### ISSUE TITLE
Feature set completion

### ISSUE THREAD

**Issue by stekyne** [kblok/puppeteer-sharp#1]
Hey,

This seems like a great library. I was wondering how complete it is relative to the JS version? 

Thanks

**Comment by kblok** [comment]
@stekyne Work in progress. I started migrating some classes in the few weeks I'll start migrating the tests first rather than the code so the progress is reflected on the tests.

Any help will be appreciated.

**Comment by tommymonk** [comment]
Great work @kblok, I'm eagerly awaiting.

How do you dispose the session of a Page, either I've missed something or it isn't implemented yet ?

The node implementation has a Close method.

**Comment by kblok** [comment]
Hey @tommymonk, thanks!

I'm the first one how wants to have at least **something**!! to deliver :)
Regarding the Page.Close, Thanks for pointing that out. I missed that method. I've just added that to my to-do list.

I want, and I think I need, to write a post next week about what's the actual progress on this project and what's the roadmap.
In a few words, I have only one test which I'm trying to make it turn green. Yes, it's only one test, but behind "Open a browser and navigate a page" there are tons of things going on. The puppeteer project is great. My current status is that I'm being able to create a process, open a web socket,  request for a new tab/page to be opened and start getting events from chromium. This morning I was working on building the FrameTree I'm getting from chromium.
After I get my first page running, first I'll have a beer, and then I think the first features to implement will be taking screenshots and printing pages to PDF.

Feel free to follow me on twitter @hardkoded I'll try to post some news there.

**Comment by Joe118** [comment]
Dario

Here's some encouragement for continuing this work -- great idea to provide an API that's similar to what a lot of people are already familiar with. Why reinvent the wheel (thumbs-up). Also, in terms of amount of stuff to download, this looks like it's a lot leaner than using CEF and opening the browser in headless mode.

Could you put together a roadmap with some tentative goalposts? Thanks!

**Comment by kblok** [comment]
Thank you @Joe118 for your kind words. I will definitely make a post next week about the current progress and roadmap.

**Comment by adriangonzalez** [comment]
@kblok Have you considered creating a project board? [Project](https://github.com/kblok/puppeteer-sharp/projects)

**Comment by kblok** [comment]
Good idea @adriangonzalez! I've never used the projects tab. I'll give it a try!

**Comment by PhenX** [comment]
Hello @kblok I'm following this projet closely as I need to use it at work, and I'd like to know when you think you'll be able to publish a new version on [NuGet](https://www.nuget.org/packages/PuppeteerSharp/).

Thank you for your work !

**Comment by kblok** [comment]
Hey @PhenX. Thank you man

How would you use this library? I'm going to publish the roadmap next Monday. That will help you to know when you could get a useful version.

**Comment by PhenX** [comment]
@kblok I'll use it to generate PDF documents from HTML. I already did this with NodeServices + NodeJS Puppeteer, but that's a bit too complicated for what I need to do.

**Comment by kblok** [comment]
@PhenX lucky you! That's the first thing I want to implement, after being able to load at least one page :p

**Comment by PhenX** [comment]
Great news :) keep up the good work, can't wait to try it

**Comment by PhenX** [comment]
@kblok Don't hesitate to tell me how I could help if you want

**Comment by kblok** [comment]
Hey guys, I have published our [first monthly report 
](http://www.hardkoded.com/blogs/puppeteer-sharp-monthly-february-2018)!. I also updated the [readme](https://github.com/kblok/puppeteer-sharp/blob/master/README.md).

@PhenX  I would really appreciate your help! So this what I wrote in the report:

>I won’t accept code contributions to the library before version 0.3 because the code is still taking shape, and because I will create the contributing document in version 0.2. However, you are welcome to start writing tests. We have 523 tests to code! 

These are my next steps:
 * Create a Project on Github.
 * Implement the downloader (I'm copying chromium manually now).

But besides that, if you want to start writing test, that will be awesome! we have 523 to write. I know it might not be the funniest part, but we really need that, I bet that many tests will just turn green, and we can ignore the others.

If you are interested, shoot me an email.

**Comment by tommymonk** [comment]
Just to mention that one of my must-have functions is "evaluate" in order to execute arbitrary script and return objects. Number two on my list is Screenshot which is already on the roadmap.

**Comment by kblok** [comment]
Hey @tommymonk. That's down the list, not because it's not important, I love that feature. The main issue is that I don't have quite clear how's that implemented. How it parses javascript code and sends it through a WebSocket, once we solve that, then we'd need to code all the interfaces necessary to map the javascript model in C#. We'll get there.

**Comment by stekyne** [comment]
https://chromedevtools.github.io/devtools-protocol/tot/Page#method-addScriptToEvaluateOnNewDocument

https://github.com/GoogleChrome/puppeteer/blob/660b65780f51d86ad615b7871bdf125b505624e6/lib/Page.js#L331

Doesn't Puppeteer just use the Chrome Debugging Protocol underneath? The parsing will occur in the browser.

I think you could replicate the Puppeteer API by using something like https://github.com/BaristaLabs/chrome-dev-tools-runtime, to implement the debugging protocol. Then you'd just have to implement the Pupetteer API, in C#, using the aforementioned library. Unless I'm missing something of course!

**Comment by kblok** [comment]
@stekyne that part is easy in Javascript, because `yourFunction.toString()` returns the function's code:
<img width="234" alt="screen shot 2018-02-06 at 10 32 26 am" src="https://user-images.githubusercontent.com/2198466/35862114-35d88134-0b29-11e8-815a-e19e10b3c28a.png">

That's not so easy in C#. I think my first approach would be implementing that as string. This will be easy:

```
page.evaluate($"document.getElementById('{foo}').innerHtml");
```

But this:

```
page.evaluate((foo) => document.getElementById(foo).innerHtml, foo);
```

First, we'd need the `document` interface/class and the `HTMLElement` class and then turn that into a string. Barista is using expressions as string.

Thank's for your feedback! It'll be great when we get this working and you start using it!

**Comment by tommymonk** [comment]
Just to be clear, I was referring to https://chromedevtools.github.io/devtools-protocol/tot/Runtime#method-evaluate

**Comment by kblok** [comment]
@tommymonk yeah, we'll get that for sure.

**Comment by stekyne** [comment]
You want to embed any arbitrary Javascript in C# code? I think that's pretty ambitious. It wouldn't be worth doing for what is essentially one method call on the API. The Chrome Debugging API itself only returns an ID string for that method so you'd have to wonder what you'd be gaining.

**Comment by kblok** [comment]
Agreed @stekyne

**Comment by tommymonk** [comment]
It actually is more sophisticated than that, when you set the returnByValue and entire JSON representation of the object is returned.
I'm currently using the [https://github.com/MasterDevs/ChromeDevTools](ChromeDevTools) project, but have found it to be quite flaky.

**Comment by stekyne** [comment]
@tommymonk That project only supports up to version 62. The other one posted is at 64. Might be a source of issues.
