### ISSUE TITLE
WaitForFunctionAsync throw is not a function

### ISSUE THREAD

**Issue by ismaeldcom** [kblok/puppeteer-sharp#1024]
Hi @kblok ,

First I want to thanks you for bringing this project to life.

I think this is a more a documentation issue or a lack o clarification. In the main README the example of WaitForFunctionAsync show:
```csharp
page.WaitForFunctionAsync("window.innerWidth < 100");
```
But this throws `(window.innerWidth < 100) is not a function`. Although the string function is valid in puppeteer.

I suppose you should indicate the need to include the definition of the function and not only the body in order for it to work. Updating README to that:
```csharp
page.WaitForFunctionAsync("() => window.innerWidth < 100");
```

Regards

**Comment by kblok** [comment]
@ismaeldcom thanks for reporting this.
If you want to make a PR for this go for it! otherwise, let me know, and I'll create one.
