### ISSUE TITLE
Page.EvaluateOnNewDocumentAsync  does not work according to Example

### ISSUE THREAD

**Issue by eludias** [kblok/puppeteer-sharp#1030]
### Description

`Page.EvaluateOnNewDocumentAsync` does not work according to documentation:
it assumes that first-argument 'pageFunction' is a function-name instead of an expression to evaluate in Page context, Therefore instead of evaluating expression 'pageFunction', it evaluates  '(pageFunction)();' instead.

Therefore the provided, shared sample from [PuppeteerSharp](https://www.puppeteersharp.com/api/PuppeteerSharp.Page.html#PuppeteerSharp_Page_EvaluateOnNewDocumentAsync_System_String_System_Object___) and [puppeteer](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pageevaluateonnewdocumentpagefunction-args):

```
var overrideNavigatorLanguages = @"Object.defineProperty(navigator, 'languages', {
  get: function() {
    return ['en-US', 'en', 'bn'];
  };
});";
await page.EvaluateOnNewDocumentAsync(overrideNavigatorLanguages);
```

...does not work.

### Complete minimal example reproducing the issue

```csharp
// Arrange
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
var launchOptions = new LaunchOptions { Headless = false, DefaultViewport = null, Devtools = true };
var browser = await Puppeteer.LaunchAsync(launchOptions);
var page = (await browser.PagesAsync()).First();

// Act
var overrideNavigatorLanguages = @"Object.defineProperty(navigator, 'languages', { get: function() { 
    return ['en-US', 'en', 'bn']; 
}; });";
await page.EvaluateOnNewDocumentAsync(overrideNavigatorLanguages);
await page.GoToAsync("about:blank");

// Check
var res = (JArray)await page.EvaluateExpressionAsync("navigator.languages");
Debug.Assert(res.Count == 3);
```

### Expected behavior:

'navigator.languages' set to `en-US`, `en` and `bn`.

### Actual behavior:

In Chrome dev console: `Uncaught SyntaxError: Unexpected token ;`, because it tries to execute

```
(Object.defineProperty(navigator, 'languages', {
                  get: function() { return ['en-US', 'en', 'bn']; };
                });)()
```

(so with `)()` added at end).

### Versions

* PuppeteerSharp version: latest stable from NuGet: 1.12.1
* .NET runtime and version are you targeting: .NET framework 4.7.2

### Additional Information

None.

**Comment by eludias** [comment]
Additionally, there is a bug in the sample, also resulting in the same `Uncaught SyntaxError`.

The sample:
```
var overrideNavigatorLanguages = @"Object.defineProperty(navigator, 'languages', {
  get: function() {
    return ['en-US', 'en', 'bn'];
  };
});";
await page.EvaluateOnNewDocumentAsync(overrideNavigatorLanguages);
```

has one semi-colon too many and therefore must be:

```
var overrideNavigatorLanguages = @"Object.defineProperty(navigator, 'languages', {
  get: function() {
    return ['en-US', 'en', 'bn'];
  }
});";
await page.EvaluateOnNewDocumentAsync(overrideNavigatorLanguages);
```

**Comment by kblok** [comment]
Thanks for reporting this @eludias. I'll take a look at it.

**Comment by kblok** [comment]
@eludias the documentation was wrong. Puppeteer's documentation is hiding the real implementation because they are injecting the content of `preload.js` and we don't know what's there.

Long story short, `EvaluateOnNewDocumentAsync` expects a function not an expression. You can check the attached PR.
