### ISSUE TITLE
PuppeteerSharp.AspNetFramework 1.12.1 not available on NuGet

### ISSUE THREAD

**Issue by mjohnson0580** [kblok/puppeteer-sharp#1032]
Hello,

Just checking when PuppeteerSharp.AspNetFramework 1.12.1 will be available on NuGet.

Many thanks.

**Comment by kblok** [comment]
Hey @mjohnson0580 I'm not pushing a new version of `PuppeteerSharp.AspNetFramework` if we don't need to. v1.12 is the latest version.
