### ISSUE TITLE
Error on first run on Ubuntu 18.04

### ISSUE THREAD

**Issue by DominicBoettger** [kblok/puppeteer-sharp#1034]
### Description

After upgrading to the latest version of p-sharp I get the error on the first run (auto download chrome):
Unable to load shared library 'MonoPosixHelper' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libMonoPosixHelper: cannot open shared object file: No such file or directory

When running a second time the error is gone until I delete the .local-chromium directory again.

**Comment by kblok** [comment]
@DominicBoettger did you take a look at this issue? https://github.com/kblok/puppeteer-sharp/issues/853

**Comment by DominicBoettger** [comment]
Thanks a lot.
But looks more like a workaround for that. I did not figure out yet why it works on the second run and it's a bit strange to install the whole mono develop for that...

**Comment by kblok** [comment]
If you know a way to implement this https://github.com/kblok/puppeteer-sharp/blob/3263458186d181b55424f984d423544f6a7ceee6/lib/PuppeteerSharp/Helpers/Linux/LinuxSysCall.cs#L12 without installing mono, you know that I would gladly review your PR :)

**Comment by DominicBoettger** [comment]
Maybe with ... https://www.nuget.org/packages/Mono.Posix.NETStandard/1.0.0

**Comment by kblok** [comment]
One little thing there. we don't need to affect Windows installments.
If that package will work on windows I'm good with it.

**Comment by scabana** [comment]
Just opened this: https://github.com/kblok/puppeteer-sharp/issues/1035

**Comment by DominicBoettger** [comment]
Do we have a solution yet and is it published to nuget? Sorry, just not sure....

**Comment by kblok** [comment]
@DominicBoettger  We are shipping v1.14 on Monday.
