### ISSUE TITLE
Remove need for Mono

### ISSUE THREAD

**Issue by scabana** [kblok/puppeteer-sharp#1035]
### Description

puppeteer-sharp depends on Mono.

### Complete minimal example reproducing the issue

Run this code on linux: 

```csharp
new PuppeteerSharp.BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision).GetAwaiter().GetResult();
```

### Expected behavior:

Run ```BrowserFetcher.DownloadAsync``` when Mono is not installed and it works.

### Actual behavior:

When run in linux and mono is not installed, it fails.

### Versions

PuppeteerSharp 1.12.1
.NET Core 2.2.101

### Additional Information

A package released by Mono supports the required calls to the current mono dependencies. Updated code can be found here: https://github.com/scabana/puppeteer-sharp/commit/1c490dfc, I can open a PR when ever...

**Comment by scabana** [comment]
@kblok hi, think you'll be able to release a version of this as you mentionned? (1.13.1)

Thanks!

**Comment by kblok** [comment]
@scabana can you wait till next Monday? 1.14 is around the corner.

**Comment by scabana** [comment]
@kblok monday's good, thanks
