### ISSUE TITLE
Newtonsoft.Json.JsonSerializationException Error converting value "default"

### ISSUE THREAD

**Issue by sseyalioglu** [kblok/puppeteer-sharp#1037]
### Description

While debugging, I always get the following exception following NewPageAsync

Newtonsoft.Json.JsonSerializationException: Error converting value "default" to type 'PuppeteerSharp.DOMWorldType'. Path 'context.auxData.type'. ---> System.ArgumentException: Requested value 'default' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber) in /_/Src/Newtonsoft.Json/Utilities/EnumUtils.cs:line 367
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /_/Src/Newtonsoft.Json/Converters/StringEnumConverter.cs:line 238
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /_/Src/Newtonsoft.Json/Converters/StringEnumConverter.cs:line 253
   at PuppeteerSharp.Helpers.Json.FlexibleStringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)

More detail:
System.ArgumentException: Requested value 'default' was not found.
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber) in /_/Src/Newtonsoft.Json/Utilities/EnumUtils.cs:line 367
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in /_/Src/Newtonsoft.Json/Converters/StringEnumConverter.cs:line 238

### Complete minimal example reproducing the issue

var browser = await Puppeteer.LaunchAsync(new LaunchOptions
{
   ExecutablePath = _downloader.GetExecutablePath(BrowserFetcher.DefaultRevision),
   Headless = true,
   Devtools = false,
   LogProcess = true,
   Timeout = 60000
});
var page = await browser.NewPageAsync();

### Expected behavior:

No exception to occur. I've checked the source code and there is obviously no such thing as "default" in the Enum.

### Actual behavior:

Always throws exception

### Versions

Mac OS Moojave
.NET Core 2.2
PuppeteerSharp 1.12.1

**Comment by kblok** [comment]
thank you for the report @sseyalioglu ?

**Comment by kblok** [comment]
@sseyalioglu Maybe your IDE settings is to break in all exceptions?
We are catching that exception here https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Helpers/Json/FlexibleStringEnumConverter.cs#L17

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.

**Comment by rgelb** [comment]
I have also encountered this behavior with VS 2019 and 2017 on Windows.  Only in my project though.  When I create a brand new project, I can't replicate this problem.  All errors are set to not Break.  

When the error is first encountered - it asks to download source from github to continue debugging (that's how I got to this screen).  I previously used v 1.12.1 - I didn't see this issue.  It's possible that it's occurring due to installation of VS 2019, but I don't know.

![2019-04-20 15_18_19-Widgets (Debugging) - Microsoft Visual Studio](https://user-images.githubusercontent.com/1064250/56463190-a31d9000-6383-11e9-8040-4c9a4c03382b.png)

**Comment by sseyalioglu** [comment]
I use Rider from JetBrains and during debugging I make sure that only my code's exceptions are caught. However for some reason this one (although it is catched), makes debugger to stop.
I have similar situation AWS S3 package when checking if file exists (throws when there is no file).

**Comment by rgelb** [comment]
@kblok This was an issue with Newtonsoft 12.0.1.  I upgraded to 12.0.2 (which was released 4 days ago) and the errors seem to have disappeared.

**Comment by kblok** [comment]
awesome!

**Comment by sseyalioglu** [comment]
good to hear. I will confirm once I am done on my part. Please give me a week or 2.

**Comment by sseyalioglu** [comment]
I confirm this is solved for me as well.

**Comment by jnyrup** [comment]
Even though `"default"` is caught by the try/catch mentioned above I'm wondering how the value ever appeared and if it's expected?

Here's some state info I could extract in case it can help anyone track down that `"default"`.

Value of the `PuppeteerSharp.Transport.MessageReceivedEventArgs.Message` that fails to be deserialized:
```json
{
    "method": "Runtime.executionContextCreated",
    "params": {
        "context": {
            "id": 1,
            "origin": "://",
            "name": "",
            "auxData": {
                "isDefault": true,
                "type": "default",
                "frameId": "D0984781F443465FF12AD6BB2EC7BD7C"
            }
        }
    },
    "sessionId": "D03CF313B0D28AEE29EA08D7C8F5DF70"
}
```

`PuppeteerSharp.Connection.Url = "ws://127.0.0.1:56572/devtools/browser/99841efa-1390-49e6-81de-b069631a76a6"`

PuppeteerSharp tasks running:
```
PuppeteerSharp.Browser.PagesAsync()	PuppeteerSharp.Browser.PagesAsync()
PuppeteerSharp.BrowserContext.PagesAsync()	PuppeteerSharp.BrowserContext.PagesAsync()
PuppeteerSharp.CDPSession.SendAsync(method, args, waitForCallback)	PuppeteerSharp.CDPSession.SendAsync(method, args, waitForCallback)
PuppeteerSharp.CDPSession.SendAsync(method, args, waitForCallback)	PuppeteerSharp.CDPSession.SendAsync(method, args, waitForCallback)
PuppeteerSharp.FrameManager.CreateFrameManagerAsync(client, page, ignoreHTTPSErrors, timeoutSettings)	PuppeteerSharp.FrameManager.CreateFrameManagerAsync(client, page, ignoreHTTPSErrors, timeoutSettings)
PuppeteerSharp.NetworkManager.InitializeAsync()	PuppeteerSharp.NetworkManager.InitializeAsync()
PuppeteerSharp.Page.CreateAsync(client, target, ignoreHTTPSErrors, defaultViewPort, screenshotTaskQueue)	PuppeteerSharp.Page.CreateAsync(client, target, ignoreHTTPSErrors, defaultViewPort, screenshotTaskQueue)
PuppeteerSharp.Page.InitializeAsync(ignoreHTTPSErrors)	PuppeteerSharp.Page.InitializeAsync(ignoreHTTPSErrors)
PuppeteerSharp.Target.CreatePageAsync()	PuppeteerSharp.Target.CreatePageAsync()
```
