### ISSUE TITLE
use IAsyncLifetime for test classes

### ISSUE THREAD

**Issue by Meir017** [kblok/puppeteer-sharp#106]
we should implement the interface `IAsyncFixture` and use the methods:
```cs
Task SetupAsync();
Task TeardownAsync();
```
for the test classes that require a `Browser` / `Page`
https://github.com/xunit/xunit/pull/531/commits/68bf5b62f625b130baa90b20d37b1933ec3e153b

**Comment by kblok** [comment]
Would those methods be called before and after **each** test?

**Comment by Meir017** [comment]
it's been renamed to [`IAsyncLifetime`](https://github.com/xunit/xunit/blob/master/src/xunit.core/IAsyncLifetime.cs).
it runs when the class is created.

we could use it in `PuppeteerLoaderFixture.cs`, doesn't really add much :(

**Comment by PhenX** [comment]
FYI, I made this change in #125, I thought it would fix the tests, but it did not :(
