### ISSUE TITLE
PuppeteerSharp.ResponseData Read-Only

### ISSUE THREAD

**Issue by vbisbest** [kblok/puppeteer-sharp#1063]
It appears that PuppeteerSharp.ResponseData properties are read only.  I am trying to return a response in the request interception but it is not allowed to set the Status and Body properties.
                              
await e.Request.RespondAsync(new PuppeteerSharp.ResponseData
                            {
                                Status = HttpStatusCode.OK,
                                Body = intermediateHtml.ToString()
                            });

**Comment by kblok** [comment]
@vbisbest take a look at this test https://github.com/kblok/puppeteer-sharp/blob/d432f026d78c1dede71b3c2f401feb81d30c334f/lib/PuppeteerSharp.Tests/NetworkTests/RequestRespondTests.cs#L23

**Comment by vbisbest** [comment]
Sorry, was on older version of puppeteerSharp.  Thanks!
