### ISSUE TITLE
Mono.Posix.NETStandard package required mono

### ISSUE THREAD

**Issue by kblok** [kblok/puppeteer-sharp#1069]
Users are getting this error.
"Severity	Code	Description	Project	File	Line	Suppression State
Error	Failed to add reference. The package 'Mono.Posix.NETStandard' tried to add a framework reference to 'Mono.Posix' which was not found in the GAC. This is possibly a bug in the package. Please contact the package owners for assistance.
Error HRESULT E_FAIL has been returned from a call to a COM component."

**Comment by kblok** [comment]
@scabana could you take a look at this. We will need a v1.14.1 ASAP

**Comment by kblok** [comment]
Error reported by @AzeExMachina here #1068

**Comment by scabana** [comment]
Hey, I'll take a look tomorrow morning. Got a few ideas, hope I can repro the issue.

**Comment by AzeExMachina** [comment]
If it can be useful, I could replicate it simply by just starting a new empty project and trying to add the nuget package for puppeteer-sharp
