### ISSUE TITLE
Payload not being applied to request

### ISSUE THREAD

**Issue by vbisbest** [kblok/puppeteer-sharp#1071]
using 1.14

When applying post data in the Request event, the payload is not being applied.

Example in Request event:
```
                Payload payload = null;

                if (currentLink.PostData != null)
                {
                    payload = new Payload()
                    {
                        Url = currentLink.Url,
                        Method = System.Net.Http.HttpMethod.Post,                                                
                        PostData = currentLink.PostData
                    };                    
                }

                e.Request.ContinueAsync(payload);
```

In the Response event, you can see that the post data and method are incorrect.  The payload does not appear to have been applied.  

![Untitled](https://user-images.githubusercontent.com/3143293/55894878-10157680-5b89-11e9-8280-ade4a607adc2.png)

**Comment by kblok** [comment]
I think when we implement this https://github.com/GoogleChrome/puppeteer/pull/4248 on v1.15 this will be fixed.

**Comment by kblok** [comment]
I checked this with the latest version and it won't work in the way you expected.
`e.Response.Request` is the very same object you got in the `Request` event. `ContinueAsync` does not alter in `Request` object. It just sends that data to Chromium.

**Comment by jmalStorm** [comment]
I am having the same issue with PostData. So how to do Post request?
