### ISSUE TITLE
Page.ScreenshotDataAsync never returns in a web environment with the latest Chromium (v75)

### ISSUE THREAD

**Issue by rgelb** [kblok/puppeteer-sharp#1101]
### Description

`page.ScreenshotDataAsync` never returns in a web environment with the latest Chromium (v75) **regardless of whether the browser is in Headless mode or not**.   This example and repro have it in Headless mode.
I deploy this sample project to IIS on Windows Server 2016. 

It works fine on local Kestrel browser (run via `dotnet run`).  

### Complete minimal example reproducing the issue

The repro is at https://github.com/rgelb/PuppetScreenshotRepro

But to do it manually 
Create a new .NET Core MVC project.  
Change Privacy action on the HomeController to be async.  Will use this Action to test the issue.
Call `await KickThisOff()` from the Privacy action.  
Add the `KickThisOff` method to the HomeController.cs

The method does the folllowing:

Downloads the browser, 
Launches it
Creates a Page via `NewPageAsync`
Sets the Viewport via `SetViewportAsync`
Goes to the page via `GoToAsync`
Waits for a selector to appear via `WaitForSelectorAsync`
Calls `ScreenshotDataAsync`

### Expected behavior:

`ScreenshotDataAsync` should return

### Actual behavior:

`ScreenshotDataAsync` never returns

### Versions
.local-chromium Win64-641577
PuppeteerSharp 1.14
.NET Core 2.2

### Additional Information
Depending on the rights on your server, you might have to download chromium manually and point to it via LaunchOptions.ExecutablePath

More info.  This worked with Chromium 72 and PuppeteerSharp 1.14.  And I would have stayed with that, but that combination had a peculiar bug where WaitForSelectorAsync would fail if the page was reused a 100 times (e.g. `for(x=1 to 1000) page.GoToAsync(url); page.WaitForSelector(".foo")`.  WaitForSelector would fail when x reached 100.

It's possible this problem has something to do with issue [1076 ](https://github.com/kblok/puppeteer-sharp/issues/1076) and [4341](https://github.com/GoogleChrome/puppeteer/issues/4341).

**Comment by kblok** [comment]
Close as duplicated
