### ISSUE TITLE
nuget package fails to install

### ISSUE THREAD

**Issue by GerhardKreuzer** [kblok/puppeteer-sharp#1104]
Hi,
I tried to install the nuget package, but it Fails.

OS: Win 10
.net: 4.7.2 (so is higher than 4.6.1
VS2017

Another issue is closed, but I can't find a solution in it.

With bets regards

Gerhad

**Comment by kblok** [comment]
Hey @GerhardKreuzer what errors are you getting?

**Comment by GerhardKreuzer** [comment]
.. tried to add a Picture, but  .

**Comment by GerhardKreuzer** [comment]
sorry, no idea how to add a Picture. Drag & Drop Fails and selecting Fails.

Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler		Fehler beim Hinzufügen eines Verweises. Das Paket "Mono.Posix.NETStandard" hat versucht, "Mono.Posix" einen Frameworkverweis hinzuzufügen, der im GAC nicht gefunden wurde. Dies ist möglicherweise ein Fehler im Paket. Wenden Sie sich an die Besitzer des Pakets, um Unterstützung zu erhalten.
Unbekannter Fehler (Ausnahme von HRESULT: 0x80004005 (E_FAIL))				

Ah, this works.

**Comment by kblok** [comment]
Oh yeah. We already fixed that. I'll release a new version fixing this next Monday.

**Comment by GerhardKreuzer** [comment]
.. Monday, … so I will loose two days!

I only can access the website off normal hours, so Saturday and Sunday were great days for working …

 

Thanks.

 

With best regards

 

Gerhard

 

Von: Darío Kondratiuk [mailto:notifications@github.com] 
Gesendet: Freitag, 03. Mai 2019 19:44
An: kblok/puppeteer-sharp
Cc: Gerhard; Mention
Betreff: Re: [kblok/puppeteer-sharp] nuget package fails to install (#1104)

 

Oh yeah. We already fixed that. I'll release a new version fixing this next Monday.

**Comment by kblok** [comment]
@GerhardKreuzer you could download the source code and build it locally till we have a new version. The fix is already in master.

**Comment by GerhardKreuzer** [comment]
Hi,
thanks. I get a sample working now.

Two questions:
- It takes a Long time to load the chromium component, his isn't that Handy.
- Can I have more than one session at the same time?

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
Hi,
still runs into Problems.
Want to create an own Project but gets an error. 
Cant find this assembly.

Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler	BC30652	Es ist ein Verweis auf die Assembly "Microsoft.Extensions.Logging.Abstractions, Version=2.0.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" erforderlich, die den Typ "ILoggerFactory" enthält. Fügen Sie dem Projekt einen Verweis hinzu.	ConsoleApp1	C:\Users\Gerhard\AppData\Local\Temporary Projects\ConsoleApp1\Program.vb	13	Aktiv
Thanks for helping again.

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
Hi,
ok, found out that there is a missing nuget package and now it compiles, but doesn't function properly.

Situation:
Want to use Puppeteer in a VB.net Project targeting .net 4.7.2, or .net Standard 2.0, which should be the same.
I want to have more than one Independent session.

Ok. I transcriped the sample as a starting Point, it compiles, but the Task never starts. I also get now runtime exception. It just do nothing.

I patched the original sample so it Looks quite similar to mine and it works:

namespace Example.GetAllLinks
{
    class Program
    {
        //public static async Task MainXX(string[] args)
            public static async void MainXX()
        {
            var options = new LaunchOptions { Headless = true };
            Console.WriteLine("Downloading chromium");
            await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
            Console.WriteLine("Navigating to google.com");

            using (var browser = await Puppeteer.LaunchAsync(options))
            using (var page = await browser.NewPageAsync())
            {
                await page.GoToAsync("http://www.google.com");
                var jsSelectAllAnchors = @"Array.from(document.querySelectorAll('a')).map(a => a.href);";
                var urls = await page.EvaluateExpressionAsync<string[]>(jsSelectAllAnchors);
                foreach (string url in urls)
                {
                    Console.WriteLine($"Url: {url}");
                }
                //Console.WriteLine("Press any key to continue...");
                //Console.ReadLine();
                Console.WriteLine("Finished ...");
            }
        }

        public static void Main()
        {
            // Create new Task.
            Task t = new Task(MainXX);
            // Start the task.
            t.Start();
            Thread.Sleep(300);
            Task t1 = new Task(MainXX);
            t1.Start();
            Console.WriteLine("Starting browser...");
            Console.ReadLine();
        }
    }
}

I get two instances. Ok, this is very quick and dirty but it works for now.

Your sample targeting .net Core 2.1.

Do you ever tried against .net Standard 2.0? Or .net 4.7.2? May be this the difference?

How can I use Puppeteer with other language than C#, I guess this should not be a problem, this is the key benefit of the .net platform.

Any hints, ideas?

Thanks for helping.

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
... I tried to wrote 'I get NO runtime exception ..', sorry. And Editing doesnt work out here ....

**Comment by GerhardKreuzer** [comment]
Hi,
here the VB code snippet:
Public Class Program

    Shared Sub Main()
        ' Create new Task.
        Dim t As Task = New Task(AddressOf GetAllLinksAsync)
        ' Start the task.
        t.Start()
        'Threading.Thread.Sleep(300)
        'Dim t1 As Task = New Task(AddressOf GetAllLinksAsync)
        't1.Start()
        Console.WriteLine("Starting browser...")
        Console.ReadLine()
    End Sub

    Private Shared Async Sub GetAllLinksAsync()
        Beep()
        Dim options = New LaunchOptions With {.Headless = True}
        Console.WriteLine("Downloading chromium")
        Await (New BrowserFetcher()).DownloadAsync(BrowserFetcher.DefaultRevision)
        Console.WriteLine("Navigating to google.com")

        'Dim bb As Browser = Await Puppeteer.LaunchAsync(options)

In the Moment where the last line is active, the Task didn't start, and there is no error message.
Without this line, the Tasks starts as expected.

I don't use the 'Using' construct here to get the things simpler. But it Shows the same behaviour with the 'Using' block.

Ok, no Chance today to use Puppeteer ...

With best regards

Gerhard

**Comment by kblok** [comment]
You have many examples here showing how to write console apps without using `Task.Start` https://github.com/kblok/puppeteer-sharp/tree/master/samples

**Comment by GerhardKreuzer** [comment]
I used exactly this samples ...

**Comment by GerhardKreuzer** [comment]
The problem isn't t.start, the problem is, that the task only runs when the line 'browser = Await Puppeteer.LaunchAsync(Options) isn't in. It   is funny but it is true.
As Puppeteer should also work with .net Standard 2.0, as the docu told me, I am quite sure, I do nothing wrong.

So, did you ever tried this samples with .net Standard 2.0? If not I will try to port them and we will see ..

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
Hi Dario,

 

here ist he problem:

 



 

Hope the Monday package will work fine.

 

With best regards

 

Gerhard

 

Von: Darío Kondratiuk [mailto:notifications@github.com] 
Gesendet: Samstag, 04. Mai 2019 21:42
An: kblok/puppeteer-sharp
Cc: Gerhard; Mention
Betreff: Re: [kblok/puppeteer-sharp] nuget package fails to install (#1104)

 

You have many examples here showing how to write console apps without using Task.Start https://github.com/kblok/puppeteer-sharp/tree/master/samples

**Comment by GerhardKreuzer** [comment]
Hi Dario,

 

and here the next one:

 



 

Unfortunately I can’t load this package, cause I get the error that the filename is longer than 260 characters ……

 

With best regards

 

Gerhard

 

Von: Darío Kondratiuk [mailto:notifications@github.com] 
Gesendet: Samstag, 04. Mai 2019 21:42
An: kblok/puppeteer-sharp
Cc: Gerhard; Mention
Betreff: Re: [kblok/puppeteer-sharp] nuget package fails to install (#1104)

 

You have many examples here showing how to write console apps without using Task.Start https://github.com/kblok/puppeteer-sharp/tree/master/samples

**Comment by GerhardKreuzer** [comment]
.. it  is working now, get it running early this morning.

 

With best regards

 

Gerhard

 

Von: Darío Kondratiuk [mailto:notifications@github.com] 
Gesendet: Samstag, 04. Mai 2019 21:42
An: kblok/puppeteer-sharp
Cc: Gerhard; Mention
Betreff: Re: [kblok/puppeteer-sharp] nuget package fails to install (#1104)

 

You have many examples here showing how to write console apps without using Task.Start https://github.com/kblok/puppeteer-sharp/tree/master/samples

**Comment by GerhardKreuzer** [comment]
Hi Dario,

 

now I get this:

 



 

It  is the function of this button, to open a new tab and present a new page.

 

Is there any chance to get the content of a page as a string, stream or something else?

Where there good samples out showing how ‘selector’ is to built?

 

With best regards

 

Gerhard

 

 

Von: Darío Kondratiuk [mailto:notifications@github.com] 
Gesendet: Samstag, 04. Mai 2019 21:42
An: kblok/puppeteer-sharp
Cc: Gerhard; Mention
Betreff: Re: [kblok/puppeteer-sharp] nuget package fails to install (#1104)

 

You have many examples here showing how to write console apps without using Task.Start https://github.com/kblok/puppeteer-sharp/tree/master/samples

**Comment by GerhardKreuzer** [comment]
oops, answere your mail and fool the Forum site, peg my pardon ...

**Comment by kblok** [comment]
v1.14.1 published
