### ISSUE TITLE
Protocol error (Runtime.callFunctionOn): Promise was collected CDPSession

### ISSUE THREAD

**Issue by sseyalioglu** [kblok/puppeteer-sharp#1106]
### Description

We have a binary URL to download some CSV file which is opened through a function evaluation. 
Because we want to download the file to a specific location we've set the download path specifically (full path) however we keep on getting this exception which is a blocker.

Exception:
One or more errors occurred. (Protocol error (Runtime.callFunctionOn): Promise was collected)

Inner Exception:
PuppeteerSharp.MessageException: Protocol error (Runtime.callFunctionOn): Promise was collected
   at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback)
   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args)
   at PuppeteerSharp.ExecutionContext.EvaluateHandleAsync(String method, Object args)
   at PuppeteerSharp.ExecutionContext.EvaluateFunctionHandleAsync(String script, Object[] args)

### Complete minimal example reproducing the issue

Complete means the code snippet can be copied into a unit test method in a fresh C# project and run.
Minimal means it is stripped from code not related to reproducing the issue.

E.g.

        public async Task<string> TryExecuteScriptAsync(string functionName, object[] parameters, bool shouldExpectNavigation, bool shouldExpectBinaryUrlDownload, bool shouldExpectDownload, EventHandler<PageExecutionEventArgs> callOnCompleteExecutionForNewTarget)
        {
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                ExecutablePath = _downloader.GetExecutablePath(BrowserFetcher.DefaultRevision),
                Headless = false,
                Devtools = true,
                LogProcess = true,
                Timeout = 60000
            });
            var _puppeteerPage = await browser.NewPageAsync();
            try
            {
                await _puppeteerPage.GoToAsync("theurlwhichdoesthat.io/path", new NavigationOptions{ Timeout = 60000, WaitUntil = new []{WaitUntilNavigation.Networkidle0}});
                Trace.WriteLine($"In TryExecuteScriptAsync for {functionName} with shouldExpectNavigation = {shouldExpectNavigation} & shouldExpectBinaryUrlDownload = {shouldExpectBinaryUrlDownload} & shouldExpectDownload = {shouldExpectDownload}");
                var result = "unknown";
                if (shouldExpectNavigation)
                {
                    var evaluationResponseThatIsNotWaitedOnPurpose = _puppeteerPage.EvaluateFunctionAsync(functionName, parameters); /* We don't wait here because for binary url downloads we need to setup download path before download happens */
                    if (shouldExpectBinaryUrlDownload)
                    {
                        var newTarget = await _puppeteerPage.Browser.WaitForTargetAsync(t => t.Opener == _puppeteerPage.Target);
                        var client = await newTarget.CreateCDPSessionAsync();
                        await client.SendAsync("Page.setDownloadBehavior", new { behavior = "allow", downloadPath = DownloadFolder }, false);

                        return evaluationResponseThatIsNotWaitedOnPurpose.Result?.ToString() ?? result;
                    }
                    await _puppeteerPage.WaitForNavigationAsync(new NavigationOptions{ Timeout = 10000, WaitUntil = new []{WaitUntilNavigation.Networkidle0}});
                }
                else
                {
                    if (shouldExpectDownload)
                    {
                        var client = await _puppeteerPage.Target.CreateCDPSessionAsync();
                        await client.SendAsync("Page.setDownloadBehavior", new { behavior = "allow", downloadPath = DownloadFolder });
                    }

                    var waitedResponse = await _puppeteerPage.EvaluateFunctionAsync(functionName, parameters);
                    result = waitedResponse?.ToString() ?? result;
                }
                    

                return result?.ToString();
            }
            catch (EvaluationFailedException e)
            {
                if (e.InnerException?.Message == "Protocol error (Runtime.callFunctionOn): Promise was collected" && (e.InnerException?.StackTrace.Contains("CDPSession.SendAsync") ?? false))
                {
                    Trace.WriteLine("MessageException for binary url download");
                    return "all-finalized!";
                }

                return $"Script Execution Failed with {e.Message}";
            }
        }

### Expected behavior:

Code continues with the next steps after exiting the method.

### Actual behavior:

Code continues and returns from the method (without catching exception) but later on while the browser is still running (we will have other executions) it suddenly throws exception as described above.

### Versions

PS V1.14.1
.NET Core 2.2
Mac OS & Rider 2019.1

**Comment by sseyalioglu** [comment]
I think the main problem here is that, those binary pages don't go through full page lifecycle. They open and close almost instantly. Even the TargetCreated event from the browser comes after download finishes. But I was unable to find any other way of setting the download path.

**Comment by kblok** [comment]
Hey @sseyalioglu could you help me out with some code using public urls I can use to test this?

**Comment by sseyalioglu** [comment]
I will try to get the same thing simulated. Unfortunately it is not a public URL that we use and cannot share that. I think in a day we may have the simulation of the same.

**Comment by sseyalioglu** [comment]
In the meantime, can you help explaining what this means?

Protocol error (Runtime.callFunctionOn): Promise was collected

What is the possible protocol error? And what does it mean by "promise was collected"? If it was not collected, that would be more meaningful normally. (I am sure it is meaningful still)

**Comment by kblok** [comment]
`collected` means collected by the garbage collector. Chromium sends that message to all promises it's about to kill.

**Comment by sseyalioglu** [comment]
That's helpful. What might be the "Protocol error" in this case? 

And what normally should be done to prevent "collection" exception.
Note: When binary url exists, it generally happens quite fast. Opens the new tab, downloads file and tab closes instantly.

**Comment by kblok** [comment]
My feeling is that the Session is crashing before or during that evaluation.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
