### ISSUE TITLE
Deployed in centos 7 throw exception

### ISSUE THREAD

**Issue by gainorloss** [kblok/puppeteer-sharp#1107]
### Description

[Description of the issue]

### Complete minimal example reproducing the issue

Complete means the code snippet can be copied into a unit test method in a fresh C# project and run.
Minimal means it is stripped from code not related to reproducing the issue.

E.g.

```csharp
// Arrange
// <summary>
        /// 抓取天猫某书实际售价（根据宝贝详情链接）
        /// </summary>
        /// <param name="url"></param>
        /// <returns></returns>
        [HttpGet]
        public async Task<IActionResult> TmallPrice(string url)
        {
            //var proxies = await _agentGetter.GetProxiesAsync<BaseAgentSpiderItem>();
            //proxies = proxies.Where(proxy => _agentGetter.VerifyProxyAsync(proxy.Host).Result).ToList();
            //var agent = proxies.ElementAt(new Random().Next(0, proxies.Count));
            //var agentStr = $"{agent.AgentType}://{agent.Host}:{agent.Port}";
            var sw = Stopwatch.StartNew();
            sw.Start();
            var item = await GetTianMaoPriceAsync(url);
            sw.Stop();
            return Ajax(HttpStatusCodes.Ok, item);
        }

        #region Helpers.
        private async Task<CatalogItem> GetTianMaoPriceAsync(string url, string agent = null)
        {
            var catalogItem = new CatalogItem();
            var iStart = url.IndexOf("&id=");
            var link = url.Substring(iStart + 4);
            var strs = link.Split("&");
            if (strs != null && strs.Any())
            {
                if (!string.IsNullOrEmpty(strs[0]))
                {
                    catalogItem.Id = strs[0];
                }
            }

            var html = await _htmlDownloader.DownloadHtmlContentAsync(url, async page => await page.WaitForSelectorAsync(".tm-price"), agent: agent);
            var h1 = await _htmlParser.GetElementAsync(html, ".tb-detail-hd h1");
            var span = await _htmlParser.GetElementAsync(html, ".tm-price");
            var price = span.TextContent.Trim();
            var title = h1.TextContent.Trim();
            var lis = await _htmlParser.GetElementsAsync(html, "#J_AttrUL li");
            catalogItem.Title = title;
            catalogItem.SellingPrice = Convert.ToDecimal(price);
            catalogItem.Link = url;
            foreach (var li in lis)
            {
                var content = li.TextContent.Trim();
                if (content.Contains("书名"))
                {
                    var nameStr = content.Split(':')[1];
                    if (!string.IsNullOrEmpty(nameStr))
                        catalogItem.Name = nameStr.Trim();
                    continue;
                }
                else if (content.Contains("ISBN编号"))
                {
                    var isbnStr = content.Split(':')[1];
                    if (!string.IsNullOrEmpty(isbnStr))
                        catalogItem.ISBN = isbnStr.Trim();
                    continue;
                }
                else if (content.Contains("定价"))
                {
                    var fixedPriceStr = content.Split(':')[1];
                    if (!string.IsNullOrEmpty(fixedPriceStr))
                    {
                        fixedPriceStr = fixedPriceStr.Split("元")[0];
                        if (decimal.TryParse(fixedPriceStr.Trim(), out var fixedPrice))
                            catalogItem.FixedPrice = fixedPrice;
                    }
                    continue;
                }
            }

            return catalogItem;
        }

 #region Methods for getting html content.
        public async Task<string> DownloadHtmlContentAsync(string url, Func<Page, Task> beforeGetContentHandler = null, string agent = null)
        {
            return await GetHtmlContentUsingPuppeteerAsync(url, beforeGetContentHandler, agent);
        }
        #endregion

        #region Helper.
        private async Task<string> GetHtmlContentUsingPuppeteerAsync(string url, Func<Page, Task> beforeGetContentHandler = null, string agent = null)
        {
            var expireMS = 40 * 1000;
            var option = new LaunchOptions()
            {
                Timeout = expireMS,
                Headless = true
            };

            var args = new List<string>()
            {
                "--no-sandbox",
                "--disable-setuid-sandbox"
            };

            if (!string.IsNullOrEmpty(agent))
                args.Add($"--proxy-server={agent}");

            option.Args = args.ToArray();

            using (var browser = await Puppeteer.LaunchAsync(option))
            {
                using (var page = await browser.NewPageAsync())
                {
                    await page.SetViewportAsync(new ViewPortOptions()
                    {
                        Width = 1366,
                        Height = 768
                    });
                    await page.GoToAsync(url);
                    if (beforeGetContentHandler != null)
                    {
                        await beforeGetContentHandler.Invoke(page);//control browser before get content.
                    }
                    var html = await page.GetContentAsync();
                    return html;
                }
            }
        }
        #endregion

// Act
...

// Assert
...
```

### Expected behavior:

[What you expect to happen]
Running In centos.
### Actual behavior:
[13:55:56 ERR] 在请求controller[Prices] 的 action[TmallPrice] 时产生异常【Permission denied】 ,异常堆栈【   at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at PuppeteerSharp.ChromiumProcess.State.StartingState.StartCoreAsync(ChromiumProcess p)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at Dnc.Spiders.PuppeteerHtmlDownloader.GetHtmlContentUsingPuppeteerAsync(String url, Func`2 beforeGetContentHandler, String agent)
   at Dnc.Spiders.PuppeteerHtmlDownloader.DownloadHtmlContentAsync(String url, Func`2 beforeGetContentHandler, String agent)
   at PriceParity.API.Controllers.PricesController.GetTianMaoPriceAsync(String url, String agent) in F:\Projects\Learning\src\tmall-price-spider\PriceParity.API\Controllers\PricesController.cs:line 77
   at PriceParity.API.Controllers.PricesController.TmallPrice(String url) in F:\Projects\Learning\src\tmall-price-spider\PriceParity.API\Controllers\PricesController.cs:line 57
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()

### Versions

* Which version of PuppeteerSharp are you using?
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.

### Additional Information
sourcecode:[https://gitee.com/gainorloss_259/tmall-price-spider.git]
demo deployed:[http://140.143.88.100:9000/swagger/index.html]

**Comment by kblok** [comment]
You are getting a Permission denied there. It seems that you process is not being able to launch Chromium

**Comment by gainorloss** [comment]
I am sorry that i know about linux less.What i should do will solve my  Problem.it’s need to know that the application is a normal dotnet core 2.2 web api application and i uploaded the linux-version chromium to my app's running-time directory.Even i tryied to set the runtime-directory permission but failed.I used puppeteer-sharp for a month,but i feeler it’s very cool.Look forward to hearing from u 2 give me some solutions.                        Yours sincerely------------------ 原始邮件 ------------------
发件人: "Darío Kondratiuk"<notifications@github.com>
发送时间: 2019年5月7日(星期二) 晚上11:24
收件人: "kblok/puppeteer-sharp"<puppeteer-sharp@noreply.github.com>;
抄送: "张建"<519564415@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [kblok/puppeteer-sharp] Deployed in centos 7 throw exception(#1107)



You are getting a Permission denied there. It seems that you process is not being able to launch Chromium
 
&mdash;
