### ISSUE TITLE
ChromiumProcessException headless = false on Ubuntu

### ISSUE THREAD

**Issue by sseyalioglu** [kblok/puppeteer-sharp#1109]
### Description

Deployed code to ubuntu with GUI.
When running headless=true, it does not crash.
But when running as headless=false, I get the following error.

Throws the following exception:
PuppeteerSharp.ChromiumProcessException: Failed to launch Chromium! LaunchProcess: failed to execvp:
/tmp/.chromium/Linux-641577/chrome-linux/nacl_helper
[25572:25572:0508/211701.335806:ERROR:nacl_fork_delegate_linux.cc(314)] Bad NaCl helper startup ack (0 bytes)

   at PuppeteerSharp.ChromiumProcess.State.StartingState.StartCoreAsync(ChromiumProcess p)
   at PuppeteerSharp.ChromiumProcess.State.StartingState.StartCoreAsync(ChromiumProcess p)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)
   at PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)

I have to use headless=false because downloads don't work with headless unfortunately in the past 2 years.

I can launch chromium normally from desktop but not working when triggered through code.
### Complete minimal example reproducing the issue
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                ExecutablePath = _downloader.GetExecutablePath(BrowserFetcher.DefaultRevision),
                Headless = false,
                Devtools = false,
                LogProcess = true,
                Timeout = 60000,
                Args = new []{"--no-sandbox --disable-setuid-sandbox"}
            });
Note: I've added Args after I got the hint from: https://github.com/Googlechrome/puppeteer/issues/290
### Expected behavior:

launch the browser properly and execute.

### Actual behavior:

crashes

### Versions

PuppeteerSharp 1.14.1
.NET Core 2.2
Ubuntu 16.04 (AWS) with xfce4

**Comment by kblok** [comment]
@sseyalioglu could you take a look at this? https://askubuntu.com/questions/1002496/chrome-nacl-error-in-ubuntu-14-04

**Comment by sseyalioglu** [comment]
Yes, this was done while setting up the server and verified manually as well.

**Comment by kblok** [comment]
It's something related with Chromium itself. Not with puppeteer-sharp.

**Comment by sseyalioglu** [comment]
I agree, thought you might be having some idea about it.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
