### ISSUE TITLE
change TestConstants to be like puppeteer

### ISSUE THREAD

**Issue by Meir017** [kblok/puppeteer-sharp#111]
actions:
- [ ] refactor TestConstants
- [ ] page base test class

https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/test/test.js#L81
split into 2:
* server
  * PREFIX
  * CROSS_PROCESS_PREFIX
  * EMPTY_PAGE
* httpsServer
  * PREFIX
  * CROSS_PROCESS_PREFIX
  * EMPTY_PAGE

we could split into 2 classes or just move them to the base class.

something like:
```cs
public class PuppeteerBaseTests : IAsyncLifetime
{
    protected static readonly int Port = 8907;
    ...

    protected static readonly int HttpsPort = Port + 1;
    ...

    protected Browser Browser { get; private set; }
    public async Task InitializeAsync()
    {
        Browser = await PuppeteerSharp.Puppeteer.LaunchAsync(TestConstants.DefaultBrowserOptions(), TestConstants.ChromiumRevision);
    }

    public async Task DisposeAsync()
    {
        await Browser.CloseAsync();
    }
}

public class PuppeteerPageBaseTests: PuppeteerBaseTests
{
    protected Page Page { get; private set; }
    public new async Task InitializeAsync()
    {
        await base.InitializeAsync();
        Page = await Browser.NewPageAsync();
    }

    public new async Task DisposeAsync()
    {
        await base.DisposeAsync();
        await Page.CloseAsync();
    }
}
```

this will reduce the overhead of writing `using (var page = await Browser.NewPageAsync())` in so many tests... :)

**Comment by kblok** [comment]
I think I can buy this. Could you reduce the scope of this issue so it won't overlap with https://github.com/kblok/puppeteer-sharp/issues/106 ?

**Comment by Meir017** [comment]
This issue is half done. Still need to refactor TestConstants
