### ISSUE TITLE
Transparent backgrounds on PDF's

### ISSUE THREAD

**Issue by ianewby** [kblok/puppeteer-sharp#1153]
All PDF's generated have a white background. Looking at puppeteer, there are workarounds but 
they rely on being able to send 

await page._emulationManager._client.send(
  'Emulation.setDefaultBackgroundColorOverride',
  { color: { r: 0, g: 0, b: 0, a: 0 } }
);

This is impossible in puppeteer-sharp as the classes required are internal.

Would it be possible to default the page background to transparent for puppeteer-sharp when generating pdfs?

This is what I am trying to achieve:
```
BrowserFetcher browserFetcher = new BrowserFetcher(), "Puppeteer") });
                await browserFetcher.DownloadAsync(BrowserFetcher.DefaultRevision);
                var browser = await Puppeteer.LaunchAsync(new LaunchOptions
                {
                    Headless = true
                });
                var page = await browser.NewPageAsync();
                var client = await page.Target.CreateCDPSessionAsync();
                await client.SendAsync("Emulation.setDefaultBackgroundColorOverride", new EmulationSetDefaultBackgroundColorOverrideRequest
                {
                    Color = new EmulationSetDefaultBackgroundColorOverrideColor
                    {
                        R = 0,
                        G = 0,
                        B = 0,
                        A = 0
                    }
                }).ConfigureAwait(false);
                await page.GoToAsync(url, 600000);
                await page.PdfAsync(FileName, new PdfOptions { PrintBackground = true, MarginOptions = { Bottom = "30mm", Left = "18mm", Top = "30", Right = "10mm" }, Format = PaperFormat.A4 });
```
If defaulting the PDF background to transparent is not possible then would it be possible to add a boolean to PDFOptions to allow it to be set.

There is an outstanding pull request for puppeteer for this: 
[(https://github.com/namespace-ee/puppeteer-pdf/pull/10/commits/e8efdced1d9accaf0e94fb101321c1321c9794fa)]

**Comment by kblok** [comment]
Do you have a link to the PR on the Puppeteer repo? I would wait for this feature to be implemented there first.

**Comment by ianewby** [comment]
[https://github.com/namespace-ee/puppeteer-pdf/pull/10/commits/e8efdced1d9accaf0e94fb101321c1321c9794fa](https://github.com/namespace-ee/puppeteer-pdf/pull/10/commits/e8efdced1d9accaf0e94fb101321c1321c9794fa)

I am in the process of implementing it on my own fork.

**Comment by kblok** [comment]
@ianewby I reviewed your code and your attempt should work. The problem `setDefaultBackgroundColorOverride` has is that it won't change all the `background-color: white" on the page. so if your `<body>` has a white backcolor, you won't get a transparent background.

**Comment by ianewby** [comment]
@kblok  I hit a bit of a roadblock on it - my changes work if no headers and footers are used - but as soon as headers and footers are included I can't get it to work, it immediately gets a full sized white background again. Not been able to get this to work at present.

**Comment by kblok** [comment]
@ianewby  Puppeteer in node has the same issue right?

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
