### ISSUE TITLE
Why is the lat/lng's type 'Int32' instead of 'Decimal' in 'GeolocationOption'?

### ISSUE THREAD

**Issue by LeaFrock** [kblok/puppeteer-sharp#1154]
I've seen one of the branch which its type is 'decimal', [https://github.com/kblok/puppeteer-sharp/blob/017e91e2a84526d8f36d84221b8727f0e8f984d4/lib/PuppeteerSharp/GeolocationOption.cs](url). 
'Int32' is much more general and inaccurant while the **particular** geolocation is required at some situations. Or is there any way else to change the geolocation of browser? Thanks in advance.

**Comment by kblok** [comment]
@LeaFrock agreed, that's wrong.

**Comment by LeaFrock** [comment]
> @LeaFrock agreed, that's wrong.

Wow, so efficient! Hope it'll be fixed in the next version.
Thanks a lot and I'll keep focusing on this project.

**Comment by kblok** [comment]
@LeaFrock :)
I think there is no planned released till the end of June. If this is a roadblock for your project please let me know we can release a hot fix.

**Comment by LeaFrock** [comment]
@kblok  Sorry to hear that but never mind. I'm trying another way to bypass this problem temporarily (maybe EvaluateExpressionAsync and Javascript could be useful).
