### ISSUE TITLE
Getting compile error in PuppetterSharp.AspNetFramework sample in BrowserClient.cs file

### ISSUE THREAD

**Issue by hrchokshi** [kblok/puppeteer-sharp#1158]
I am getting compile error while compiling PuppetterSharp.AspNetFramework sample in file BrowserClient.cs file

using (var browser = await Puppeteer.LaunchAsync(new LaunchOptions()
            {
                Headless = true,
                **Transport = new AspNetWebSocketTransport(),**
                ExecutablePath = browserFetcher.GetExecutablePath(BrowserFetcher.DefaultRevision)
            }).ConfigureAwait(false))

In above code, while assign value to transport option, it is using class as "new AspNetWebSocketTransport()", but there is no parameter less constructor. Can you please check this?

### Versions

I am using 1.17 version of Puppeteer on .NET framework 4.6.1 with Windows 7. I am not sure whether this will work on Windows 7. If not, then do we have any alternate solution for this?

**Comment by hrchokshi** [comment]
This issue is from version 1.12.1

**Comment by kblok** [comment]
@hrchokshi You should use
`TransportFactory = AspNetWebSocketTransport.AspNetTransportFactory`

I updated the demo project

**Comment by hrchokshi** [comment]
Thanks.. Will check it.
