### ISSUE TITLE
implement a SimpleServer like puppeteer

### ISSUE THREAD

**Issue by Meir017** [kblok/puppeteer-sharp#116]
by creating a server like https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/test/server/SimpleServer.js we would be able to add routes/auths and more things more easily.

it will remove all of the test-specific routes

this depends on #101

**Comment by Meir017** [comment]
It will stop us from adding more test specific logic to the server
- [`server.setRoute('/fetch-request-a.js', (req, res) =>`](https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/test/test.js#L1106)
- [`server.waitForRequest('/fetch-request-a.js')`](https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/test/test.js#L1111)

once this is done these tests will be extremely simple

**Comment by Meir017** [comment]
This is basically what I hand in mind:
```cs
public class SimpleServer
{
    public IWebHost WebHost { get; }
    private readonly ConcurrentDictionary<string, RequestDelegate> _routes = new ConcurrentDictionary<string, RequestDelegate>();
    private readonly ConcurrentDictionary<string, (string username, string password)> _auths = new ConcurrentDictionary<string, (string username, string password)>();
    
    public SimpleServer()
    {
        WebHost = new WebHostBuilder()
            .Configure(app => app.Use(async (context, next) =>
            {
                var pathName = context.Request.Path;
                if (_routes.TryGetValue(pathName, out var handler))
                {
                    await handler(context);
                }
                await next();
            }))
            .Build();
    }
    
    public void SetAuth(string path, string username, string password) => _auths.TryAdd(path, (username, password));
    public void SetRoute(string path, RequestDelegate handler) => _routes.TryAdd(path, handler);
}
```

and the `PuppeteerBaseTest` will expose a property `public SimpleServer Server { get; }`

**Comment by kblok** [comment]
Looks quite a cool challenge :)
IMHO what we can easily solve using native controllers in ASP.NET I would go that way. They can't do that in Puppeteer because more than a Simple server is a dumb server :p 

My main concern now is the `waitForRequest` functionality.

Not strong with this, if you want to have fun with this have fun, I'm thinking more about the effort you'd make in some features which are not urgent to us.
