### ISSUE TITLE
ERR_SOCKS_CONNECTION_FAILED

### ISSUE THREAD

**Issue by karuzzo** [kblok/puppeteer-sharp#1160]
**.NET Framework 4.7.2
puppeteer-sharp 1.17.1**

When I try to open the page, I get an authorization error on socks5 proxy

```
string[] arg = new string[] { $"--proxy-server=\"socks5://127.0.0.1:9050\" --no-first-run --ignore-certificate-errors --window-size=\"1450,850\" --user-data-dir=" + Environment.CurrentDirectory + $"\\users_data\\{login}\\" };
                    var browser = await Puppeteer.LaunchAsync(new LaunchOptions
                    {
                        Headless = false,
                        ExecutablePath = browserFetcher.GetExecutablePath(BrowserFetcher.DefaultRevision),
                        Args = arg,
                    });
                    Page page = await browser.NewPageAsync();
                    await page.AuthenticateAsync(new Credentials
                        {
                            Username = "123",
                            Password = "123"
                        });
                     await page.GoToAsync("https://whoer.net/ru");
```

At the same time, the proxy log looks like **socks5: offered methods don't include 'no auth'. Rejecting.**

if you connect to a proxy without authorization, the page loads successfully.
This error occurred on all tested proxies socks5, including the ones I raised.

**Comment by karuzzo** [comment]
If anyone finds this error before they deal with it, know that there is an intermediate solution.
NuGet **SocksRelayServer**
`var localEndpoint = new IPEndPoint(IPAddress.Parse("127.0.0.1"), GetNextFreePort());
            var remoteEndpoint = new IPEndPoint(IPAddress.Parse("127.0.0.1"), 9050);
            ISocksRelayServer relay = new SocksRelayServer.SocksRelayServer(localEndpoint, remoteEndpoint)
            {
                Username = "123",
                Password = "123",
            };
            //relay.ResolveHostnamesRemotely = false;

            relay.Start();

            int GetNextFreePort()
            {
                var listener = new System.Net.Sockets.TcpListener(IPAddress.Loopback, 0);
                listener.Start();
                var port = ((IPEndPoint)listener.LocalEndpoint).Port;
                listener.Stop();
                localport = port;
                return port;
            }`

**Comment by StegBrind** [comment]
This is not a PuppeteerSharp related issue. Here is a solution from original Puppeteer repository: https://github.com/puppeteer/puppeteer/issues/2472#issuecomment-390891948

Just replace your "--proxy-server=socks5://127.0.0.1:9050" with "--proxy-server=socks5=127.0.0.1:9050"
