### ISSUE TITLE
Strategies for faster Screenshot generation.

### ISSUE THREAD

**Issue by rgelb** [kblok/puppeteer-sharp#1161]
### Description

I have a web page that when called, it takes a screenshot on the backend, then returns the image.
So to make it faster, I have a pre-allocated [factory like cache](https://github.com/rgelb/PuppetScreenshot/blob/master/PuppetFactory.cs) of 20 Page objects that I rent to a web request, which sets Viewport to a specific width, goes to a URL, waits for a Selector to appear, then takes a screenshot (specific example [here](https://github.com/rgelb/PuppetScreenshot/blob/master/PuppeteerHelperAsync.cs)) .  Sequence of events and average timings with 3-4 concurrent connections:

page.SetViewportAsync (2 ms)
page.GoToAsync (100 ms)
page.WaitForSelectorAsync (76 ms)
page.ScreenshotDataAsync (750 ms)

So it works reasonably well.  However when I up the number of simultaneous requests to 20, the performance of page.ScreenshotDataAsync (and only that method) goes up to an average of 4500 ms.

I am currently on PuppeteerSharp v1.14 and Chromium 72.0.3617.0.

So my questions.  

1. Is there a reason why the performance of ScreenshotDataAsync nosedives like that with more simultaneous requests?

2. Is the strategy of pre-allocating Page objects valid?  Would it be better to pre-allocate multiple browser objects with fewer pages instead?

3. I noticed that there have been several releases since v1.14.  Do the changes in those in any way address the perf issues I am running into?  (btw, I will test this hopefully soon, it just takes time to set it up on web cluster).

**Comment by kblok** [comment]
Here @rgelb. There is a queue for screenshots behind the scenes. Each browser can take only one screenshot at a time.

**Comment by kblok** [comment]
You could have multiple browsers running in parallel.

**Comment by rgelb** [comment]
Thanks for the tip.  One more thing I found out.  Decreasing amount of Pages on a browser object also seems to speeds up ScreenshotDataAsync method, even if you are not doing screenshots in other tabs.

So the current setup is 10 browser objects, 2 Page objects on each.  And round-robin through them as requests come in.
