### ISSUE TITLE
The "await Puppeteer.LaunchAsync(launchOptions)" this method cannot open Chromium in Windows7 environment.

### ISSUE THREAD

**Issue by A-Grass-Code** [kblok/puppeteer-sharp#1162]
I made a test program in 64-bit Windows10 environment, using the ". Net Framework 4.7" runtime, the program ran perfectly, successfully started Chromium, and performed subsequent operations; However, the same code, in the 64-bit Windows7 environment, also uses the ".NET Framework 4.7" runtime, and when the program executes to the "await Puppeteer.LaunchAsync(launchOptions)" method, it fails to start the Chromium, program as if it were stuck in the background, waiting and unable to continue execution.

**Comment by kblok** [comment]
Hey @A-Grass-Code. We have some [prerequisites in our home page](https://github.com/kblok/puppeteer-sharp#prerequisites). Windows 7 doesn't have the libraries we need to run.

You can try installing [System.Net.WebSockets.Client.Managed](https://www.nuget.org/packages/System.Net.WebSockets.Client.Managed/). And adding this piece of code:

```cs
var browserOptions = new LaunchOptions
{
    WebSocketFactory = async (uri, socketOptions, cancellationToken) =>
    {
        var client = SystemClientWebSocket.CreateClientWebSocket();
        if (client is System.Net.WebSockets.Managed.ClientWebSocket managed)
        {
            managed.Options.KeepAliveInterval = TimeSpan.FromSeconds(0);
            await managed.ConnectAsync(uri, cancellationToken);
        }
        else
        {
            var coreSocket = client as ClientWebSocket;
            coreSocket.Options.KeepAliveInterval = TimeSpan.FromSeconds(0);
            await coreSocket.ConnectAsync(uri, cancellationToken);
        }

        return client;
    }
};
```

**Comment by A-Grass-Code** [comment]
Thank you very much. This problem has been solved. The program works perfectly.
