### ISSUE TITLE
Passing large amounts of data during EvaluateFunctionAsync

### ISSUE THREAD

**Issue by digi-chris** [kblok/puppeteer-sharp#1163]
I'm using PDF.JS within PuppeteerSharp to analyze and render PDFs. This is working really well, but I'm running into an issue when the PDFs reach a certain size.

In order to load the PDF into PDF.JS via PuppeteerSharp, I'm opening the PDF in C#, reading the bytes into a buffer and then converting that buffer to Base64. I can then use `EvaluateFunctionAsync` to call a function (which opens the PDF), passing the Base64 string as an argument.

What I'm finding is that if I reach a certain size restriction, the `EvaluateFunctionAsync` call will fail with the following error:

```
PuppeteerSharp.EvaluationFailedException: 'The 'System.Net.WebSockets.InternalClientWebSocket' instance cannot be used for communication because it has been transitioned into the 'Aborted' state.'
```

The PDF file I'm trying to load is 80mb in size. Looking at the error message, I'm assuming that this data is being sent via a WebSocket to Chrome, and that the WebSocket aborts before all the data is sent.

Is there any advice relating to how much data we can send in a function call, or any hard limits that are set anywhere?

**Comment by kblok** [comment]
Hey @digi-chris 
I downloaded [this file](https://norvig.com/big.txt), and I duplicated it, getting a 13MB file.
This piece of code worked for me.

```cs
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);

LaunchOptions options = new LaunchOptions
{
    Headless = false
};
using (Browser browser = await Puppeteer.LaunchAsync(options))
using (Page page = await browser.NewPageAsync())
{
    await page.EvaluateFunctionAsync(
        "t => document.querySelector('BODY').innerText = t",
        File.ReadAllText("/Users/neo/Downloads/big.txt"));
    await page.EvaluateFunctionAsync(
        "t => document.querySelector('BODY').innerText = t",
        "");
    await page.EvaluateFunctionAsync(
        "t => document.querySelector('BODY').innerText = t",
        File.ReadAllText("/Users/neo/Downloads/big.txt"));
    Console.WriteLine("Done!");
    Console.ReadLine();
}
```
 
![image](https://user-images.githubusercontent.com/2198466/59506445-a19daf00-8e7e-11e9-9050-522b4224b0a7.png)


Then I moved to a 10mb zip, converted to a base64 text. Although it was able to console.log, that content innerText was not working.

![image](https://user-images.githubusercontent.com/2198466/59507475-84b6ab00-8e81-11e9-92b2-353bca21cc1a.png)

When the WebSocket crashes, it doesn't necessarily mean that a message killed the connection. It could also mean that the session crashed.
Maybe the javascript side of that is having a hard time processing that content?

**Comment by digi-chris** [comment]
Thanks for the quick reply @kblok :)

I've tried loading the file into PDF.JS outside of Puppeteer, and it does process correctly. If I run PuppeteerSharp with `headless = false` so I can see Chrome, what I'm seeing is that the load never initiates on the browser side, so it seems like the function never gets called.

I'll do some more tests here with various size files. I think my previous tests also showed files around the 10mb mark did work, it was only when I tried a much bigger 80mb file that I ran into trouble.

**Comment by kblok** [comment]
Ah sorry I read `8MB` instead of `80`. Yeah that's quite a lot :p

**Comment by digi-chris** [comment]
Is there any way of knowing what sort of data length will work?

I'm thinking I can break this up into chunks, but I'd need to have some sort of indication as to what the maximum is, and if it's likely to vary from system to system.

I suppose alternatively, I could always break it up into known manageable chunks - like 1mb per chunk.

**Comment by kblok** [comment]
@digi-chris one thing that performs really good is sending the file to chromium using a File input. That file input could be already on your page or you can inject it using javascript.

```cs
await page.SetContentAsync("<input type='file' ID='file' style='display: none;'>");
var input = await page.QuerySelectorAsync("input");
await input.UploadFileAsync("path-to-my-big-file");
await page.EvaluateFunctionAsync(@"() => {
    var reader = new FileReader();
    reader.onload = function(){
        var result = reader.result;
        console.log(result);
    };
    reader.onerror = function(e){
        console.log(e);
    };
    reader.readAsArrayBuffer(document.querySelector('#file').files[0]);
}");
```

**Comment by digi-chris** [comment]
@kblok thanks for that - stupidly, it didn't occur to me to try sending it that way!

I have got it working by sending the data in chunks, but it is slow. Sending 1mb at a time isn't too bad, but I suspect it'll be a lot faster if I can send the file in one pass.

I'll try it out.

Thanks!
