### ISSUE TITLE
Running BrowserFetcher().DownloadAsync on Raspberry Pi downloads x64 version instead of ARM

### ISSUE THREAD

**Issue by rgelb** [kblok/puppeteer-sharp#1181]
### Description

Running BrowserFetcher().DownloadAsync on Raspberry Pi downloads x64 version instead of ARM.

### Complete minimal example reproducing the issue
```csharp
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
```

### Expected behavior:

Compatible ARM build downloads.

### Actual behavior:

X64 Linux build downloads.

### Versions

* PuppetSharp 1.17.2
* .NET Core 2.2

### Additional Information

The workaround is to `sudo apt-get install chromium-browser` and then 

```csharp
var options = new LaunchOptions() {
            ExecutablePath = "/usr/bin/chromium-browser",
            Headless = true
};
var browser = await Puppeteer.LaunchAsync(options);
```

**Comment by kblok** [comment]
There are some recipes here https://github.com/GoogleChrome/puppeteer/issues/550
Puppeteer is not downloading a chrome version for ARM.

**Comment by aengl** [comment]
Is that an unwanted feature?

I had a look at https://github.com/GoogleChrome/puppeteer/blob/master/lib/BrowserFetcher.js which could easily be expanded to handle ARM. The only question is whether there is an ARM binary on https://storage.googleapis.com/chromium-browser-snapshots/index.html, which is a bit of a mess to navigate.

If there's interest I can look into creating a PR.

**Comment by kblok** [comment]
@aengl yeah you could create an issue there. The main question is if they are building ARM binaries for every revision.
