### ISSUE TITLE
A about "await page. EvaluateOnNewDocumentAsync (overrideNavigatorLanguages);"API documentation error.

### ISSUE THREAD

**Issue by A-Grass-Code** [kblok/puppeteer-sharp#1183]
Examples of the current API documentation are as follows:
```c#
var overrideNavigatorLanguages = @"Object.defineProperty(navigator, 'languages', {
	get: function() {
 		return ['en-US', 'en', 'bn'];
 	};
});";
await page.EvaluateOnNewDocumentAsync(overrideNavigatorLanguages);
```
But the above example code doesn't work!
After my trial and error, I found that the following code is very effective:
```c#
string navigatorlanguages = @"
() => {
	Object.defineProperty(navigator, 'languages', {
 		get: () => ['zh-CN', 'en-US', 'en'],
 	});
}";
await page.EvaluateOnNewDocumentAsync(navigatorlanguages);
```
I hope you can make improvements to the API documentation after you confirm.Thank you very much!

**Comment by A-Grass-Code** [comment]
Supplementary notes:
Link to the API documentation above http://www.puppeteersharp.com/api/PuppeteerSharp.Page.html

**Comment by kblok** [comment]
That code should work. We should fix that.

**Comment by A-Grass-Code** [comment]
Thank you very much. Hope it gets better and better!

**Comment by kblok** [comment]
Reopening. We'll have a PR attached to this.

**Comment by A-Grass-Code** [comment]
Sorry, I did it wrong.But thank you and hope it gets better and better.
