### ISSUE TITLE
jpeg/png that comes as base64string are not being rendered

### ISSUE THREAD

**Issue by yumahayomaso** [kblok/puppeteer-sharp#1194]
Hi

I'm trying to convert the HTML string to pdf file. My HTML contains the CSS and the image base 64 string imported like
`url('data:image/png;base64,BASE_64_STRING_HERE')`
After the conversion, the image doesn't appear.
I've tried for jpeg and png base64 string both of them do not work.
Maybe I'm missing something?

**Comment by kblok** [comment]
@yumahayomaso  Can you share an example so I can test?

**Comment by yumahayomaso** [comment]
Here is the html example
`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style type="text/css">
        .signiture-image {
            width: 130px;
            height: 57px;
            display: inline-block;
            background: no-repeat center center;
            background-size: cover;
            background-image: url('data:image/png;base64,PUT_HERE_ANY_PNG_CONVERTED_TO_BASE64_STRING');
        }
     </style>
</head>
<body>
        Here should be an image
        <div class="signiture-image"> </div>
</body>
</html>`

And c# code
`public async Task ConvertHtmlToPdf(string htmlString)
        {
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
            });

            using (var page = await browser.NewPageAsync())
            {
                await page.SetContentAsync(htmlString);
                await page.PdfAsync("Result.pdf",
                    new PdfOptions
                    {
                        MarginOptions = new MarginOptions
                        {
                            Bottom = "50",
                            Left = "50",
                            Right = "50",
                            Top = "80"
                        },
                    });
            }
        }`

**Comment by yumahayomaso** [comment]
Here is the html example
```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style type="text/css">
        .signiture-image {
            width: 130px;
            height: 57px;
            display: inline-block;
            background: no-repeat center center;
            background-size: cover;
            background-image: url('data:image/png;base64,PUT_HERE_ANY_PNG_CONVERTED_TO_BASE64_STRING');
        }
     </style>
</head>
<body>
        Here should be an image
        <div class="signiture-image"> </div>
</body>
</html>
```
And c# code

```
public async Task ConvertHtmlToPdf(string htmlString)
        {
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
            });

            using (var page = await browser.NewPageAsync())
            {
                await page.SetContentAsync(htmlString);
                await page.PdfAsync("Result.pdf",
                    new PdfOptions
                    {
                        MarginOptions = new MarginOptions
                        {
                            Bottom = "50",
                            Left = "50",
                            Right = "50",
                            Top = "80"
                        },
                    });
            }
        }
```

**Comment by kblok** [comment]
The same happens on a headfull Chrome when you try to print this HTML to PDF. You should report this to Chromium.
![image](https://user-images.githubusercontent.com/2198466/60587218-474f8a00-9d6a-11e9-923c-39cbd0a1745c.png)
