### ISSUE TITLE
background image as watermark

### ISSUE THREAD

**Issue by llocani** [kblok/puppeteer-sharp#1200]
Hello, i´m trying to add a background image in every page. 
For example, using itextsharp i'm adding a handler in the end_page event
pdfDoc.AddEventHandler(PdfDocumentEvent.END_PAGE, handler);
and then 
PdfDocumentEvent docEvent = (PdfDocumentEvent)@event;
            PdfDocument pdfDoc = docEvent.GetDocument();
            PdfPage page = docEvent.GetPage();
            PdfCanvas canvas = new PdfCanvas(page.NewContentStreamBefore(),
                    page.GetResources(), pdfDoc);
            Rectangle area = page.GetPageSize();
            new Canvas(canvas, pdfDoc, area)
                    .Add(_img);

Is there any way to do this wih puppeteer-sharp?
Thank you in advance

**Comment by kblok** [comment]
If you can host that image in some server, then you can set a `background-image` in the body element.

**Comment by llocani** [comment]
I tried that but the background is only printing in the first page.

**Comment by kblok** [comment]
@llocani Puppeteer will behave in the same way Chrome behaves when you print to PDF. Maybe this will help https://stackoverflow.com/questions/49970317/repeating-a-watermark-on-every-print-page-javascript-or-css ?

**Comment by llocani** [comment]
it worked like a charm!
Thanks!
