### ISSUE TITLE
Proxy ERR_TUNNEL_CONNECTION_FAILED  

### ISSUE THREAD

**Issue by Yom92** [kblok/puppeteer-sharp#1202]
Hi,

I work with VS 2017 and library PuppeteerSharp v 1.17.2

When I try to open the page with proxy anonymus, I get an error PuppeteerSharp.NavigationException : 'net::ERR_TUNNEL_CONNECTION_FAILED at https://www.whatsmyipaddress.net/ at https://

Here my code : 
`                var ipPort = "88.198.24.108:8080";

                var options = new LaunchOptions {
                    Headless = false,
                    Devtools = false,
                    IgnoreHTTPSErrors = true,
                    Args = new[] {
                                    "--no-sandbox",
                                    "--disable-infobars",
                                    "--disable-setuid-sandbox",
                                    "--ignore-certificate-errors",
                                    "--proxy-server="+ipPort,
                                     "--disable-dev-shm-usage",
                                     "--disable-accelerated-2d-canvas",
                                     "--disable-gpu",
                                     "--window-size=1920x1080",
                                }
                };
                await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
                Console.WriteLine("Downloading Chromium");

                using (var browser = await Puppeteer.LaunchAsync(options))
                using (var page = await browser.NewPageAsync())
                {

                    await page.GoToAsync("https://www.whatsmyipaddress.net/");`

Thx for your help :)

**Comment by kblok** [comment]
Hey @Yom92 That error is coming straight from Chromium. There is not much we can do on our side.

**Comment by Yom92** [comment]
Thanks @kblok for your return. 
Can I use chrome or firefox instead of chromium?

'await puppeteer.launch ({headless: false, executablePath: '/ Applications / Chrome'});'

**Comment by kblok** [comment]
@Yom92 Firefox not yet :)
Regarding Chrome, as long as you follow the version matching [here]( https://github.com/GoogleChrome/puppeteer/blob/v1.18.1/docs/api.md), you can do it.

For instance, now I'm using Chrome 75. So that means I should use Puppeteer-Sharp v1.15.
