### ISSUE TITLE
Improve Platform

### ISSUE THREAD

**Issue by djslife** [kblok/puppeteer-sharp#1207]
Explain how would you like this document to be impoved.
Source URL: https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/BrowserFetcherOptions.cs/#L11

Fix misspelling of 'currenct' to 'current' in description for property BrowserFetcherOptions.Platform.

**Comment by kblok** [comment]
Thanks for the report @djslife!
