### ISSUE TITLE
Puppeteer not Launching in headless false mode on server IIS

### ISSUE THREAD

**Issue by kulesshhh** [kblok/puppeteer-sharp#1242]
Hello @kblok ,
I am facing an issue where puppeteer is launching in headless mode only, even when i have specified **"Headless = false"**.

Can you help me with this.

Thanks

**Comment by kblok** [comment]
Are you getting any error?

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
