### ISSUE TITLE
Black tall screenshot for a certain URL

### ISSUE THREAD

**Issue by d668** [kblok/puppeteer-sharp#1246]
repo to reproduce https://github.com/d668/puppeteer-sharp-test

black tall screen: 
![PDAszs2ogGBRgkkfW8MQ](https://user-images.githubusercontent.com/2155554/62856020-79fa8400-bd13-11e9-92e4-4f0c6d224906.jpg)

**Comment by kblok** [comment]
I'm getting a new image with your code
![jpeg](https://user-images.githubusercontent.com/2198466/62938058-9c88ad80-bda4-11e9-8d0e-ebef9826eb0d.jpg)

**Comment by d668** [comment]
i guess it depends on environment.
I will close it, anyway I decided to limit it with viewport height to avoid too long screenshots and it works fine
