### ISSUE TITLE
Unable to open http://css.suzhouterminals.com/xianghuoxinxi.jsp

### ISSUE THREAD

**Issue by jifeilong9** [kblok/puppeteer-sharp#1249]
![image](https://user-images.githubusercontent.com/24316291/63333275-bd846c00-c36b-11e9-8736-d6829371744a.png)
Unable to open http://css.suzhouterminals.com/xianghuoxinxi.jsp

![image](https://user-images.githubusercontent.com/24316291/63333544-35eb2d00-c36c-11e9-9fd2-046d989cd530.png)
Open with Chromium Browser

Code
![image](https://user-images.githubusercontent.com/24316291/63333201-9a59bc80-c36b-11e9-8d38-31362466442e.png)

**Comment by kblok** [comment]
It seems that site is detecting that you are using puppeteer. There are many posts talking about that on the internet. 
In my opinion (and that's the spirit of this project), if a site doesn't want to be scraped you shouldn't scrape it.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
