### ISSUE TITLE
Puppeteer-sharp throws an exception when opening a url pointing to a PDF

### ISSUE THREAD

**Issue by darrynhoskingluna** [kblok/puppeteer-sharp#1250]
# Description
Puppeteer-sharp throws an exception (ERR_ABORTED) on GoToAsync when the URL resolves to a PDF

### Complete minimal example reproducing the issue
```csharp
// Arrange
var options = new LaunchOptions { Headless = true };
var chromiumRevision = BrowserFetcher.DefaultRevision;
var browser = await Puppeteer.LaunchAsync(options, chromiumRevision);
var page = browser.NewPageAsync();

// Act
await page.GoToAsync("https://ayotsl.com/wp-content/uploads/2018/06/Code-of-Conduct-2018.pdf");

// Assert
That no exception is thrown
ScreenshotOptions options = new ScreenshotOptions { FullPage = true };
var stream = await page.ScreenshotStreamAsync(options);
Assert stream is not null
```

### Expected behavior:

No Exception

### Actual behavior:

Exception thrown 
`One or more errors occurred. (net::ERR_ABORTED at https://ayotsl.com/wp-content/uploads/2018/06/Code-of-Conduct-2018.pdf at https://ayotsl.com/wp-content/uploads/2018/06/Code-of-Conduct-2018.pdf)`

### Versions

Latest Stable 1.19.0
 .NET Core 2.2

**Comment by kblok** [comment]
The PDF Viewer you see in Chrome it's not a Page you can act on. It's a plugin.
