### ISSUE TITLE
EvaluateExpressionAsync failed to return new Date

### ISSUE THREAD

**Issue by Gdocal** [kblok/puppeteer-sharp#1251]
I want to receive date object from JS, but this  doesn't work

```csharp
var d= await Page.EvaluateExpressionAsync<DateTime>("new Date()");
```

### Expected behavior:

no exception

### Actual behavior:

Exception thrown
> Newtonsoft.Json.JsonReaderException
>   HResult=0x80131500
>   Message=Error reading date. Unexpected token: StartObject. Path ''.
>   Source=Newtonsoft.Json
>   StackTrace:
>    at Newtonsoft.Json.JsonReader.ReadAsDateTime()
>    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
>    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
>    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
>    at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
>    at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
>    at PuppeteerSharp.Helpers.Json.JTokenExtensions.ToObject[T](JToken token, Boolean camelCase)
>    at PuppeteerSharp.Helpers.RemoteObjectHelper.ValueFromType[T](JToken value, RemoteObjectType objectType)
>    at PuppeteerSharp.Helpers.RemoteObjectHelper.ValueFromRemoteObject[T](RemoteObject remoteObject)
>    at PuppeteerSharp.ExecutionContext.<RemoteObjectTaskToObject>d__18`1.MoveNext()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at PuppeteerSharp.DOMWorld.<EvaluateExpressionAsync>d__17`1.MoveNext()
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

### Versions
PuppeteerSharp 1.18.0

Net framework 4.7.2

**Comment by kblok** [comment]
Chromium won't return a `Date`. https://github.com/GoogleChrome/puppeteer/pull/1098/files

You can serialize the date on the browser side and then parse it locally.

```cs
var token = await Page.EvaluateExpressionAsync<string>("JSON.stringify(new Date())");
var date = JsonConvert.DeserializeObject<DateTime>(token, new IsoDateTimeConverter());
Assert.Equal(DateTime.Today, date.Date);
```
