### ISSUE TITLE
Task<byte[]> method using puppeteer-sharp not always ready on time 

### ISSUE THREAD

**Issue by cap7ainjack** [kblok/puppeteer-sharp#1253]
### Description

[Link to stackoverflow question](https://stackoverflow.com/questions/57788298/web-api-controller-returning-task-not-always-waits-for-task-completion-puppetee)

Method which I return Task<byte[]> with puppeteer-sharp does not always returns the full data. Actually it returns the full data only in debug or first time when i make request to the API. In the other cases i get PDF with only some of the data i expect.

I first tought I may have missed something in the API controller implementation, but now it seems like problem could be in the puppeteer library instead.

### Versions

* Which version of PuppeteerSharp are you using?
1.11.2

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
.NET framework 4.7.2

**Comment by kblok** [comment]
Do you have something for me to test?
An isolated piece of code would be useful.

**Comment by cap7ainjack** [comment]
Is there a prbolem with the code sample in Stackoverflow? That is the exact recreation of the problem, without the real HTML content

**Comment by kblok** [comment]
@cap7ainjack are you getting that issue with any content you pass to `GetAsync`?
If I send, just "hello world", it will break?

**Comment by cap7ainjack** [comment]
I have not tried with "Hello world" kind of html. I load a couple of css`s and a bit more complex but not enourmous HTML. Do you want to send you the HTML content (without css) or the two output pdf files where can be seen the difference?

**Comment by cap7ainjack** [comment]
Hello! Any new on the topic? Do you need something additional?

**Comment by kblok** [comment]
@cap7ainjack when you say "it returns some partial result." It's a valid PDF with missing content or a broken byte array?

**Comment by cap7ainjack** [comment]
It's a valid PDF with missing content.

**Comment by kblok** [comment]
If you get a valid PDF file there is no "missing PDF data".
Did you try waiting a little bit more before generating the PDF?

**Comment by cap7ainjack** [comment]
Yes, when I`m doing this in Debug mode it works fine. Otherwise not, in the most cases.

**Comment by kblok** [comment]
Can't you wait for a CSS selector to be ready?

**Comment by cap7ainjack** [comment]
`           
 using (var page = await browser.NewPageAsync().ConfigureAwait(false))
            {
                await page.SetCacheEnabledAsync(false).ConfigureAwait(false);

                await page.SetContentAsync(html).ConfigureAwait(false);
                await page.AddStyleTagAsync("https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700").ConfigureAwait(false);
                await page.AddStyleTagAsync("http://localhost:55448//client-cli/output/css/bootstrap.min.css").ConfigureAwait(false);
                await page.AddStyleTagAsync("https://cdnjs.cloudflare.com/ajax/libs/MaterialDesign-Webfont/3.4.93/css/materialdesignicons.css").ConfigureAwait(false);
                await page.AddStyleTagAsync("http://localhost:55448//client-cli/output/css/kendo.css").ConfigureAwait(false);
                await page.AddStyleTagAsync("http://localhost:55448/client-cli/output/css/themes/default/styles.css").ConfigureAwait(false);
                await page.AddStyleTagAsync("http://localhost:55448/client-cli/output/css/styles-pdf.css").ConfigureAwait(false);

                var result = await page.GetContentAsync().ConfigureAwait(false);

                PdfOptions pdfOptions = new PdfOptions()
                {
                    PrintBackground = true,
                    MarginOptions = new PuppeteerSharp.Media.MarginOptions { Right = "15mm", Left = "15mm", Top = "20mm", Bottom = "20mm" },
                };

                await page.EmulateMediaAsync(PuppeteerSharp.Media.MediaType.Screen);
                streamResult = await page.PdfDataAsync(pdfOptions).ConfigureAwait(false);

                await page.CloseAsync().ConfigureAwait(false);
            }`
This is example how i add the css, there is a few more CSS that i load in the same manner. I think this is how I should wait for them. Am I doing it wrong somehow?

**Comment by cap7ainjack** [comment]
Hello! Do you find some mistakes with the implementation?

**Comment by kblok** [comment]
You could add an element at the bottom of the page and then use `WaitForSelector` to wait for that element. There is no rule of thumb to know when the page is loaded. You need to evaluate the page and see what you should check to know when your page is ready to evaluate.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
