### ISSUE TITLE
Improve SetRequestInterceptionAsync(Boolean)

### ISSUE THREAD

**Issue by ChinaPhusun** [kblok/puppeteer-sharp#1255]
Explain how would you like this document to be impoved.
Source URL: https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Page.cs/#L485

When I Activating request interception enables, The browser is can not to open http://www.google.com
![1568101771(1)](https://user-images.githubusercontent.com/38497378/64594487-b12b8600-d3e2-11e9-9de1-8d019e7dfc32.jpg)
![1568102191(1)](https://user-images.githubusercontent.com/38497378/64595019-b210e780-d3e3-11e9-9d67-2a8f2abde828.jpg)

**Comment by kblok** [comment]
If you enable `SetRequestInterceptionAsync` you have to attach to the `Request` event so you can tell puppeteer to "continue".

If you enable request interception, it's because you can to use the Request event.

```cs
Page.Request += async (sender, e) => await e.Request.ContinueAsync();
```

**Comment by ChinaPhusun** [comment]
Is OK , Thank you very much!
