### ISSUE TITLE
Syncing viewport from server

### ISSUE THREAD

**Issue by chitoiur** [kblok/puppeteer-sharp#1288]
This is not a bug, more of a question. I have the following code:

```
var connectOptions = new ConnectOptions()
{
      BrowserWSEndpoint = "ws://..."
};

var browser = await Puppeteer.ConnectAsync(connectOptions);

var pages = await browser.PagesAsync();

foreach (var page in pages)
{
       JObject response = await page.Client.SendAsync("Performance.getMetrics");
       Console.WriteLine("Response is " + response.ToString());
}
```

To my surprise, as soon as the command ran, it resized the viewport to the default (800,600). My expectation would be that if a viewport was already set on the server, it shouldn't modify it. If there is already a viewport set on the server, the PuppeteerSharp state should be synchronized to match it. Thoughts?

**Comment by kblok** [comment]
You could try setting the `DefaultViewport` to `null` in the `ConnectOptions`.

**Comment by chitoiur** [comment]
I completely forgot to mention that this is what I did and it did work, but the problem becomes that if I try to do page.Viewport, it is null. Is there a way to "sync" that so it fetches the server value?

**Comment by kblok** [comment]
@chitoiur you could try to get that using a javascript code and calling `EvaluateFunctionAsync`

**Comment by chitoiur** [comment]
Thanks! Closing this out.

**Comment by Mercurial** [comment]
this was helpful to me, thanks! hopefully this becomes better in the future
