### ISSUE TITLE
Get all XHR response.

### ISSUE THREAD

**Issue by haduong825** [kblok/puppeteer-sharp#1294]
###Question 
Hi all, 
In pupperteer for nodejs. I can use method for get all XHR response like
'''
page.on('response', async res => {
    if (res.request().method() === 'POST') {
      var data = await res.json()
      // Do something
    }
  })
'''
And in pupperteer-sharp. I don't know how to write function like above code with pupperteer-sharp.
Anyone show me function like it ???
Thanks

**Comment by StegBrind** [comment]
> ###Question
> Hi all,
> In pupperteer for nodejs. I can use method for get all XHR response like
> '''
> page.on('response', async res => {
> if (res.request().method() === 'POST') {
> var data = await res.json()
> // Do something
> }
> })
> '''
> And in pupperteer-sharp. I don't know how to write function like above code with pupperteer-sharp.
> Anyone show me function like it ???
> Thanks

Page page;
page.SetRequestInterceptionAsync(true);
page.Request += OnPageRequest;

public static async void OnPageRequest(object sender, RequestEventArgs RequestEvent)
        {
            if (RequestEvent.Request.ResourceType == ResourceType.Xhr)
            {
                //Do something
            }
            await RequestEvent.Request.ContinueAsync();
        }

**Comment by haduong825** [comment]
> > ###Question
> > Hi all,
> > In pupperteer for nodejs. I can use method for get all XHR response like
> > '''
> > page.on('response', async res => {
> > if (res.request().method() === 'POST') {
> > var data = await res.json()
> > // Do something
> > }
> > })
> > '''
> > And in pupperteer-sharp. I don't know how to write function like above code with pupperteer-sharp.
> > Anyone show me function like it ???
> > Thanks
> 
> ```
> Page page;
> page.SetRequestInterceptionAsync(true);
> page.Request += OnPageRequest;
> 
> public static async void OnPageRequest(object sender, RequestEventArgs RequestEvent)
>         {
>             if (RequestEvent.Request.ResourceType == ResourceType.Xhr)
>             {
>                 //Do something
>             }
>             await RequestEvent.Request.ContinueAsync();
>         }
> ```

Thank StegBrind, i will try

**Comment by haduong825** [comment]
@StegBrind. It’s seem like for Request. Because when I debug Response is null but when i see in Network of browser it still response. Can you explain for me or give me example code for get response. I’m newbie in C#.

**Comment by StegBrind** [comment]
If you need to intercept Responses you can add Repsonse event.
Pretty much the same:

```
Page page;
page.Response += OnPageResponse;

public static void OnPageResponse(object sender, ResponseCreatedEventArgs ResponseEvent)
        {
            // use ResponseEvent.Response object
        }
```

**Comment by haduong825** [comment]
Thank you for your help. I will try it.
