### ISSUE TITLE
Page.DefaultTimeout not used

### ISSUE THREAD

**Issue by jgilbert2017** [kblok/puppeteer-sharp#1297]
Page.DefaultTime does             set => _timeoutSettings.Timeout = value;

However Page does "new WaitForSelectorOptions()" when methods are called with null options.

new WaitForSelectorOptions() does  public int Timeout { get; set; } = Puppeteer.DefaultTimeout; which is defined as a const

**Comment by kblok** [comment]
Thanks for the report @jgilbert2017 !
