### ISSUE TITLE
WaitTask.Cleanup() exception

### ISSUE THREAD

**Issue by jgilbert2017** [kblok/puppeteer-sharp#1298]
_cts.Cancel() was throwing for me in WaitTask.Cleanup().  I fixed with the following:

        private void Cleanup()
        {
            // avoid exception if _cts is Dispose()d
            if (!_cts.IsCancellationRequested) {
                _cts.Cancel();
            }
            _cts?.Dispose();
            _world.WaitTasks.Remove(this);
        }

**Comment by kblok** [comment]
Awesome! Thanks again!
