### ISSUE TITLE
Add local javascript script to html

### ISSUE THREAD

**Issue by psclkhoury** [kblok/puppeteer-sharp#1309]
Hey, sorry if this is not the right place to ask.

I'm using PuppeteerSharp in an `ASP.NET core` project to generate reports. I basically generate all the html document using `handlebars` and then inject the whole html using `SetContentAsync`. 

I have a local javascript library bundle (`Chartjs.bundle.min`) and I am not able to figure out which path I should use to make chromium see it.

I tried an absolute path, I also tried to put the library file in the same folder as chromium and reference it using `./Chartjs.bundle.js` but it doesn't seem to work.

What is the correct way to handle that.

**Comment by kblok** [comment]
@psclkhoury you will need to register the js using the [file protocol](https://docs.microsoft.com/en-us/previous-versions/aa767731(v%3Dvs.85))

**Comment by psclkhoury** [comment]
Tried that but then got an error:
```
Not allowed to load local resource: file:///Users/Chart.bundle.min.js
(anonymous) @ __puppeteer_evaluation_script__:3
```

**Comment by kblok** [comment]
@psclkhoury I wasn't able to get to this issue yet, did you find a solution?

**Comment by psclkhoury** [comment]
@kblok I didn't find a solution. I ended up just reading the file into a string and adding the string in the `<script>` tag. If you have a better solution I would appreciate it, otherwise this workaround is good enough for now.

**Comment by kblok** [comment]
@psclkhoury after some reading I found that's a security validation in Chrome. You don't a site try to read a file from your file system.

I like your solution, you could also host that file in some server and access it using a normal url.
