### ISSUE TITLE
Is there any way to pass an html string of a raw page to have puppeteer render the full page with all js?

### ISSUE THREAD

**Issue by sjdirect** [kblok/puppeteer-sharp#1322]
I am the author of Abot/AbotX (c# web crawler). I wanted to create another js rendering impl using chrome headless (have a working impl for phantomjs) Currently phantomjs allows me to pass raw html to it and it will do the final rendering (without having to rerequest the page again). This allows me to offer javascript rendering as an additional step in the current crawl process. Can Puppeteer/chromeheadless do the same? Not finding anything in the docs. The worst case looks to be passing the path for a ""file:///""?

Looks like a cool project, thanks for building it out!

**Comment by kblok** [comment]
Hey @sjdirect.

You can inject content using [SetContentAsync](https://www.puppeteersharp.com/api/PuppeteerSharp.Page.html#PuppeteerSharp_Page_SetContentAsync_System_String_PuppeteerSharp_NavigationOptions_). You can take a look at some tests [here](https://github.com/kblok/puppeteer-sharp/blob/74488cf1760b2d4895a4855e9be87cb50ec3c9d8/lib/PuppeteerSharp.Tests/PageTests/SetContentTests.cs).

You can also use [AddScriptTag](https://www.puppeteersharp.com/api/PuppeteerSharp.Page.html#PuppeteerSharp_Page_AddScriptTagAsync_System_String_) to inject javascript to an existing page.

**Comment by ahmadalli** [comment]
@sjdirect how about going to `data:text/html,{html}`? (try it on your browser. e.g. go to `data:text/html,<h1>hello</h1>`

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
