### ISSUE TITLE
How to use dedicated Browserless Docker container instance with PuppeteerSharp?

### ISSUE THREAD

**Issue by tedvanderveen** [kblok/puppeteer-sharp#1325]
I would like to completely isolate all things related to hosting/running Chrome from my core application runtimes. So I'm hosting our own Browserless.io Docker container (https://hub.docker.com/r/browserless/chrome/dockerfile). But this results in various web socket connections dropped during sessions. 

Can you confirm this should work at all? Maybe I'm not using the right version/tag? See https://hub.docker.com/r/browserless/chrome/tags.

Any guidance on this, would be very much appreciated.

**Comment by kblok** [comment]
Which kind of app is your puppeteer app? Console/Web Core/Framework...

**Comment by tedvanderveen** [comment]
Sorry about this! I'm using ASP.Net Core 3.0.
I got it working after setting `AppMode = false`.
