### ISSUE TITLE
Error trying to connect to browserless

### ISSUE THREAD

**Issue by davidrevoledo** [kblok/puppeteer-sharp#1329]
### Description

Trying to connect puppeteer-sharp with browserless to run in Azure App Service or Docker
Used code here : http://www.hardkoded.com/blogs/azure-chrome-puppeteer-browserless

### Complete minimal example reproducing the issue
```C#
var options = new ConnectOptions()
{
    BrowserWSEndpoint = $"wss://chrome.browserless.io?token={apikey}"
};

var browser = await Puppeteer.ConnectAsync(options);
var page = await browser.NewPageAsync();
```

### Actual behavior:

Error : ``` PuppeteerSharp.MessageException: 'Protocol error (Target.setAutoAttach): Invalid parameters waitForDebuggerOnStart: boolean value expected'```

### Versions

V 1.20.0
.Net Core 2.1

**Comment by kblok** [comment]
It looks like you are connected to a quite old Chromium version, older than even 73.0.3679.0, which is the version that added support to  `waitForDebuggerOnStart`.

Do we have a way to choose the Chromium version in Browserless?

**Comment by inuvano-labs** [comment]
I reached out to browserless on twitter.

"We run the last 5 versions of puppeteers bundled Chromium & chrome stable for Dedicated (plans). Usage based (plans) are currently running puppeteer@2.0.0 Chromium"

"You can pick the version when you sign up. And can be changed any time"

@davidrevoledo  is it possible you have selected v1.12 in your account on browserless? As this matches the chromium version that @kblok mentions above https://github.com/puppeteer/puppeteer/releases/tag/v1.12.2

**Comment by davidrevoledo** [comment]
@inuvano-labs  thanks I'll close this issue
