### ISSUE TITLE
EvaluateExpressionAsync does not work with async javascript functions

### ISSUE THREAD

**Issue by lurock** [kblok/puppeteer-sharp#1333]
### Description

EvaluateExpressionAsync does now work with a javascript function that is async. It returns immediately even though my javascript function "nextGraphic()" takes over 2 seconds to run. 
The nextGraphic method has a Promise that it resolves after a 2 second setTimout call.

Here is the call I am using:

`var graphic = await page.EvaluateExpressionAsync<Graphic>("async () => await window.nextGraphic()");`

When I call this same function using the javascript version of puppeteer in node it works as expected.  The function waits the 2 seconds and I get the correct response

Here is the call I am doing in node:

`let graphic = await page.evaluate(async () => await window.nextGraphic());`

### Expected behavior:
EvaluateExpressionAsync would wait for javascript Promise to resolve before returning result.

### Actual behavior:

Returns immediately without waiting the 2 seconds that the setTimeout function inside the nextGraphic function is set to wait.

### Versions

* Which version of PuppeteerSharp are you using?
2.0.0

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
.Net Core 3.0

### Additional Information

The nextGraphic() calculates the height and width of a dom element but it needs to wait 2 seconds for render to completely before getting those dimensions.  When I use the node version of puppeteer you can tell the code waits the 2 seconds and gets the correct dimensions but when using the C# version of puppeteer it executes immediately with the dimensions still set to 0.

**Comment by kblok** [comment]
@lurock one difference between puppeteer and puppeteer-sharp is that, as we are not being able to use native javascript code, everything is represented as a string. So you can use `EvaluateExpressionAsync` for expressions, such as `"1 + 2"` and `EvaluateFunctionAsync` for functions, such as `"() => 1 + 2"` or `"async () => await window.nextGraphic()"`.

Short answer, you have to use `EvaluateFunctionAsync`.
