### ISSUE TITLE
Cookie: Expire format unclear

### ISSUE THREAD

**Issue by Blenderpics** [kblok/puppeteer-sharp#1335]
https://github.com/kblok/puppeteer-sharp/blob/b3111a19285ca8db9c201fc5f355f452fa6e4a8c/lib/PuppeteerSharp/CookieParam.cs#L46
  
Hey there!  
It's not completely clear to me in which format the expires timestamp is provided.  
Is it a unix timestamp?  
Thanks!

**Comment by kblok** [comment]
@Blenderpics it´s unix time in seconds. Explanation added. Thanks for reporting this.
