### ISSUE TITLE
PuppeteerSharp.TargetClosedException: Protocol error(Page.printToPDF): Target closed. (The remote party closed the WebSocket connection without completing the close handshake.)

### ISSUE THREAD

**Issue by lsheng-mel** [kblok/puppeteer-sharp#1338]
Puppeteer started failing with exceptions after a few times of success:

`PuppeteerSharp.TargetClosedException: Protocol error(Page.printToPDF): Target closed. (The remote party closed the WebSocket connection without completing the close handshake.)\n   at PuppeteerSharp.CDPSession.SendAsync(String method, Object args, Boolean waitForCallback)\n   at PuppeteerSharp.CDPSession.SendAsync[T](String method, Object args)\n   at PuppeteerSharp.Page.PdfInternalAsync(String file, PdfOptions options)\n   at PuppeteerSharp.Page.PdfAsync(String file, PdfOptions options)`

This .net core 2.1 console application running in docker container on aws Linux ec2 instance. My Dockerfile:

`FROM microsoft/dotnet:2.1-sdk as builder
WORKDIR /app
COPY . .
RUN dotnet restore --ignore-failed-sources
RUN dotnet publish -c Release -o /dist

FROM microsoft/dotnet:2.1-aspnetcore-runtime

RUN apt-get update && apt-get -f install && apt-get -y install wget gnupg2 apt-utils
RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst ttf-freefont \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
	
ENV PUPPETEER_EXECUTABLE_PATH "/usr/bin/google-chrome-stable"

WORKDIR /app
COPY --from=builder /dist .

ENTRYPOINT ["dotnet", "XXX.XXX.XXX.dll"]`

Puppteer browser is initiated in following class, note that this class is injected to some other classs in transient mode:

`public class HeaderlessChrome : IHeaderlessChrome
    {
        public async Task ConvertPdf(string url, string outputFile)
        {
            var browser = await LaunchBrowser();
            var page = await browser.NewPageAsync();
            await page.GoToAsync(url);

            if (File.Exists(outputFile))
            {
                File.Delete(outputFile);
            }

            await page.PdfAsync(outputFile, new PdfOptions
            {
                DisplayHeaderFooter = false,
                Format = PaperFormat.A4
            });
            await browser.CloseAsync();
        }

        private static async Task<Browser> LaunchBrowser()
        {
            return await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true,
                LogProcess = true,
                DumpIO = true,
                Args = new string[]
                {
                    "--no-sandbox"
                }
            });
        }
    }`

Everything works fine on local machine debugging (Windows). 

Any ideas what may be causing the issue here? Thanks in advance!

**Comment by kblok** [comment]
Could you try using this image `hardkoded/puppeteer-sharp-base:latest-sandboxed`?
[Check this out](http://www.hardkoded.com/blog/puppeteer-sharp-docker).

**Comment by lsheng-mel** [comment]
turned out that it was the memory on the sandbox the program was deployed to is not big enough. bumped it up to 1GB and it was all good.

**Comment by kblok** [comment]
Awesome!
