### ISSUE TITLE
Firefox testing

### ISSUE THREAD

**Issue by jgilbert2017** [kblok/puppeteer-sharp#1340]
How can i test automation with Firefox?  Do I need to build a certain branch?  I don't see any relevant LaunchOptions.  Thanks.

**Comment by kblok** [comment]
@jgilbert2017 there is not support for Firefox yet.

**Comment by jgilbert2017** [comment]
ok, i see.  the main puppeteer repo looks like could be pretty functional.  is it a lot of work to wire up p# for firefox for the purpose of testing?  my use case is pretty simple and perhaps i can fill in any broken bits and submit a patch.  thanks!

**Comment by kblok** [comment]
It might look pretty functional in the repo, but they are using a custom Firefox build and I haven't seen changes in the puppeteer-firefox codebase for a while. And as it's marked as experimental I don't think that's ready to be used for real.

**Comment by jgilbert2017** [comment]
gotcha.
