### ISSUE TITLE
The slack link in README.md is no longer working

### ISSUE THREAD

**Issue by cado1982** [kblok/puppeteer-sharp#1342]
The link to https://join.slack.com/t/puppeteer/shared_invite/enQtMzU4MjIyMDA5NTM4LTM1OTdkNDhlM2Y4ZGUzZDdjYjM5ZWZlZGFiZjc4MTkyYTVlYzIzYjU5NDIyNzgyMmFiNDFjN2UzNWU0N2ZhZDc found in the Useful links section of the repo readme results in an error

> This invite link is no longer active.
Please check with the person who shared it with you to see if there's a new link available.

**Comment by kblok** [comment]
Thank you for reporting this. Checking the url...
