### ISSUE TITLE
Question: how to listen to DOM change?

### ISSUE THREAD

**Issue by NewITCorp** [kblok/puppeteer-sharp#1346]
Hello Team,
I wish to listen to element changes without polling by intervals. I see there is a best practice to implement MutationObserver  in js, but dont know how to use it with the puppeteer-sharp. 
Any small advise will be glad.

Thank you and respect

**Comment by kblok** [comment]
You can use ExposeFunctionAsync to expose a function, and use that function inside the observer.  This post might be useful http://www.hardkoded.com/blog/creating-whatsapp-bot-puppteer-sharp
