### ISSUE TITLE
Puppeteer chrome BrowserContext instead of Incognito Mode

### ISSUE THREAD

**Issue by RakeshAllikatti** [kblok/puppeteer-sharp#1348]
Can I Open Normal Browser Context, instead of Incognito mode like await browser.CreateIncognitoBrowserContextAsync(),

Please assist me

Thank you, 
Rakesh

**Comment by kblok** [comment]
You can have many incognito browser contexts, but only one non-incognito, which is the [DefaultContext](https://www.puppeteersharp.com/api/PuppeteerSharp.Browser.html#PuppeteerSharp_Browser_DefaultContext)
