### ISSUE TITLE
feature: PageCreated event

### ISSUE THREAD

**Issue by jgilbert2017** [kblok/puppeteer-sharp#1353]
would it be possible to support a PageCreated event so common actions can be easily be done for all created pages?

**Comment by kblok** [comment]
Did you try [TargetCreated](https://www.puppeteersharp.com/api/PuppeteerSharp.BrowserContext.html#PuppeteerSharp_BrowserContext_TargetCreated)?

**Comment by jason1039** [comment]
Can give me example?
I don't understand.
