### ISSUE TITLE
  How to inject HTML code into div？

### ISSUE THREAD

**Issue by whgfu** [kblok/puppeteer-sharp#1359]
var AAA = await firstPage.QuerySelectorAsync("div.w-e-text");

How to inject HTML code into AAA object?

**Comment by kblok** [comment]
You can do this:

```cs
await firstPage.QuerySelectorAsync("div.w-e-text").ExecuteFunctionAsync("el => el.textContent = content;", content);
```

**Comment by whgfu** [comment]
orry, I didn't find the ExecuteFunctionAsync method, only the EvaluateFunctionAsync method, but this method will fail to execute:
{"Evaluation failed: SyntaxError: Unexpected token ';'"}

**Comment by kblok** [comment]
Sorry, how about this?

```cs
await firstPage.QuerySelectorAsync("div.w-e-text").EvaluateFunctionAsync("el => el.textContent = content", content);
```

**Comment by whgfu** [comment]
` try
                        {
                            
                            var content = "11111";
                            await firstPage.QuerySelectorAsync("div.w-e-text").EvaluateFunctionAsync("el => el.textContent = content", content);
                        }
                        catch (Exception ex)
                        {
                            InsertState(ex.ToString());
                        }`

PuppeteerSharp.EvaluationFailedException: Evaluation failed: ReferenceError: content is not defined
    at __puppeteer_evaluation_script__:1:25
   在 PuppeteerSharp.ExecutionContext.<ExecuteEvaluationAsync>d__21.MoveNext()
--- The end of the stack trace in the previous location where the exception was thrown ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 PuppeteerSharp.ExecutionContext.<RemoteObjectTaskToObject>d__18`1.MoveNext()
--- The end of the stack trace in the previous location where the exception was thrown---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 PuppeteerSharp.Extensions.<EvaluateFunctionAsync>d__1`1.MoveNext()
--- The end of the stack trace in the previous location where the exception was thrown ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   在 Nord.UI.frmMain.<PublishUI>d__19.MoveNext() 位置 F:\CrawlerSamples-master\Nord.UI\frmMain.cs:行号 318 
2020-01-13 20:40:36 => System.IndexOutOfRangeException: 索引超出了数组界限。
   在 Nord.UI.frmMain.<PublishUI>d__19.MoveNext() 位置 F:\CrawlerSamples-master\Nord.UI\frmMain.cs:行号 359

**Comment by kblok** [comment]
Ok, take 3 😂 

```cs
await firstPage.QuerySelectorAsync("div.w-e-text").EvaluateFunctionAsync("(el, content) => el.textContent = content", content);
``

**Comment by whgfu** [comment]
Thank you very much. This time, it's text or HTML. I want to inject HTML
 😂

**Comment by whgfu** [comment]
await firstPage.QuerySelectorAsync("div.w-e-text").EvaluateFunctionAsync("(el, content) => el.innerHTML = content", body);

thank you !!!
