### ISSUE TITLE
UploadFileAsync fails with browserless.io

### ISSUE THREAD

**Issue by Code-DJ** [kblok/puppeteer-sharp#1363]
### Description

UploadFileAsync doesn't work with browserless.io - note that I am using hosted version of browserless but the same applies to browserless.io as well.

The upload fails because the method ElementHandle.UploadFileAsync resolves the path using Path.GetFullPath. So when Puppeteer-Sharp is run on Windows, it resolves "/usr/src/app/workspace/filename.ext" to "C:\usr\src\app\workspace\filename.ext".

Since browserless is running on a remote server, they allow you to upload your file to your workspace (https://docs.browserless.io/docs/workspace.html) on the remote server and then reference it with puppeteer.

After uploading the file to your workspace, you can access it as "/usr/src/app/workspace/filename.ext".

### Complete minimal example reproducing the issue

```csharp
// Arrange

// Use HttpClient to upload a file to browserless.io workspace.

var url = "http://somefileuploadservice.com/";
var filename = "/usr/src/app/workspace/foo.txt";

string apikey = config["browserlessApiKey"];
var options = new ConnectOptions()
{
    BrowserWSEndpoint = $"wss://chrome.browserless.io?token={apikey}"
};

var browser = await Puppeteer.ConnectAsync(options);
var page = await browser.NewPageAsync();

// Act
await page.GoToAsync(url);

var el = page.QuerySelectorAsync("input[name='file1']");
await el.UploadFileAsync(filename);

// Use HttpClient to delete the file from browserless.io workspace.

// Assert
// Check if file was uploaded correctly to the website.
```

### Expected behavior:

UploadFileAsync to successfully upload the file.

### Actual behavior:

Due to the file getting resolved from "/usr/src/app/workspace/filename.ext" to "C:\usr\src\app\workspace\filename.ext", the upload fails.

### Versions

* PuppeteerSharp 2.0
* .NET framework 4.7.2

**Comment by kblok** [comment]
Interesting, good catch.

**Comment by Code-DJ** [comment]
Can I submit a PR? Is it better to let API users resolve paths in their own code or should we handle it using method overloading?

e.g.
```
public Task UploadFileAsync(params string[] filePaths) => UploadFileAsync(true, filePaths);

public Task UploadFileAsync(bool resolveFilePaths, params string[] filePaths)
{
    var files = resolveFilePaths ? filePaths.Select(Path.GetFullPath).ToArray() : filePaths;
    var objectId = RemoteObject.ObjectId;
    return Client.SendAsync("DOM.setFileInputFiles", new DomSetFileInputFilesRequest
    {
        ObjectId = objectId,
        Files = files
    });
}
```
