### ISSUE TITLE
Frame.GetContentAsync() return content before javascript execution

### ISSUE THREAD

**Issue by KardoseR** [kblok/puppeteer-sharp#1369]
Frame.GetContentAsync() return content before javascript execution, i want the complete content after javascript executed(at the time of the method call)

### Complete minimal example reproducing the issue

E.g.

```csharp
var content = page.Frames[0].GetContentAsync().GetAwaiter().GetResult();
```

### Expected behavior:

Should return code after javascript execution.

### Versions

* Which version of PuppeteerSharp are you using?
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by kblok** [comment]
@KardoseR You should try to find some hint which tells you that it finished.
Any DOM element you can use with a `WaitForSelectorAsync`? Any javascript code you can evaluate with `WaitForExpressionAsync`? 

Once you find that it would be a matter of using the right waitFor and then call GetContentAsync.

Also, remember to use `await` instead of `GetAwaiter().GetResult();`.

**Comment by KardoseR** [comment]
I know the content is already loaded because i can inspect it in the chromium window, i call that method way after that happens...

**Comment by kblok** [comment]
@KardoseR did you try any of these?

>Any DOM element you can use with a WaitForSelectorAsync? Any javascript code you can evaluate with WaitForExpressionAsync?

`GetContentAsync` calls `document.documentElement.outerHTML` internally. If you run that on DevTools, do you get what you expect?

**Comment by KardoseR** [comment]
So most of the puppeteer commands can be translated to javascript calls? No I dont get what I want because I am trying to query an iframe, in selenium I would call driver.SwitchTo().Frame(0); and then driver.PageSource to get the desired result.

**Comment by KardoseR** [comment]
So In short, i would like to be able to get the same result as I would with selenium

**Comment by kblok** [comment]
WaitForSelectorAsync or WaitForExpressionAsync should help you accomplish what you need.
