### ISSUE TITLE
Waiting for popup

### ISSUE THREAD

**Issue by RobertBaldini** [kblok/puppeteer-sharp#1370]
### Description

Popup is a page **event**, which runs into problems with the **async** methods.

I'm trying to click a button that opens a popup.

After the popup opens, I'm trying to call `browser.PagesAsync()` to get the new page.

### Complete minimal example reproducing the issue

Sorry I don't have a great example, I'm working on an internal company tool and it's hard to find a hosted page that has a similar popup.

I noticed there's a sample popup page in the repo... https://github.com/kblok/puppeteer-sharp/tree/master/lib/PuppeteerSharp.TestServer/wwwroot/popup

The code I'm working with looks something like this:

```csharp
public async Task ClickThisAsync(string elementSelector)
{
	var clickTask = this.CurrentPage.ClickAsync(elementSelector);
	
	var waitForIdleNav = new NavigationOptions {
		WaitUntil = new[] { WaitUntilNavigation.Networkidle0 }
	};
	// doesn't work, need to wait for nav on new page 
	var waitForIdleTask = this.CurrentPage.WaitForNavigationAsync(waitForIdleNav);
	
	// obvious race condition
	this.CurrentPage.Popup += async (sender, args) => {
		this.OpenPages = await _browser.PagesAsync();
		this.CurrentPage = this.OpenPages.FirstOrDefault();
	};
	
	// still a race condition
	//this.CurrentPage.Popup += (sender, args) => {
	//  	this.OpenPages.Add(args.PopupPage);
	//};
	
	await Task.WhenAll(waitForIdleTask, clickTask);
}
```

### Expected behavior:

I think I actually found a solution in JavaScript, but I have no idea if there's a way to make it work in C# / PuppeteerSharp.

```javascript
const [_, popup] = await Promise.all([
      page.click('a'),
      new Promise(resolve => page.once('popup', async (popup) => {
        await popup.waitFor('selector', {
          waitUnitl: ['networkidle0', 'load', 'networkidle2', 'domcontentloaded']
        })
        resolve(popup)
      }))
    ]);
```
(from https://github.com/puppeteer/puppeteer/issues/1412#issuecomment-465849461) 

### Actual behavior:

The `ClickAsync` completes before the `Popup` event.

There's no way to get a handle on the new `Page`.

### Versions

* Which version of PuppeteerSharp are you using?
PuppeteerSharp v2.0.0

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
.NET Core 3.1

**Comment by kblok** [comment]
Hey @RobertBaldini!
You will have a "translation" for that recipe [here](https://github.com/kblok/puppeteer-sharp/blob/7fca5eeeaa9e138af09e24bd98d11d128cac260b/lib/PuppeteerSharp.Tests/PageTests/Events/PopupTests.cs#L17).

**Comment by RobertBaldini** [comment]
Awesome!  Except... now I need to wait for the popup to finish loading. (Otherwise it's just passing back an empty page.)

This is the closest I could think of, but `WaitForNavigationAsync` doesn't work if you've already awaited the `ClickAsync`.  

```csharp
if (requestedBehavior?.IsPopupExpected == true)
{
	var popupTaskSource = new TaskCompletionSource<Page>();
	var popupHandler = new EventHandler<PopupEventArgs>(async (sender, args) => {
		var newPage = args.PopupPage;
		// nothing to wait for, we've already clicked
		await newPage.WaitForNavigationAsync(waitForIdleNav);
		popupTaskSource.TrySetResult(newPage);
	});
	
	this.CurrentPage.Popup += popupHandler;
	await Task.WhenAll(popupTaskSource.Task, clickTask);
	this.CurrentPage.Popup -= popupHandler;
	
	this.OpenPages = await _browser.PagesAsync();
}
```

**Comment by kblok** [comment]
`Task.WhenAll` should wait for the click and your `TaskCompletionSource`.
Maybe you could use a `WaitForSelectorAsync` instead of `WaitForNavigationAsync`?

**Comment by RobertBaldini** [comment]
We're building up our selectors dynamically, so that wasn't an option for me. But I was trying to think of what else I could await, and looks like I found something that works.

I'm sure there's some cases where you wouldn't want to refresh the popup, but I'll cross that bridge when I come to it. :)

Thanks for all of your help! Never would have thought of the TaskCompletionSource; I definitely learned some things today.


```csharp
if (requestedBehavior?.IsPopupExpected == true)
{
	var popupTaskSource = new TaskCompletionSource<Page>();
	var popupHandler = new EventHandler<PopupEventArgs>(async (sender, args) => {
		var newPage = args.PopupPage;
		await newPage.ReloadAsync(waitForIdleNav);
		popupTaskSource.TrySetResult(newPage);
	});
	
	this.CurrentPage.Popup += popupHandler;
	await Task.WhenAll(popupTaskSource.Task, clickTask);
	this.CurrentPage.Popup -= popupHandler;
	
	this.OpenPages = await _browser.PagesAsync();
}
```

**Comment by kblok** [comment]
Closing the issue, feel free to create a new one if you need more help.

**Comment by RobertBaldini** [comment]
Sorry, one last thing...  It tricked me. :) 

When I call `PagesAsync`, sometimes the popup is the last page, but sometimes it's the first page.

I tried doing the event handler without the async, but same thing.

Maybe, as a workaround, is there any way to `OrderBy` the pages? To get them in the order they were created?


```csharp
var popupTaskSource = new TaskCompletionSource<Page>();
var popupHandler = new EventHandler<PopupEventArgs>((sender, args) => {
	var newPage = args.PopupPage;
	popupTaskSource.TrySetResult(newPage);
});
_page.Popup += popupHandler;
await Task.WhenAll(popupTaskSource.Task, clickTask);
_page.Popup -= popupHandler;

var newPage = popupTaskSource.Task.Result;
await newPage.ReloadAsync(waitForIdleNav);

// newPage is sometimes first or last
this.OpenPages = await _browser.PagesAsync();
```

**Comment by kblok** [comment]
@RobertBaldini the thing is that there is lots of async stuff going on when `PagesAsync` is called. Long story short we are making sure that all the pages (which is a list of Targets filtered by TargetType) are initialized and ready to be interacted with.

Maybe you can filter that array by URL?

```cs
(await _browser.PagesAsync()).Where(p => p.Url.Contains(yourPopupUrl));
```
