### ISSUE TITLE
Strange behaviour when using --user-agent command-line option

### ISSUE THREAD

**Issue by njlr** [kblok/puppeteer-sharp#1371]
**Before you file a bug, have you:**

* Tried upgrading to newest version of PuppeteerSharp, to see if your issue has already been resolved and released? ✔️
* Checked existing open *and* closed [issues](https://github.com/kblok/puppeteer-sharp/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported? ✔️
* Tried reproducing your problem in a new isolated project? ✔️
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/search?q=puppeteer-sharp). ✔️

### Description

When I add `--user-agent` to my list of arguments the browser opens with many tabs and various events such as `page.DOMContentLoaded` do not fire correctly.

### Complete minimal example reproducing the issue

My code is F# but I have translated to C#:

```csharp
// Arrange
var customUserAgent = "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"

var options = new LaunchOptions { 
  Args = new string[] { "--user-agent='" + customUserAgent + "'" }
 };

var chromiumRevision = BrowserFetcher.DefaultRevision;
var browser = await Puppeteer.LaunchAsync(options, chromiumRevision);
var pages = await browser.PagesAsync();
var page = pages[0];

// Wait forever
...
```

Minimal example in F#: 

```fsharp
open System
open System.IO
open PuppeteerSharp

[<Literal>]
let private CustomUserAgent = "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"

[<EntryPoint>]
let main argv =

  async {
    let userDataDir =
      Path.Combine (Path.GetTempPath (), "puppeteer", Path.GetRandomFileName ())

    let fetcher = BrowserFetcher()

    do!
      fetcher.DownloadAsync(BrowserFetcher.DefaultRevision)
      |> Async.AwaitTask
      |> Async.Ignore

    let opts = LaunchOptions()

    opts.Headless <- false
    opts.UserDataDir <- userDataDir
    opts.Args <- [|
      "--user-agent='" + CustomUserAgent + "'"
    |]

    use! browser =
      Launcher().LaunchAsync(opts)
      |> Async.AwaitTask

    let! pages =
      browser.PagesAsync()
      |> Async.AwaitTask

    use page = pages.[0]

    page.DOMContentLoaded.AddHandler (EventHandler (fun sender args ->
      printfn "DOMContentLoaded: %s\n\n" page.Url
    ))

    // Wait forever
    do! Async.FromContinuations ignore
  }
  |> Async.RunSynchronously

  0
```

### Expected behavior:

Browser launches with one page. When that page is navigated, the `DOMContentLoaded` event should fire.

### Actual behavior:

Browser launches with tabs at:

 * `about:blank`
 * `%28windows`
 * `nt`
 * `gecko`
 * `firefox`

It appears that the launcher is interpreting my user-agent string as a list of URLs to open!

### Versions

* Which version of PuppeteerSharp are you using?

```
nuget PuppeteerSharp 2.0.0
```

* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.

```
netcoreapp3.0
```

### Additional Information

None

**Comment by kblok** [comment]
Did you tried using SetUserAgentAsync?

**Comment by njlr** [comment]
> Did you tried using SetUserAgentAsync?

Yes that works, however the command-line argument should also work.

**Comment by kblok** [comment]
So this would be more a bug upstream (in chromium) there is no much we can do downstream (in our .NET core)
