### ISSUE TITLE
UnobservedTaskException

### ISSUE THREAD

**Issue by nitinag** [kblok/puppeteer-sharp#1377]
### Description

We monitor UnobservedTaskException to catch bugs/issues and found that Puppeteer Sharp is causing two such exceptions to be thrown rather than handling them. The timeout exception is surprising since the request completes successfully in much less time and doesn't seem to timeout at all. The two exceptions appear together for one request when the sample code included below is executed:

#891 and #1016 seem to be related to this issue.

```
System.TimeoutException: Timeout of 5000 ms exceeded
   at PuppeteerSharp.Helpers.TaskHelper.<WithTimeout>d__8`1.MoveNext()
```
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Web.ThreadContext.AssociateWithCurrentThread(Boolean setImpersonationContext)
   at System.Web.HttpApplication.OnThreadEnterPrivate(Boolean setImpersonationContext)
   at System.Web.HttpApplication.System.Web.Util.ISyncContext.Enter()
   at System.Web.Util.SynchronizationHelper.SafeWrapCallback(Action action)
   at System.Threading.Tasks.Task.Execute()
```

### Complete minimal example reproducing the issue

```csharp
var browserFetcher = new BrowserFetcher(new BrowserFetcherOptions { Path = @"c:\chromium-path\" });
var revisionInfo = await browserFetcher.DownloadAsync(BrowserFetcher.DefaultRevision);
using (var browser = await Puppeteer.LaunchAsync(new LaunchOptions { Headless = true, ExecutablePath = revisionInfo.ExecutablePath }))
{
	using (var page = await browser.NewPageAsync())
	{
		await page.SetContentAsync("<div>My Receipt</div>", new NavigationOptions { Timeout = 5000 });	
		var pdfBytes = await page.PdfDataAsync();
	}
}
```

### Expected behavior:

No UnobservedTaskException should be raised

### Actual behavior:

Raising UnobservedTaskException

### Versions

* Which version of PuppeteerSharp are you using?
2.0.1

* Which .NET runtime and version are you targeting?
.NET framework 4.7.2

**Comment by kblok** [comment]
Hey @nitinag 
I tried hard on #891 trying to get to a solution here. I could invest some time on it, maybe I learned something in the past year :p  
The issue is how to implement timeouts without leaving orphan tasks.

I'm also open to new ideas and pull requests.

**Comment by nitinag** [comment]
Hi @kblok,

This is what we use based originally on https://devblogs.microsoft.com/pfxteam/crafting-a-task-timeoutafter-method/ with customizations:

```csharp
public static async Task TimeoutAfter(this Task task, TimeSpan timespanTimeout)
{
	if (timespanTimeout <= TimeSpan.Zero)
		throw new ArgumentOutOfRangeException(nameof(timespanTimeout), "Timeout must be greater than 0");

	//Task already complete
	if (task.IsCompleted)
	{
		await task.ConfigureAwait(false);
		return;
	}
	
	using (var timeoutCts = new CancellationTokenSource(timespanTimeout))
	{
		//Create task from timeoutCts
		var tcs = new TaskCompletionSource<bool>();
		using (timeoutCts.Token.Register(s => ((TaskCompletionSource<bool>)s).TrySetResult(true), tcs, false))
		{
			//Task Complete
			//timeoutCts will be automatically disposed on function exit
			if (task == await Task.WhenAny(task, tcs.Task).ConfigureAwait(false))
			{
				await task.ConfigureAwait(false);
				return;
			}

			//Continuation to Observe / Ignore Exception in Orphan Original Task
			ObserveExceptions(task);

			//Timeout Triggered
			throw new TimeoutException();
		}
	}
}

private static void ObserveExceptions(Task task)
{
	task.ContinueWith(t =>
	{
		var ignoredException = t.Exception;
	}, TaskContinuationOptions.OnlyOnFaulted | TaskContinuationOptions.ExecuteSynchronously);
}
```
I also noticed ConfigureAwait was missing on all awaits in https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Helpers/TaskHelper.cs.

**Comment by kblok** [comment]
>This is what we use based originally on https://devblogs.microsoft.com/pfxteam/crafting-a-task-timeoutafter-method/ with customizations:

This is awesome. I will give it a try.

>I also noticed ConfigureAwait was missing on all awaits in https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Helpers/TaskHelper.cs.

Yeah, I noticed that while migrating code to [Playwright-Sharp](https://github.com/kblok/playwright-sharp). I'll add some code analyzers here.

Thank you!

**Comment by nitinag** [comment]
Great! The only thing I couldn't understand was why it was generating a timeout exception in the first place because everything seemed to respond well before the timeout that we set. It seemed like there was something else going on since the timeout shouldn't have been triggered at all. It didn't seem like anything in your existing WithTimeout method should cause an orphan timeout exception unless the cancellationToken.CancelAfter in your code isn't cleaned up by the framework on dispose in which case maybe our code will help fix it since we don't run into the same issue in our own code.

**Comment by kblok** [comment]
@nitinag agreed. [This](https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Helpers/TaskHelper.cs#L142) should return false most of the cases. Maybe were are using `WithTimeout` where we shouldn't?

Let me get back to that issue I see what I find.

**Comment by kblok** [comment]
@nitinag long story short: We were not canceling the [TerminationOrTimeout task](https://github.com/kblok/puppeteer-sharp/pull/1380/files#diff-55e5301bb3d8344d796d9f3fa50376a5R76) and that was eventually triggering the timeout.

Would you mind building the project locally and test it out? If you get good results I'll ship v2.0.2

**Comment by nitinag** [comment]
@kblok Tested it and looks good. No more UnobservedTaskExceptions are being raised from our sample code.

**Comment by kblok** [comment]
@nitinag v2.0.2 shipped!
