### ISSUE TITLE
Implement Page.waitFor

### ISSUE THREAD

**Issue by kblok** [kblok/puppeteer-sharp#141]
https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/test/test.js#L887

**Comment by Meir017** [comment]
this should be `Page.waitFor`...
since [`describe('Page.waitFor', function() {`](https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/test/test.js#L887)

**Comment by Meir017** [comment]
and therefore should be part of 0.4 :)
