### ISSUE TITLE
Cannot open file PuppeteerSharp.ruleset in Visual Studio

### ISSUE THREAD

**Issue by dergroncki** [kblok/puppeteer-sharp#1444]
Because CA1062 is used 2 times it is not possible to open the ruleset file.

![Screenshot 2020-03-03 at 13 32 55](https://user-images.githubusercontent.com/2815398/75776254-f1e1d780-5d53-11ea-8bb7-b4c8d0d65126.jpg)

```
    <Rule Id="CA1062" Action="None" /> <!-- Error CA1062: VALIDATE OPTIONS-->
    <Rule Id="CA1062" Action="None" /> <!-- Error CA1031: Modify 'DeleteAsync' to catch a more specific allowed exception type, or rethrow the exception. (CA1031)-->
```

**Comment by kblok** [comment]
Ops. Feel free to create a PR @dergroncki or I can create one this evening.
