### ISSUE TITLE
Wrong chromium version in v2.0.0 release notes (r706915 not r705776)

### ISSUE THREAD

**Issue by volleio** [kblok/puppeteer-sharp#1445]
### Description

Same issue as in puppeteer's repo - https://github.com/puppeteer/puppeteer/issues/5136.
[This commit's message](https://github.com/kblok/puppeteer-sharp/commit/74488cf1760b2d4895a4855e9be87cb50ec3c9d8#diff-8bcf5eae342f451c5cb92f4bad0e23e1) and the [v2.0.0 release notes](https://github.com/kblok/puppeteer-sharp/releases/tag/v2.0) say that the chromium revision was updated to r705776, when it was actually updated to r706915:
`DefaultRevision = 706915;`

### Versions
Puppeteer v2.0.0+

**Comment by kblok** [comment]
Awesome, Thank you @volleio!

**Comment by kblok** [comment]
Release note changed
