### ISSUE TITLE
QuerySelectorAllAsync   div a

### ISSUE THREAD

**Issue by whgfu** [kblok/puppeteer-sharp#1448]
jquery: on webpage
```js
$("div.show-auto-save a")[0]
```
We can get the result：
```html
<a data-v-fc117650 href=​"javascript:​void(0)​">Cancel​</a>​
```
If I use puppetersharp：
```cs
var input3 = await firstPage.QuerySelectorAllAsync("div.show-auto-save a");
```

Cannot get this a object.

help me，thank you

**Comment by Meir017** [comment]
@whgfu  what happens? does the method return an empty array?

**Comment by whgfu** [comment]
Array，result：
Node is either not visible or not an HTMLElement

Sorry, I didn't make it clear. It's an invisible element. How to operate it? I get a object. I want to execute the click error.

**Comment by Meir017** [comment]
are you trying to hover/click/tap? if so then it's by design and you should make the element visible first

**Comment by whgfu** [comment]
Yes, I haven't found out how to make the elements visible. I can implement it with jQuery, but I haven't succeeded in using puppetersharp

**Comment by whgfu** [comment]
$("div.show-auto-save").css("display","")

**Comment by Meir017** [comment]
well, you can execute that using puppeteersharp.
puppeteer will try to scroll the elemen into view but it won't try to make it visible

**Comment by whgfu** [comment]
Yes, I have. This is my code
` var js = "$(\"div.show-auto-save\").css(\"display\", \"\")";
                    await firstPage.EvaluateFunctionAsync($"() => {js}");
                    var input4 = await firstPage.QuerySelectorAllAsync("div.show-auto-save a");
                    await input4[0].ClickAsync();`
