### ISSUE TITLE
Publish Documentation

### ISSUE THREAD

**Issue by Meir017** [kblok/puppeteer-sharp#160]
Consider using [docfx](https://dotnet.github.io/docfx/) for documentation once we complete documentation the code.

Maybe add code samples in  the documentation like [cake](https://github.com/cake-build/cake) does.
example:
souce - https://github.com/cake-build/cake/blob/develop/src/Cake.Common/ArgumentAliases.cs#L28
generated docs - https://cakebuild.net/api/Cake.Common/ArgumentAliases/20DF3649

**Comment by Meir017** [comment]
Need to read how github pages work

**Comment by kblok** [comment]
It’s pretty easy to implement. You just need to push our docs to the “docs” folder.
I’d would like to think more about how we would integrate this into our workflow. I would like this to be and automated step.
