### ISSUE TITLE
ERROR: PuppeteerSharp.MessageException : Protocol error (Runtime.callFunctionOn): Object reference chain is too long 

### ISSUE THREAD

**Issue by Meir017** [kblok/puppeteer-sharp#166]
when using `EvaluateExpressionAsync` or `EvaluateFunctionAsync` to return a `dynamic` object of something big the following exception is thrown:
PuppeteerSharp.MessageException : Protocol error (Runtime.callFunctionOn): Object reference chain is too long.

to reproduce this:
```cs
public class test
{
    [Fact]
    public async Task EvaluateBigObject()
    {
        using (var browser = await PuppeteerSharp.Puppeteer.LaunchAsync(TestConstants.DefaultBrowserOptions(), TestConstants.ChromiumRevision))
        using (var page = await browser.NewPageAsync())
        {
            var window = await page.EvaluateExpressionAsync("window"); // this throws
        }
    }
}
```

I suggest we delete the overloads that return `dynamic`.

whenever we don't care about the result we should use `EvaluateExpressionHandleAsync` or `EvaluateFunctionHandleAsync`

**Comment by kblok** [comment]
I don't know if removing `dynamic` support is the solution but let's take a look at it.
