### ISSUE TITLE
We have a real fail in develop

### ISSUE THREAD

**Issue by kblok** [kblok/puppeteer-sharp#177]
https://ci.appveyor.com/project/kblok/puppeteer-sharp/build/1.0.476

**Comment by Meir017** [comment]
not sure it's a real bug since it passes locally and in other runs (for example - https://ci.appveyor.com/project/kblok/puppeteer-sharp/build/1.0.480/tests)

**Comment by kblok** [comment]
I know, but the error doesn't look like our typical temporary errors. Just not to miss this issue. We will see who it looks after our next merge
