### ISSUE TITLE
lost files

### ISSUE THREAD

**Issue by cnryb** [kblok/puppeteer-sharp#2]
lost files  
lib\PuppeteerSharp.TestServer\testCert.cer

**Comment by kblok** [comment]
Hey @cnryb, I need to create a how to get started document, well I need to create many things 😛 

That testCert.cer is supposed to be created on your machine, is a self signed certificate the local test server would use to server https pages.

You can google about creating self signed certificates (I would link to some examples but I don't know whether you are on windows or on Mac)

**Comment by cnryb** [comment]
Thank you for your reply.
I used windows. But I think MAC users also need some examples. 
By the way, emoticon how come out?

**Comment by kblok** [comment]
In windows is quite simple https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2008-R2-and-2008/ff710475(v=ws.10)

This is one doc for mac https://support.apple.com/kb/PH20131?locale=en_US&viewlocale=en_US

For emoticons just hit ":" 😄

**Comment by cnryb** [comment]
Thank you 😸
