### ISSUE TITLE
should set page.WaitForNavigation to "public" function

### ISSUE THREAD

**Issue by skyyearxp** [kblok/puppeteer-sharp#208]
this function could be used in TargetCreated Event to wait for page to be loaded.

**Comment by Meir017** [comment]
makes sense since it part of puppeteer's public api - https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/docs/api.md#pagewaitfornavigationoptions

**Comment by Meir017** [comment]
a fix for this should also implement the related tests - https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/test/test.js#L1198
