### ISSUE TITLE
AddScriptTagOptions suggest support "nonce" attribute

### ISSUE THREAD

**Issue by skyyearxp** [kblok/puppeteer-sharp#210]
some site use nonce attribute, if without this attribute, addscripttag will fail. chrome will show error in console.

now i insert by hand.
    var jq = document.createElement('script');
    jq.setAttribute('nonce',document.scripts[0].nonce);
    jq.setAttribute('type','text/javascript');

**Comment by Meir017** [comment]
I think this should be opened as a feature request on the [puppeteer ](https://github.com/GoogleChrome/puppeteer) repo since they don't support this.

their related code - https://github.com/GoogleChrome/puppeteer/blob/master/lib/FrameManager.js#L462

**Comment by kblok** [comment]
Closing this issue. We got an answer from Puppeteer https://github.com/GoogleChrome/puppeteer/issues/2518
