### ISSUE TITLE
PuppeteerSharp.NavigationException: The WebSocket is in an invalid state ('Aborted')

### ISSUE THREAD

**Issue by Jiping-hi** [kblok/puppeteer-sharp#223]
My app is running batch downloading a list. It always breaks after a few downloads.

Should I set some kind of options? Or this might be a bug?

[PupeeteerSharp-exception.txt](https://github.com/kblok/puppeteer-sharp/files/1998845/PupeeteerSharp-exception.txt)

**Comment by JipingWang** [comment]
Pupppeteer official document shows there is an option

> pipe <boolean> Connects to the browser over a pipe instead of a WebSocket. Defaults to false.
But PuppeteerSharp doesn't have this one.

**Comment by kblok** [comment]
Hey @JipingWang. Pipe connection will be implemented when we get to [v1.1.0](https://github.com/GoogleChrome/puppeteer/releases/tag/v1.1.0)

**Comment by kblok** [comment]
@Jiping-hi 
How long does your process take in total?
Are you leaving a browser open? I think we might get that error if the WebSocket is not used for a while. Do you have some code to share with us so we can try to reproduce it?

**Comment by Jiping-hi** [comment]
@kblok I am new to Puppeteer/Sharp. I am using it like this,
```
            using (var browser = await Puppeteer.LaunchAsync(options, Downloader.DefaultRevision))
            using (var page = await browser.NewPageAsync())
            {
                PupeeteerTool.browser = browser;
                await page.SetUserAgentAsync(PupeeteerTool.userAgent);
                foreach(var item in myList){
                    response = await page.GoToAsync(url, ops);
                    // use response 
                }
            }

```

**Comment by Jiping-hi** [comment]
@kblok symptom: I've run this many times, every time it stops at the 7th downloading, the first 6 urls are finished.

**Comment by Jiping-hi** [comment]
@kblok I moved the browse and page object initialization into the for loop, it is working for now.
`    
foreach(var url in myList){
            using (var browser = await Puppeteer.LaunchAsync(options, Downloader.DefaultRevision))
            using (var page = await browser.NewPageAsync())
            {
//my code ...
            }
}
`

**Comment by Jiping-hi** [comment]
@kblok 
```
            var ops = new NavigationOptions()
            {
                Timeout = 120000,
            };
```

**Comment by kblok** [comment]
#231 will help in these situations
