### ISSUE TITLE
Can't install it via nuget

### ISSUE THREAD

**Issue by Suresokken** [kblok/puppeteer-sharp#228]
Trying to install puppeteer but cant and I get this:

Could not install package 'PuppeteerSharp 0.8.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author

**Comment by Meir017** [comment]
Can you please share your `csproj`/`packages.config` file?

**Comment by kblok** [comment]
@Suresokken I was able to create a brand new project in 4.7.2 and add PuppeteerSharp 0.8.0. Do you have the final 4.7.2 version installed?

**Comment by Suresokken** [comment]
Hey 
Sorry for slow response.
@kblok yes i have tried from 4.6.1 all the way up to 4.7.2 with no luck.

**Comment by Suresokken** [comment]
Now I'ved tried with a totally new project still same issue

**Comment by kblok** [comment]
Could you share that new project @Suresokken ?

**Comment by Suresokken** [comment]
Well now i got it working or at least imported into my project but im running VS15, and got a coworker to give me the dll after he builded it in his VS17 and added it to my project.
So that's a solution for this.

**Comment by kblok** [comment]
Got it. So maybe it was your nuget client version.

**Comment by kumkanillam** [comment]
Me too facing this issue. Even though I am targetting .NET Framework 4.5.2, it is not installing. It throws error

> "Could not install package 'PuppeteerSharp 1.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author."

I am using VS15.

Tried in console got this error,

> PM> Install-Package PuppeteerSharp -Version 1.4.0
> Attempting to gather dependency information for package 'PuppeteerSharp.1.4.0' with respect to project 'MyPuppeterDemo', targeting '.NETFramework,Version=v4.5.2'
> Attempting to resolve dependencies for package 'PuppeteerSharp.1.4.0' with DependencyBehavior 'Lowest'
> Resolving actions to install package 'PuppeteerSharp.1.4.0'
> Resolved actions to install package 'PuppeteerSharp.1.4.0'
> Install failed. Rolling back...
> Package 'PuppeteerSharp.1.4.0' does not exist in project 'MyPuppeterDemo'
> Package 'PuppeteerSharp.1.4.0' does not exist in folder 'G:\puppeteer-sharp-stuff\MyPuppeterDemo\MyPuppeterDemo\packages'
> Install-Package : Could not install package 'PuppeteerSharp 1.4.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.5.2', but the package does not contain any 
> assembly references or content files that are compatible with that framework. For more information, contact the package author.
> At line:1 char:1
> + Install-Package PuppeteerSharp -Version 1.4.0
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>

**Comment by GerhardKreuzer** [comment]
Hi,
sorry, I use .net 4.7.2 so definetely higher than 4.6.1 and it Fails.

**Comment by GerhardKreuzer** [comment]
Hi,
OS Win 10, VS2017

**Comment by kblok** [comment]
@GerhardKreuzer what errors are you getting?

**Comment by CREFaulk** [comment]
The framework target for PDFSharp is "NETStandard2.0" but Nuget in Visual Studio 2015 doesn't recognize that as matching .Net Framework 4.6.1. I was able to get VS 2017 to work as expected.

@GerhardKreuzer  Since you are using VS 2017, can you edit your project file in a text editor and see if the first PropertyGroup node contains this:
<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>

**Comment by deadmann** [comment]
same issue vs2015 too

**Comment by kblok** [comment]
That's a problem on the nuget client version. You need go update your nuget client.
