### ISSUE TITLE
Implement ConnectionReconnectAsync 

### ISSUE THREAD

**Issue by kblok** [kblok/puppeteer-sharp#231]
We will implement this after we implement all Puppeteer versions.

The idea is helping the user to restore a broken connection if the WebSocket fails. If the user can catch a PuppeteerException and try to reconnect to Chromium he will be able to resume the task she was doing.

**Comment by Jiping-hi** [comment]
Thanks, great to hear. Also to provide my finding that it always broke in the 7th page. I changed my code to create Browse for each iterate in the loop for now.

**Comment by kblok** [comment]
@Jiping-hi  You shouldn't need to do that. You could also try increasing the [KeepAliveInterval](https://github.com/kblok/puppeteer-sharp/blob/0714c7ce4070d2ad59df626db042ba6ed07c5ff6/lib/PuppeteerSharp/ConnectOptions.cs#L31)

I tested that locally (using 10 public URLs) and it worked. I'll push that this evening so you can help me reproduce it.

**Comment by szilardx** [comment]
Hi!
I am facing the situation where the connection randomly disconnects (once every second day, or so in the application).
Is this ConnectionReconnectAsync method implemented?
Would ithis useful to reconnect to the browser in case of disconnection to continue work in the browser on the already opened page?

Also I am a little bit confused, as KeepAliveInterval marked as deprecated, and also set to zero so I don't know if that helps to make the WebSocket connection more reliable.
Thanks!

**Comment by kblok** [comment]
@szilardx KeepAliveInterval is 0 because Chromium does not support a `PING` call in their WebSockets implementation.

This is not part of my priorities now. But if you want to jump in I would gladly review a PR.
