### ISSUE TITLE
Can't run puppeteer demo

### ISSUE THREAD

**Issue by dgpham112** [kblok/puppeteer-sharp#245]
Error:
cannot mix synchronous and asynchronous operation on process stream.

**Comment by kblok** [comment]
@dgpham112 could you share some code?

**Comment by dgpham112** [comment]
Yes, it error on this line of code:
using (var browser = await Puppeteer.LaunchAsync(options, Downloader.DefaultRevision))
Screenshot: https://imgur.com/a/ZZnu5Ue
Also the example usage in README.md doesn't not work.
It thrown this error:
cannot mix synchronous and asynchronous operation on process stream.
also syntax typo here:
await page.ScreenshotAsync(outputFile));

**Comment by dgpham112** [comment]
im running it on VS2017

**Comment by kblok** [comment]
Rings a bell... I'll check this out. It's failing to launch Chromium.

Are you running `await Downloader.CreateDefault().DownloadRevisionAsync(chromiumRevision);`?

**Comment by dgpham112** [comment]
Yes, i have tried the code in demo file and also the code in ReadME.md page

**Comment by dgpham112** [comment]
@kblok did you have a chance to take a look at it yet ?

**Comment by kblok** [comment]
@dgpham112 It's next in my ToDo. I hope I can take a look tomorrow.

**Comment by kblok** [comment]
Could you test these 2 things @dgpham112?

* The demo project was using v0.3. Could you update that to v0.8?
* Could you delete .local-chromium so it's being downloaded again?

**Comment by kblok** [comment]
I added a fix on #255 to avoid the "an attempt was made to transition a task to a final state" exception. But I think we should try with the steps above because we have something with your chromium instance.

**Comment by dgpham112** [comment]
@kblok 
I deleted the old project folder. I downloaded latest version on github page, after that i run the demo and it still error. 
Then i deleted .local=chromium in PuppeteerSharpPdfDemo\bin\Debug\netcoreapp2.0\.local-chromium 
but it still show the same error "an attempt was made to transition a task to final state"

**Comment by kblok** [comment]
@dgpham112 could you do me a favor? Could you go to the .local-chromium folder and run the chormium.exe you have there and tell me if it works?

If it works, Could you do the following?
Add the PuppeteerSharp project to the demo project and break here.
https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Launcher.cs#L129

Once there, grab the `chromeExecutable` variable and the `string.Join(" ", chromeArguments)` and try to run that executable with those arguments using the CommandPrompt.

Thanks for your help!

**Comment by kblok** [comment]
@dgpham112 I think #308 might be related.

Could you tell me whether your host OS is 64bits or 32bits and what folder was created under `.local-chromium`?
