### ISSUE TITLE
puppeteer sharp opening 5 instance of chrominum

### ISSUE THREAD

**Issue by virenderkverma** [kblok/puppeteer-sharp#247]
When I calling following code to open chrome, its creating 6 instances of chrome !

using (var browser = await Puppeteer.LaunchAsync(options, Downloader.DefaultRevision))

Please check !

![image](https://user-images.githubusercontent.com/976073/40385978-13f884e2-5e26-11e8-8202-a008633e0230.png)

**Comment by kblok** [comment]
That's Chromium. If you launch chromium manually you should get the same number of processes.

![screen shot 2018-05-22 at 4 44 17 pm](https://user-images.githubusercontent.com/2198466/40386197-6b0b3e1a-5ddf-11e8-9317-b84675e95e3b.png)

**Comment by virenderkverma** [comment]
Yes, I also checked same! opening around 20 URLs at the same time. Can consume 80% memory. very bad on performance!

**Comment by kblok** [comment]
You could try also try installing Chrome and setting the [ExecutablePath](https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/LaunchOptions.cs#L29) and check if you get a better performance there.

**Comment by kblok** [comment]
@virenderkverma yes. But we can't control much. Puppeteer Sharp is just a bridge to Chrome, and we know the relationship between Chrome and memory...
