### ISSUE TITLE
Can't run Puppeteer Sharp in Docker

### ISSUE THREAD

**Issue by respel** [kblok/puppeteer-sharp#262]
### Description

I am not able to run Puppeteer Sharp in a Windows docker container. It gives an error while trying to launch chromium. 

### Complete minimal example reproducing the issue

```csharp
            var options = new LaunchOptions
            {
                Headless = true
            };

            Console.WriteLine("Downloading chromium");
            await Downloader.CreateDefault().DownloadRevisionAsync(Downloader.DefaultRevision);

            Console.WriteLine("Navigating google");
            using (var browser = await Puppeteer.LaunchAsync(options, Downloader.DefaultRevision))
            using (var page = await browser.NewPageAsync())
            {
                await page.GoToAsync("http://www.google.com");

                Console.WriteLine("Generating PDF");
                await page.PdfAsync(Path.Combine(Directory.GetCurrentDirectory(), "google.pdf"));

                Console.WriteLine("Export completed");
                Console.ReadLine();
            }
```

### Actual behavior:
```
Downloading chromium
Navigating google

Unhandled Exception: PuppeteerSharp.ChromeProcessException: Failed to create connection ---> PuppeteerSharp.ChromeProcessException: Failed to launch chrome!
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharp.Launcher.<LaunchAsync>d__16.MoveNext()
   --- End of inner exception stack trace ---
   at PuppeteerSharp.Launcher.<LaunchAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at PuppeteerSharpTest.Program.<MainAsync>d__1.MoveNext() in C:\Users\xxx\source\repos\PuppeteerSharpTest\PuppeteerSharpTest\Program.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at PuppeteerSharpTest.Program.Main(String[] args) in C:\Users\xxx\source\repos\PuppeteerSharpTest\PuppeteerSharpTest\Program.cs:line 13
```
### Versions

Docker 
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false
```

Dotnet
```
.NET Command Line Tools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.15063
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.200\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11
```
### Additional Information
Publish
```
dotnet publish -o out
```
Dockerfile
```dockerfile
FROM microsoft/aspnetcore
WORKDIR /app
COPY out/ .
ENTRYPOINT ["dotnet", "PuppeteerSharpTest.dll"]
```

**Comment by kblok** [comment]
You won't be able to run Chrome inside docker. You'd need to use some solution like browserless.io.
Check out this blog post http://www.hardkoded.com/blogs/azure-chrome-puppeteer-browserless

**Comment by respel** [comment]
> You won't be able to run Chrome inside docker.

@kblok, can you please explain(or give references) why this is so ?

**Comment by respel** [comment]
@kblok , thanks for the help but I need it specifically for a windows container.

**Comment by kblok** [comment]
I'll try to dig a little bit into it. It would be great to know how to support this.
But it's out if the scope of Puppeteer Sharp. It's a Chrome issue.

**Comment by jenlyoung** [comment]
I was able to get it running easily in docker linux. I had to set execute permissions after I downloaded.

`
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
            if (IsLinux() || IsMacOs())
            {
                var path = Launcher.GetExecutablePath();
                Console.WriteLine($"Setting permissions: {path}");

                Exec($"chmod 777 {path}");
            }
`

**Comment by youngcm2** [comment]
I was able to get it running easily in docker linux. I had to set execute permissions after I downloaded.

```
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
            if (IsLinux() || IsMacOs())
            {
                var path = Launcher.GetExecutablePath();
                Console.WriteLine($"Setting permissions: {path}");

                Exec($"chmod 777 {path}");
            }
```

**Comment by kblok** [comment]
So maybe #430 will fix this issue. Thanks @youngcm2

**Comment by DdannyB** [comment]
Im using puppeteer nugetpackage 1.9.0. I also had the same issue that browser couldn't launch in my linux container. I added this line in my dockerfile and it fixed the problem for me:

apt-get install -y wget unzip fontconfig locales gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget

reference:
https://hub.docker.com/r/browserless/chrome/

**Comment by kblok** [comment]
@DdannyB are you confirming that you managed to run pptr# on Docker? Would you mind sharing some dockerfile here?

**Comment by PavelShalahai** [comment]
> public HeadlessChrome()
>         {
> 
>             _options = new LaunchOptions
>             {
>                 Headless = true,
>                 Args = new string[] { "--no-sandbox" }
>             };
>             DownloadChrome().ConfigureAwait(true).GetAwaiter().GetResult();
>         }

Can you please tell me, is it works with Headfull in the container? Like  Headless = false;
Thanks!

**Comment by DdannyB** [comment]
I dont know for sure but my guess would be i wouldstill work, I think it would only be a difference in performance because when headless is true it will not launch a full version of a browser.

This is a quote I found:
Turn off headless mode - sometimes it's useful to see what the browser is displaying. Instead of launching in headless mode, launch a full version of the browser using headless: false

**i haven't tested it so i dont know for sure!**

**Comment by shoe-diamente** [comment]
For the record I was able to make it work just via:

```
RUN apt-get update && apt-get install -y xorg openbox libnss3 libasound2
```

(in my Dockerfile) and:

```
var browser = await Puppeteer.LaunchAsync(new LaunchOptions
{
    Headless = true,
    Args = new string[] { "--no-sandbox" }
});
```

in my launch code.

**Comment by tommydangdn95** [comment]
now aday. You need install these package. so this is the dockerfile need include

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim as runtime

RUN apt-get update && apt-get install -y libx11-6 libx11-xcb1 libatk1.0-0 libgtk-3-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libpango-1.0-0 libcairo2 libasound2 libxshmfence1 libnss3

**Comment by RahatAmir** [comment]
> RUN apt-get update && apt-get install -y libx11-6 libx11-xcb1 libatk1.0-0 libgtk-3-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libpango-1.0-0 libcairo2 libasound2 libxshmfence1 libnss3

Could you please share your Dockerfile and the source code to initialize the puppeteer?

**Comment by michalgrzyska** [comment]
> now aday. You need install these package. so this is the dockerfile need include
> 
> FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim as runtime
> 
> RUN apt-get update && apt-get install -y libx11-6 libx11-xcb1 libatk1.0-0 libgtk-3-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libpango-1.0-0 libcairo2 libasound2 libxshmfence1 libnss3

Update 2023 (.NET 7):

this solution worked under `FROM mcr.microsoft.com/dotnet/aspnet:7.0 AS base`, but I also needed
```
        var browser = await Puppeteer.LaunchAsync(new LaunchOptions
        {
            Args = new string[] { "--no-sandbox" }
        });
```

and PDFs started to generate

**Comment by MSaqib-Rocket** [comment]
using var browser = await Puppeteer.LaunchAsync(new LaunchOptions
        {
            Headless = false,
            ExecutablePath = "D:\\Saqib\\Downloads\\chrome-win\\chrome.exe",
            Args = new[] { "--disable-blink-features=AutomationControlled" }

        });
       
While building the image there is no issue in cmd but when I run the image then a issue is raised that shows 

Unhandled exception. System.ComponentModel.Win32Exception (2): An error occurred trying to start process 'D:\Saqib\Downloads\chrome-win\chrome.exe' with working directory '/'. No such file or directory

//My Docker file
FROM mcr.microsoft.com/dotnet/runtime:6.0

# Install dependencies
RUN apt-get update && apt-get install -y wget

# Install Node.js and npm
RUN apt-get install -y curl
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs

# Install Google Chrome
RUN wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
RUN apt-get install -y fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libatspi2.0-0 libcairo2 libcups2 libcurl4 libdbus-1-3 libdrm2 libexpat1 libgbm1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libu2f-udev libvulkan1 libx11-6 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxkbcommon0 libxrandr2 xdg-utils
RUN dpkg -i google-chrome-stable_current_amd64.deb

# Install Puppeteer
RUN npm init -y
RUN npm i puppeteer

# Add a user so you don't need --no-sandbox
RUN groupadd -r pptruser && useradd -r -g pptruser -G audio,video pptruser
RUN mkdir -p /home/pptruser/Downloads
RUN chown -R pptruser:pptruser /home/pptruser
RUN chown -R pptruser:pptruser /node_modules
RUN chown -R pptruser:pptruser /package.json
RUN chown -R pptruser:pptruser /package-lock.json

# Copy your application files
COPY bin/Release/net6.0/publish .

# Set the entry point for your application
ENTRYPOINT ["dotnet", "PupeeterSharpGmailAutomation.dll"]


Q: Can anyone tell me how to solve it?
PS: I am using console app for the automation using puppeteer sharp.

**Comment by mammadovnihad** [comment]
> now aday. You need install these package. so this is the dockerfile need include
> 
> FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim as runtime
> 
> RUN apt-get update && apt-get install -y libx11-6 libx11-xcb1 libatk1.0-0 libgtk-3-0 libcups2 libdrm2 libxkbcommon0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libpango-1.0-0 libcairo2 libasound2 libxshmfence1 libnss3

If you're using App Service for Linux ([Built-in images](https://learn.microsoft.com/en-us/troubleshoot/azure/app-service/faqs-app-service-linux#built-in-images)) without a custom Docker image, you can specify this as the [`Startup Command`](https://learn.microsoft.com/en-us/azure/developer/python/configure-python-web-app-on-app-service) like:

```
sudo apt-get update && \
sudo apt-get install -y \
  libx11-6 \
  libx11-xcb1 \
  libatk1.0-0 \
  libgtk-3-0 \
  libcups2 \
  libdrm2 \
  libxkbcommon0 \
  libxcomposite1 \
  libxdamage1 \
  libxrandr2 \
  libgbm1 \
  libpango-1.0-0 \
  libcairo2 \
  libasound2 \
  libxshmfence1 \
  libnss3 && \
 dotnet path/Project.dll
```
**Azure Portal ref**:

![enter-startup-file-for-app-service-in-the-azure-portal](https://github.com/hardkoded/puppeteer-sharp/assets/30072524/75b53f6a-7a18-440f-b521-217599cf4df7)

**Comment by dev-dilan** [comment]
Args = new string[] { "--no-sandbox" } worked for me both linux and windows

**Comment by daustany** [comment]
This is working for me:

```
FROM mcr.microsoft.com/dotnet/sdk:8.0 as build

WORKDIR /App

COPY . ./

RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0

# Install dependencies for puppeteer
RUN apt-get update && \
    apt-get install -y \
        wget \
        gnupg2 \
        apt-transport-https \
        ca-certificates \
        fonts-liberation \
        libappindicator3-1 \
        libasound2 \
        libatk-bridge2.0-0 \
        libatk1.0-0 \
        libcups2 \
        libdbus-1-3 \
        libgdk-pixbuf2.0-0 \
        libnspr4 \
        libnss3 \
        libx11-xcb1 \
        libxcomposite1 \
        libxdamage1 \
        libxrandr2 \
        xdg-utils \
        libgbm1 \
        libxcb-dri3-0 \
        libxss1 && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /App
COPY --from=build /App/out .
ENTRYPOINT ["dotnet", "YourApp.API.dll"]

```

Make sure changing **YourFileManager.cs**

```
await new BrowserFetcher().DownloadAsync();
var browser = await Puppeteer.LaunchAsync(new LaunchOptions
{
    Headless = true,
    Args = new string[] { "--no-sandbox", "--disable-setuid-sandbox" }
});

```
