### ISSUE TITLE
awating launch just closes and do nothing

### ISSUE THREAD

**Issue by Suresokken** [kblok/puppeteer-sharp#305]
I'm using the code below, when i debug it reaches  `using (var browser = await Puppeteer.LaunchAsync(options, Downloader.DefaultRevision))`

Then it just close down and saves no file. 
What am i missing?
It never reaches and lines after that.

```

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using PuppeteerSharp;
using System.IO;

namespace ConsoleApp {
    class Program {
        public static void Main(string[] args) {
            Task r = Run(args);
        }

        public static async Task Run(string[] args) {
            var options = new LaunchOptions {
                Headless = true
            };

            Console.WriteLine("Downloading chromium");
            await Downloader.CreateDefault().DownloadRevisionAsync(Downloader.DefaultRevision);

            Console.WriteLine("Navigating google");
            using (var browser = await Puppeteer.LaunchAsync(options, Downloader.DefaultRevision))
            using (var page = await browser.NewPageAsync()) {
                await page.GoToAsync("http://www.google.com");

                Console.WriteLine("Generating PDF");
                await page.PdfAsync(Path.Combine(Directory.GetCurrentDirectory(), "google.pdf"));

                Console.WriteLine("Export completed");

                if (!args.Any(arg => arg == "auto-exit")) {
                    Console.ReadLine();
                }
            }
        }
    }
}
```

**Comment by kblok** [comment]
On the other hand, you need to improve your `Main` code. You need to await the Run method.
See: https://github.com/kblok/puppeteer-sharp/blame/c327052cfbe7fbab64dc0d330b4ceb17d01e7dfc/demos/PuppeteerSharpPdfDemo/Program.cs#L13

**Comment by Suresokken** [comment]
After improving code i get this:

System.InvalidOperationException was unhandled
Message: An unhandled exception of type 'System.InvalidOperationException' occurred in mscorlib.dll
Additional information: An attempt was made to transition a task to a final state when it had already completed.

**Comment by Suresokken** [comment]
Wasen't supposed to be closed

**Comment by kblok** [comment]
Could you upload your project (bin included) to some cloud?

**Comment by Suresokken** [comment]
I found another way, so i will close this

**Comment by RyanONeill1970** [comment]
@Suresokken Can you say what you did to work around this? I'm also getting 'An attempt was made to transition a task to a final state when it had already completed.' when calling;

`					using (var page = await browser.NewPageAsync())
`

**Comment by viswa18** [comment]
@Suresokken @RyanONeill1970 
I'm also getting the same exception can you please let me know how to overcome this issue.
