### ISSUE TITLE
Unable to connect to the remote server

### ISSUE THREAD

**Issue by nankingcigar** [kblok/puppeteer-sharp#312]
Excepton screenshot as below. 
Code line causes this exception. Can someone help me to resolve it? Thanks. Maybe I'm at China that cause this issue.
await Downloader.CreateDefault().DownloadRevisionAsync(Downloader.DefaultRevision);
![image](https://user-images.githubusercontent.com/9410343/41027948-db2b332e-6967-11e8-8a74-9a655b994911.png)

**Comment by Meir017** [comment]
Are you having problems accessing the url https://storage.googleapis.com - https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Downloader.cs#L18 ?

**Comment by nankingcigar** [comment]
@Meir017 I can access https://storage.googleapis.com with shadowsocks.

**Comment by nankingcigar** [comment]
@kblok Let me try. Thanks for your comment.

**Comment by nankingcigar** [comment]
Thanks. It's ok for me now.
