### ISSUE TITLE
Chrome process launch fails when Windows user name contains 'special' characters.

### ISSUE THREAD

**Issue by RyanONeill1970** [kblok/puppeteer-sharp#333]
My name on some Windows installations is embedded into the user directory so that it comes out as 

`C:\Users\Ryan O'Neill\AppData\....`

There are two problems here, the space and the apostrophe. I imagine other characters will cause this issue too. When launching Chrome, the process ignores all of the characters past the space and shows this error (via a popup dialogue, visible when headless is turned off);

> Failed to Create Data Directory
> Chromium cannot read or write to its data directory:
> C:\Users\Ryan

This can be rectified in Launcher.cs by amending;
`                    chromeArguments.Add($"{UserDataDirArgument}={options.UserDataDir}");
`
to
`                    chromeArguments.Add($"{UserDataDirArgument}=\"{options.UserDataDir}\"");
`

To reproduce this error, create a Windows user with a space in their name. A lot of the unit tests then fail.

I am happy to provide a pull-request, but thought I would check first.

**Comment by kblok** [comment]
Pull requests are welcome @RyanONeill1970.

Thanks for taking the time to go through the code!
