### ISSUE TITLE
Asp.NET - hangs returning Task Result

### ISSUE THREAD

**Issue by Jojoshua** [kblok/puppeteer-sharp#337]
I am testing this on an ASP.NET MVC application targeting .NET 4.7.1. and using v 1.01 puppeteer-sharp.

A post to the server is initiated and goes to pull the byte[] of the webpage. The code hangs if trying to return the result of a Task. If simply awaiting it works fine.

```
[HttpPost]
       public async Task<ActionResult> IndexAsync(string url)
       {
           //var bytes = await PupeteerPDFDataAsync(url); <------works
           var bytes = PupeteerPDFDataAsync(url).Result; <-------hangs
           return View("Index");
       }

public static async Task<byte[]> PupeteerPDFDataAsync(string url)
        {
            var options = new LaunchOptions
            {
                Headless = true,
                ExecutablePath = HostingEnvironment.MapPath("~/App_Data/.local-chromium/Win32-526987/chrome-win32/chrome.exe")
            };
       
            byte[] result = null;

            var browser = await Puppeteer.LaunchAsync(options, Downloader.DefaultRevision);
            using (var page = await browser.NewPageAsync())
            {
                await page.GoToAsync("http://www.google.com");
                result = await page.PdfDataAsync();
            }
            await browser.CloseAsync();

            return result;
        }

```

**Comment by kblok** [comment]
Thanks for the code example, I'll take a look

**Comment by kblok** [comment]
So regarding this Issue, we do need to use `await` in this context to avoid deadlocks.

**Comment by Jojoshua** [comment]
Is there any way you can think of to not require awaiting? It could cause a lot of propagation.

**Comment by kblok** [comment]
Why don't you want to use `await`? If you are in an async context like ASP.NET MVC you should use `await`.

The demo project uses `GetAwaiter().GetResult()` but a console App is a sync context.
If you want to keep digging and come up with a Pull Request, I can review it.

**Comment by Jojoshua** [comment]
You are probably right for that context. There are however some cases where I want it to stay synchronous.  This seems to work though. This is likely not an issue with puppeteer-sharp.


```
            Task<byte[]> mytask = Task.Run(() => PupeteerPDFDataAsync(url));
            //Wait for task to finish
            mytask.Wait();
            var bytes = mytask.Result;
```
```_

**Comment by kblok** [comment]
You can still do that

```cs
var task = PupeteerPDFDataAsync(url);
await Task.Delay(2000);
var bytes = await task;
return View("Index");
```

**Comment by kblok** [comment]
Any thoughts here @Meir017 ?

**Comment by kblok** [comment]
Making asynchronous code synchronous can be quite problematic. See http://blog.stephencleary.com/2012/07/dont-block-on-async-code.html

I got to this post https://stackoverflow.com/questions/17248680/await-works-but-calling-task-result-hangs-deadlocks and this piece of code will work.

```cs
var bytes = Task.Run(() => PupeteerPDFDataAsync(url)).Result;
return View("Index");
```

**Comment by Meir017** [comment]
I think that `.Result` is different than using `GetAwaiter().GetResult()` - I think it wraps the exception in an `AggregateException` and maybe more things
see https://stackoverflow.com/questions/17284517/is-task-result-the-same-as-getawaiter-getresult#answer-31742125

**Comment by kblok** [comment]
@Jojoshua could you try v1.5?

**Comment by Jojoshua** [comment]
I thought I needed to write my code differently. What changed in 1.5 that might make this work as was written?

**Comment by kblok** [comment]
We apply `ConfigureAwait(false);` across the board.
This should work `var bytes = Task.Run(() => PupeteerPDFDataAsync(url)).Result;`

**Comment by Jojoshua** [comment]
Updated -- It works
