### ISSUE TITLE
Get exception when run page.GetCookiesAsync().

### ISSUE THREAD

**Issue by HopeForToday** [kblok/puppeteer-sharp#343]
### Description

when use page.GetCookiesAsync() method, I'll get exception `OverflowException: 值对于 Int32 太大或太小`. When I create a new project or change target url to a new website, this issue occured again.

![exception](https://user-images.githubusercontent.com/20399569/41828100-e9ef4d02-7865-11e8-9467-c79aa7f2f1f8.png)

### Complete minimal example reproducing the issue

```csharp
var browser = await Puppeteer.LaunchAsync(new LaunchOptions
{
    Headless = false,
    ExecutablePath = @"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",

}, 0);
var page = await browser.NewPageAsync();
await page.GoToAsync("https://www.baidu.com");
var cookies = await page.GetCookiesAsync();
Console.WriteLine(cookies.Length);
```

### Versions

* PuppeteerSharp 1.0.2 via NuGet
* .NET framework 4.6.1

**Comment by kblok** [comment]
Thanks for the code example @HopeForToday. I'll take a look at it.
