### ISSUE TITLE
Implement Page.setUserAgent tests

### ISSUE THREAD

**Issue by kblok** [kblok/puppeteer-sharp#35]
https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/test/test.js#L2419

**Comment by Meir017** [comment]
blocked by #101 since [`server.waitForRequest('/empty.html')`](https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/test/test.js#L2424)

**Comment by kblok** [comment]
@Meir017 did we miss implementing [should emulate device user-agent](https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/test/test.js#L2429) for any reason?

**Comment by Meir017** [comment]
I think I forgot it when I merged the emulate tests with that branch...
