### ISSUE TITLE
Another issue spaces in paths (possibly)

### ISSUE THREAD

**Issue by RyanONeill1970** [kblok/puppeteer-sharp#374]
The basic snapshot example below hangs at 'NewPageAsync' when launched from a user profile with a space in it;
`await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
var browser = await Puppeteer.LaunchAsync(new LaunchOptions
{
    Headless = true
});
var page = await browser.NewPageAsync();
await page.GoToAsync("http://www.google.com");
await page.ScreenshotAsync(outputFile);`

I'm happy to investigate and provide a pull request. If anyone has any ideas where the issue is, that would help.

Would you like me to look at this?

**Comment by kblok** [comment]
I was looking for a related PR. And it turns out that you working on #333

I don't know if it's related to spaces. But yes, I'd gladly review your PR. Let me know if you need a hand.

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.
