### ISSUE TITLE
System.ArgumentException: 'options.Quality is unsupported for the jpeg screenshots'

### ISSUE THREAD

**Issue by drittich** [kblok/puppeteer-sharp#378]
Using the following snippet I get an exception when trying to take a screenshot:

```
await page.ScreenshotAsync(@"c:\tmp\MyScreenshot.jpeg", new ScreenshotOptions
{
	Type = "jpeg",
	Quality = 90
});
```

I'm assuming `Quality` should be an allowed option since the only other format (`png`) is lossless.

I can submit a PR for this if that's helpful.

**Comment by kblok** [comment]
That's true. I feel into the `assert` trap here https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L770

[Here](https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Page.cs#L954) we should fail if the type is `<> "jpeg"` 

You can create a PR for this PR and the other you created.

**Comment by Meir017** [comment]
maybe we could refactor the `ScreenshotOptions.Type` to be an enum?

**Comment by kblok** [comment]
I can also buy that
