### ISSUE TITLE
Explicitly setting file type in ScreenshotAsync should allow custom file extension

### ISSUE THREAD

**Issue by drittich** [kblok/puppeteer-sharp#379]
I get an exception `System.ArgumentException: 'Unknown options.type jpg'`
when doing this:

```
await page.ScreenshotAsync(@"c:\tmp\MyScreenshot.jpg", new ScreenshotOptions
{
	Type = "jpeg"
});
```

I think custom file extensions should be allowed when explicitly setting the `Type`. Alternately, `jpg` could be allowed as an alias for Type `jpeg`.

**Comment by kblok** [comment]
Good point. I'd gladly review your PR. I think we need to do two things Puppeteer is doing [here](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Page.js#L754).

1. If options.Type is set it should take priority over the file extension (as you mentioned)
2. We should get the options.Type not from the file extension but from the Mime type (https://msdn.microsoft.com/en-us/library/system.web.mimemapping.getmimemapping.aspx) inferred from the file name.
