### ISSUE TITLE
Get exception when run page.GetContentAsync()

### ISSUE THREAD

**Issue by victor1135** [kblok/puppeteer-sharp#381]
Hi, when use page.GetContentAsync() method, I'll get exception

> CLR/System.Exception
An exception of type 'System.Exception' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Protocol error (Runtime.callFunctionOn): Session closed. Most likely the page has been closed.'

Here is my simple code
>             
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                ExecutablePath = "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe",
                Headless = true,
                DumpIO = true,
            });
            var page = await browser.NewPageAsync();
            await page.GoToAsync("https://www.google.com.tw/");
            var countGoogle = 0;
            do
            {
                await Task.Delay(3000);
                await page.GetContentAsync();
                countGoogle++;
            } while (true);

the counter will count 5 to 6 times and throw exception

**Versions**
- PuppeteerSharp 1.1.0 via NuGet
- .NET Core 2.1

**Comment by kblok** [comment]
Thanks for the code example @victor1135. I'll take a look.

**Comment by kblok** [comment]
@victor1135 just to double check. Could you try downgrading to .NET Core 2.0?

**Comment by victor1135** [comment]
No problem , I'll try on .NET Core 2.0

**Comment by victor1135** [comment]
Hi @kblok  .NET Core 2.0 operating normally, I run for a hour, no exception

**Comment by kblok** [comment]
Issue https://github.com/dotnet/corefx/issues/31076 created on the corefx repo.
