### ISSUE TITLE
Support for Azure

### ISSUE THREAD

**Issue by raupes** [kblok/puppeteer-sharp#383]
### Description

Trying hole day. Is it possible to run on Azure App Service?
Also when trying to copy installation result from npm install puppeteer to output I still get the error
`Win32Exception: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail`
at this line
`PuppeteerSharp.Launcher.LaunchAsync(LaunchOptions options)`
And I simply can't install chrome there.

Hope you can help or be able how to get this cool project running on azure.

thank you

### Complete minimal example reproducing the issue

          public class HomeController : Controller
    {
        string path;
        public HomeController(IHostingEnvironment hostingEnvironment) {
            this.path = hostingEnvironment.ContentRootPath;
        }
        public async Task<IActionResult> Index()
        {
            bool exist = false;
            using(var browser = await PuppeteerSharp.Puppeteer.LaunchAsync(new LaunchOptions() {
                Headless = true,
                ExecutablePath = this.path + @"\node_modules\puppeteer\.local-chromium\win64-564778\chrome-win32\chrome.exe"
            })) {
                using(var page =await browser.NewPageAsync()) {
                    var response = await page.GoToAsync("http://www.sales-suckers.com");
                    var res = await page.EvaluateExpressionAsync<dynamic>("window.salessuckers");
                    exist = res != null;
                }
            }
            ViewData.Add("EXIST", exist);
            return View();
        }
}

### Expected behavior:

Please add description how to run within Azure App Service or add support to it.

### Versions

* Which version of PuppeteerSharp are you using? 1.1
* Which .NET runtime and version are you targeting? .NET Core 2.0. .NET Core 2.1

**Comment by kblok** [comment]
You won't be able to run chrome on Azure, you'll have to use an external chrome process. I wrote a post about this http://www.hardkoded.com/blogs/azure-chrome-puppeteer-browserless

**Comment by raupes** [comment]
Too bad.
Thanks I need to think about it using browserless - or probably i found an other service for a couple of requests.

thanks!

**Comment by brightertools** [comment]
When you say it won't work in Azure, will Puppeteer-Sharp not run within a .net core web application? Or are talking about Azure Functions, or both?

**Comment by kblok** [comment]
@brightertools I didn't have the time to test it again.
It's not a Puppeteer's limitation. It is an environment limitation. The WebApp or Azure Function should be able to run Chromium and Chromium should have all the CGI components it needs to run.

If you can test it and let us know how it went it would be great.

**Comment by kblok** [comment]
@brightertools cool, Let us know how it goes.

**Comment by PradeepLoganathan** [comment]
I tried to run it in an azure web app and it fails. This is my code 

```C
              var options = new LaunchOptions
                {
                    Headless = true
                };

                await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);

                
                using (var browser = await Puppeteer.LaunchAsync(options))
                using (var page = await browser.NewPageAsync())
                {
                    await page.GoToAsync(htmlurl);
                    document = await page.PdfStreamAsync();
                }

                return document;

It fails on this line  using (var browser = await Puppeteer.LaunchAsync(options)) and I don't even get an exception. The call fails with a 502 invalid gateway error. I was hopeful of using this to generate pdf's :-)

**Comment by kblok** [comment]
@PradeepLoganathan is that a WebApp?

**Comment by drsasankh** [comment]
I have the same issue

**Comment by ravtakhar** [comment]
Ssme issue here can't run it on my web app

**Comment by ravtakhar** [comment]
@kblok are you planning on looking into this? SelectPDF is working fine, but slow and far more limited than this library.

**Comment by kblok** [comment]
@ravtakhar I don't think I will be able to dig into this in the following 30 days.

**Comment by ravtakhar** [comment]
@kblok wondering if we can open this issue again. I tried to take a look, but I think it's a little too over my head.

**Comment by kblok** [comment]
@ravtakhar reopened

**Comment by rytmis** [comment]
I got a little bit further, but still no success.

My code is:

```csharp
    public class PuppeteerRenderer : IPdfRenderer {
        public async Task<byte[]> RenderPdfAsync(string htmlInput)
        {
            var fetcher = new BrowserFetcher(new BrowserFetcherOptions()
            {
                Path = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "Puppeteer")
            });

            await fetcher.DownloadAsync(BrowserFetcher.DefaultRevision);

            var path = fetcher.GetExecutablePath(BrowserFetcher.DefaultRevision);
            
            var options = new LaunchOptions()
            {
                Headless = true,
                ExecutablePath = path
            };

            using (var browser = await Puppeteer.LaunchAsync(options))
            {
                var page = await browser.NewPageAsync();
                await page.SetContentAsync(htmlInput);
                return await page.PdfDataAsync();
            }
        }
    }
```

The only interesting part is the one where I specify the folder for the Chromium download. When attempting this with MVC 5 running locally on IIS Express, I noticed that the default working directory is one where the app can't write, so specifying this helped.

In Azure App Service, though, execution hangs at `await browser.NewPageAsync();` (checked via remote debugging) and eventually the result is a 502. I can see that the Chrome process gets launched, but nothing more than that.

![image](https://user-images.githubusercontent.com/121952/56425025-422a8500-62bb-11e9-8b4b-376bcc0ccb38.png)

**Comment by CREFaulk** [comment]
BrowserFetcher uses Directory.GetCurrentDirectory() to download to but if you are running PuppeteerSharp in a service it'll be something like "C:\Windows\System32".

I added a statement to when my service was starting and gave the service user permissions on the install folder:
System.IO.Directory.SetCurrentDirectory(System.AppDomain.CurrentDomain.BaseDirectory);

**Comment by WernerMairl** [comment]
May be this is a idea to solve this:

https://oren.codes/2018/02/25/registration-free-com-with-azure-app-services/

**Comment by mikecabana** [comment]
Status update? Is this a viable feature?

**Comment by brightertools** [comment]
We are using PuppeteerSharp in Azure (AppService) with the browserless.io service and it works well.

I followed @kblok 's example here: http://www.hardkoded.com/blogs/azure-chrome-puppeteer-browserless

**Comment by kblok** [comment]
Are you looking for something like this?
![image](https://user-images.githubusercontent.com/2198466/63166131-dc010500-c003-11e9-802c-bd10bd3a00cc.png)


Blog post is coming :)

**Comment by lohithdhanakonda** [comment]
I am deploying my application on azure, seems I cannot use BrowserFetcher. (In local anyhow I am using this, sometimes chrome.exe from Program files)
Is there any chance, that we could use chrome.exe file path as the executable path, from the machine, where we have deployed the application. Actually, I don't want to use the remote browser. Instead, can I use the .exe path directly, in Azure?

**Comment by GFoley83** [comment]
Can confirm that it's currently not possible to run Puppeteer on Azure Functions either. You get the same error as raupes:

> System.Private.CoreLib: Exception while executing function: WebPageScanJob. System.Diagnostics.Process: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

![image](https://user-images.githubusercontent.com/838788/64510652-cd71e900-d336-11e9-9aa7-c0570f8d6a76.png)

Which gets trigger as soon as you call:

```csharp
var browser = await Puppeteer.LaunchAsync(new LaunchOptions
{
    Headless = true
});
```
 
Looks like it's a known issue: Azure/azure-functions-host/issues/2417

**Comment by kblok** [comment]
I posted a possible solution here http://www.hardkoded.com/blog/running-puppeteer-sharp-azure-functions

**Comment by Jehoel** [comment]
To my knowledge, Chrome's Headless mode doesn't use the GDI libraries (it's all OpenGL).

I was able to get `chrome.exe` to run by working-around the side-by-side error by running from the `HOME_EXPANDED` directory - I do get some assortment of errors written out of `stderr` and `stdout` but at least it does run.

**Comment by Jehoel** [comment]
@kblok Kinda a cop-out to use a Linux Docker image rather than running in-place within an Azure App Service or Azure Function.

FWIW, I'm able to work-around (fix?) the `winsxs` issue by running `chrome.exe` from the "real" path (not the virtualized `D:\home\...` path), but then the `chrome.exe` process never quits - I haven't done any further investigation, but the fact that `Chrome.exe` is able to start and connect with Puppeteer is encouraging (also it's 4:31am where I am as I write this - so I hope you'll forgive me for not delving deeper).

I first posted my semi-solution to here ( https://github.com/Azure/azure-functions-host/issues/2417 ) but I've replicated it here:

I was able to get `chrome.exe` to run by working-around the side-by-side error by running from the `HOME_EXPANDED` directory - I do get some assortment of errors written out of `stderr` and `stdout` but at least it does run.

For those wondering, do this:

1. Open Kudu's `cmd` prompt in your `D:\home` directory.
2. `echo %HOME_EXPANDED%` (this will print a `C:\...` path)
3. `cd %HOME_EXPANDED%` (nothing will happen, but do it anyway)
4. `c:` (this will put you in your "real" home directory)
5. `site\your-chome-directory\chrome.exe`
6. It is now running - you'll see some `stderr` and/or `stdout` messages printed too. Unfortunately as Kudu doesn't forward `Ctrl+C` (or has any means of killing processes, really) you can't do anything and will need to open a new Kudu window to start again - but it shows that `Chrome.exe`  can be made to start.

**Comment by emilbm** [comment]
> 6\. you'll see some `stderr` and/or `stdout` messages printed too. Unfortunately as Kudu doesn't forward `Ctrl+C` (or has any means of killing processes, really) you can't do anything and will need to open a new Kudu window to start again - but it shows that `Chrome.exe`  can be made to start.

I've just managed to do the same before seeing your comment. I'm getting the same, but everything appears to be working. Have you experienced any issues with this approach of just ignoring the error? Memory-buildup or restarts or anything?

**Comment by GFoley83** [comment]
You can now use Puppeteer on Azure Functions running on Linux:
https://anthonychu.ca/post/azure-functions-headless-chromium-puppeteer-playwright/

The article talks about Node.js but I've tested the code below and it works fine.

```cs
public static async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
    ILogger log)
{
    string url = req.Query["url"];
    url = url ?? "https://google.com";

    var downloadsFolder = Path.GetTempPath(); // Need to use a folder with write permissions. "/tmp/" in Azure 
    log.LogInformation($"downloadsFolder: {downloadsFolder}");

    var browserFetcher = new BrowserFetcher(new BrowserFetcherOptions
    {
        Path = downloadsFolder
    });

    await browserFetcher.DownloadAsync(BrowserFetcher.DefaultRevision);
    var browser = await Puppeteer.LaunchAsync(new LaunchOptions
    {
        Headless = true,
        ExecutablePath = browserFetcher.RevisionInfo(BrowserFetcher.DefaultRevision).ExecutablePath
    });

    var page = await browser.NewPageAsync();
    await page.GoToAsync(url);
    var screenshotStream = await page.ScreenshotStreamAsync(new ScreenshotOptions { Type = ScreenshotType.Png, FullPage = true });

    return new FileStreamResult(screenshotStream, "image/png");
}

```

**Comment by sadidkhan** [comment]
@GFoley83 does the same implementation work on Azure Functions running on Windows also?

**Comment by Jehoel** [comment]
@emilbm  

> Have you experienced any issues with this approach of just ignoring the error?

Honestly, no - I gave up :)

**Comment by GannonTank** [comment]
Any updated for deploy puppeteer in Azure Apps ? (OS version: Microsoft Windows NT 10.0.14393.0)
I execute the API and get the following error:
`[ERR] An unhandled exception has occurred while executing the request. (48a46595)
System.ComponentModel.Win32Exception (203): The system could not find the environment option that was entered.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at PuppeteerSharp.States.ChromiumStartingState.StartCoreAsync(LauncherBase p) in C:\projects\puppeteer-sharp\lib\PuppeteerSharp\States\ChromiumStartingState.cs:line 68`

**Comment by BOBx5** [comment]
> > 이제 Linux에서 실행되는 Azure Functions에서 Puppeteer를 사용할 수 있습니다: https://anthonychu.ca/post/azure-functions-headless-chromium-puppeteer-playwright/
> > 이 글을 쓰는 시점의 소비 계획입니다. 이 글에서는 Node.js에 대해 이야기하지만 아래 코드를 테스트해보니 잘 작동합니다.
> > ```cs
> > public static async Task<IActionResult> Run(
> >     [HttpTrigger(AuthorizationLevel.Anonymous, "get", "post", Route = null)] HttpRequest req,
> >     ILogger log)
> > {
> >     string url = req.Query["url"];
> >     url = url ?? "https://google.com";
> > 
> >     var downloadsFolder = Path.GetTempPath(); // Need to use a folder with write permissions. "/tmp/" in Azure 
> >     log.LogInformation($"downloadsFolder: {downloadsFolder}");
> > 
> >     var browserFetcher = new BrowserFetcher(new BrowserFetcherOptions
> >     {
> >         Path = downloadsFolder
> >     });
> > 
> >     await browserFetcher.DownloadAsync(BrowserFetcher.DefaultRevision);
> >     var browser = await Puppeteer.LaunchAsync(new LaunchOptions
> >     {
> >         Headless = true,
> >         ExecutablePath = browserFetcher.RevisionInfo(BrowserFetcher.DefaultRevision).ExecutablePath
> >     });
> > 
> >     var page = await browser.NewPageAsync();
> >     await page.GoToAsync(url);
> >     var screenshotStream = await page.ScreenshotStreamAsync(new ScreenshotOptions { Type = ScreenshotType.Png, FullPage = true });
> > 
> >     return new FileStreamResult(screenshotStream, "image/png");
> > }
> > ```
> 
> 안녕하세요. 이 솔루션에 감사드립니다. 영어에서는 작동합니다. 동아시아 웹사이트에서 유니코드/동아시아 글꼴을 사용하도록 프로젝트를 만드는 방법을 아는 사람이 있나요?

@nickticket2u  I had to add lines of codes on docker file.

``` dockerfile
RUN apt update -y && apt install -y fonts-noto-core && apt install -y fonts-noto-cjk && fc-cache -fv
```
