### ISSUE TITLE
Dispose method in Page.cs

### ISSUE THREAD

**Issue by Ariex** [kblok/puppeteer-sharp#409]
https://github.com/kblok/puppeteer-sharp/blob/b1fb17ff6cbe15426094c8983c6260553294bb74/lib/PuppeteerSharp/Page.cs#L1766

should it be `public void Dispose() => CloseAsync().Wait();` so when reach the end of the Dispose method, the execution of CloseAsync will guaranteed to be completed?

**Comment by kblok** [comment]
Sadly we can't. Wait would lock the current thread, making the library unable to fulfill it's own promises. 
The best good solution would be waiting for https://github.com/dotnet/csharplang/blob/195efa07806284d7b57550e7447dc8bd39c156bf/proposals/async-streams.md#iasyncdisposable

In the meantime, if the causes you some issue, the solution would be avoiding `using` blocks and closing the Pages explicitly, using `await page.CloseAsync();`

**Comment by Ariex** [comment]
thanks, i have not encounter any issue with this, just happen to see that when I searching in the code.

it is great to learn something new~
