### ISSUE TITLE
how to change default download behavior to "deny"?

### ISSUE THREAD

**Issue by Ariex** [kblok/puppeteer-sharp#410]
### Description
In puppeteerjs, this can be done as below:
``` javascript
const puppeteer = require('puppeteer');

(async () => {
    const browser = await puppeteer.launch({headless: false});
    const page = await browser.newPage();
    await page._client.send('Page.setDownloadBehavior', {
        behavior: 'deny'
    });
    await page.goto("https://s.codepen.io/boomerang/iFrameKey-ece752a2-192a-1f85-b63f-199176b096d4/index.html");
})();
```

But when I tried to do the following:
``` C#
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);

var browser = await Puppeteer.LaunchAsync(new LaunchOptions
{
    Headless = false
});
var page = await browser.NewPageAsync();

var clientProp = page.GetType().GetTypeInfo().GetDeclaredProperty("Client");
var client = clientProp.GetValue(page) as CDPSession;
var method = client.Connection.GetType().GetTypeInfo().GetDeclaredMethod("SendAsync");
await (Task)method.Invoke(client.Connection, new object[]{"Page.setDownloadBehavior", new {
    behavior = "deny"
}});

var resp = await page.GoToAsync("https://s.codepen.io/boomerang/iFrameKey-50c549ef-bab1-2043-847e-1fef0eac751c/index.html");
```
I cannot get same result.

I have checked the JSON stringified message at [Connections.cs@90](https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Connection.cs#L90), compare it against [Connections.js@191](https://github.com/GoogleChrome/puppeteer/blob/master/lib/Connection.js#L191), i got same string as `{"id":12,"method":"Page.setDownloadBehavior","params":{"behavior":"deny"}}`

So, any idea why this is not working? And how to fix it?

I have found #172 but in my case, the response type is document, so I cannot simply "Abort" document request.

I am using the latest version of puppeteer-sharp 1.1.0, with dot net core 2.1.300

Thanks very much

**Comment by Ariex** [comment]
oh, one more thing, the test code for the download page is in here: https://codepen.io/Ariex/pen/BPNBLr
the url in the description does not last long, you might need to either create a local page with the code as in the pen, or refresh it then get the url of the preview panel... sorry for the inconvenience

**Comment by Ariex** [comment]
this get fixed, i dived too deep..
```C#
var clientProp = page.GetType().GetTypeInfo().GetDeclaredProperty("Client");
var client = clientProp.GetValue(page) as CDPSession;
var m = client.GetType().GetTypeInfo().GetDeclaredMethods("SendAsync").ElementAt(1) as MethodInfo;
await (Task)m.Invoke(client, new object[]{"Page.setDownloadBehavior", new {
    behavior = "deny"
}});
```

**Comment by kblok** [comment]
Create created #411 so we can expose that API call.

**Comment by kblok** [comment]
@Ariex Just a late comment here. Now SendAsync exposes the SendAsync method, you can use it without reflection.

**Comment by Ariex** [comment]
@kblok thanks very much, this is awesome!
