### ISSUE TITLE
Hang when creating PDF

### ISSUE THREAD

**Issue by spib** [kblok/puppeteer-sharp#414]
### Description
Exporting as PDF hangs and never completes. I've tried the following combinations

* BrowserFetcher.DefaultRevision (543305) and the current puppeteer version (571375)
* Platform.Win32 vs Platform.Win64
* It works if I run \Win64-571375\chrome-win32\chrome.exe --headless --disable-gpu "https://*******.com" --print-to-pdf
* It works if I run via puppeteer, see below

````javascript
const puppeteer = require('puppeteer');

require('console-stamp')(console, '[HH:MM:ss.l]');

(async () => {
    console.log('Launching Browser');

  const browser = await puppeteer.launch();
  
  console.log('Opening new page');
  const page = await browser.newPage();
  console.log('Navigating to https://*******.com');
  await page.goto('https://*******.com', {waitUntil: 'networkidle2'});
  console.log('Exporting PDF');
  await page.pdf({path: 'proposal.pdf', format: 'A4'});
  console.log('Closing browser');
  await browser.close();
  console.log('Fin');
})();
````

I can give you the url I am testing with but would rather do that privately if possible.

### Complete minimal example reproducing the issue

```csharp
    class Program
    {
        static void Main( string[] args )
        {
            MainAsync( "https://*******.com",
                "c:\\temp\\test\\output.pdf",
                10 * 60 ).GetAwaiter().GetResult();
        }

        static async Task MainAsync( string url, string fullPath, int timeoutSeconds )
        {
            const int revision = 571375; 

            // Download Chromium if we don't already have it
            Console.WriteLine( $"Downloading Chromium version {revision}" );

            var downloader = new BrowserFetcher( new BrowserFetcherOptions()
            {
                Path = "c:\\temp\\test",
                Platform = Platform.Win32
            } );
            await downloader.DownloadAsync( revision );

            // Launch it
            Console.WriteLine( $"Launching Chromium version {revision}" );
            var browser = await Puppeteer.LaunchAsync( new LaunchOptions
            {
                Headless = true, // Print to PDF only works when headless (and we want headless anyway)
                ExecutablePath = downloader.GetExecutablePath( revision )
            } );

            // Navigate to the url and print to PDF
            Console.WriteLine( $"Navigating to url {url}" );
            var page = await browser.NewPageAsync();
            await page.GoToAsync( url, timeoutSeconds > 0 ? timeoutSeconds * 1000 : 0 );

            Console.WriteLine( $"Writing PDF to file {fullPath}" );
            await page.PdfAsync( fullPath );

            Console.WriteLine( $"Closing page" );
            await page.CloseAsync();

            Console.WriteLine( $"Closing Chromium" );
            await browser.CloseAsync();

            Console.WriteLine( $"Finished writing PDF to file" );
        }
    }
```

### Expected behavior:

Export the pdf and exit

### Actual behavior:

Gets are far as 'Writing PDF to file ...' and then never completes. I can see 6 instances of chrome.exe running in task manager

### Versions

PuppeteerSharp 1.2
.NET 4.6.2 Full Framework

**Comment by kblok** [comment]
Thanks for all the details @spib. I'll take a look at it.

**Comment by viswa18** [comment]
I'm also getting the same issue, when using below code snippet.

**MainAsync( "https://*******.com", "c:\\temp\\test\\output.pdf",10 * 60 ).GetAwaiter().GetResult();**

The same MainAsync works fine if I use await and async in the calling method. But I want to use a code snippet like a above one. But it getting hangs, can you please check and let me know is there any possibilities to overcome this.

**Comment by kblok** [comment]
@viswa18 `GetAwaiter().GetResult()` might be locking the thread, making puppeteer unable to process callbacks.
Maybe #525 could solve this issue but I strongly suggest you to use `await`.

**Comment by viswa18** [comment]
@kblok  Thank you for your update. 
Adding ConfigureAwait in the provided code snippet is not working.

Is there any other way to overcome this?

**Comment by kblok** [comment]
Yes, using the await keyword

**Comment by viswa18** [comment]
I have tried the below code snippet, but this also does not work. 

            Thread thread = new Thread(async () => await MainAsync(url, outputPath));
            thread.Start();
            thread.Join();

**Comment by kblok** [comment]
Could you try Task.Run?
https://msdn.microsoft.com/en-us/library/hh195051(v=vs.110).aspx

**Comment by viswa18** [comment]
I tried but does not works, Socket class has synchronous connect, send, receive method. Is it possible to use **Socket** instead of **ClientWebSocket** to perform the conversion?

**Comment by kblok** [comment]
Puppeteer is asynchronous by nature. You send a message to chormium and eventually you get one or many messages back.

Let’s wait for the next version (we added ConfigureAwait in all our awaits) and we’ll see if that helps you.

**Comment by viswa18** [comment]
@kblok Thank you. When will be the next version available. 

Socket has class API's than ClientWebSocket class, is there any reason to use ClientWebSocket for conversion.

**Comment by kblok** [comment]
I can get you a version in a week. You could try building master locally and see if it works.

ClientWebSocket had everything we need to do the job.

**Comment by viswa18** [comment]
Okay thanks for your update. I'll check this with next version.

**Comment by kblok** [comment]
@viswa18 could you try v1.5?
