### ISSUE TITLE
BrowserFetcher: download through a proxy

### ISSUE THREAD

**Issue by rgruebel** [kblok/puppeteer-sharp#432]
Hello,
at the moment I have to download and unpack the browser myself.
browserFetcher.DownloadAsync fails in my ASP.net Application because I am behind a proxy.
Can you please implement something like this:
`            
var browserFetcher = new BrowserFetcher(new BrowserFetcherOptions
 {
     Path = TEMP_PATH,
     PROXY = new WebProxy(PROXY_URL) { UseDefaultCredentials = true };
 });
`
Then we can use this proxy for the webclient.

**Comment by rgruebel** [comment]
I just found out I can set System.Net.WebRequest.DefaultWebProxy

**Comment by kblok** [comment]
I'd like to know how we can make it testable.

Ideas @Meir017 ?

**Comment by Meir017** [comment]
Adding a redirect on the simpleserver to download the file?
