### ISSUE TITLE
Can't set DeviceScaleFactor in ViewportOptions

### ISSUE THREAD

**Issue by sruchot** [kblok/puppeteer-sharp#434]
In some situation (to get better quality of snapshot / currently text is blurry), the DeviceScaleFactor parameters has to be set. Currently it's read-only without a set option.

Is there any reason for this one to be read only without an ability to set it ?

**Comment by kblok** [comment]
It makes sense. In fact, it's an issue.
It should be public https://github.com/kblok/puppeteer-sharp/blob/52181695a5486c95ea03dfe8da77d7bc9acb3ecf/lib/PuppeteerSharp.Tests/InputTests/InputTests.cs#L505

As we have `internals visible to tests` set we missed that.  You'll get that in the next version.

**Comment by sruchot** [comment]
Thanks for this quick anwser.

Looking forward to it
