### ISSUE TITLE
LaunchAsync - Not working code just hangs

### ISSUE THREAD

**Issue by vinayhfs** [kblok/puppeteer-sharp#512]
Hi 

I am just trying demo code in my project. Code just hangs at line 
   await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);

I am on windows 7 ,Visiual studio 2017. installed nuget version 1.4.0

I trying generated pdf in .net core 2.0.6 web api method.

**Comment by kblok** [comment]
We had some reports here about that https://github.com/kblok/puppeteer-sharp/issues/90#issuecomment-407046241

The internals of the the WebSocket class is not implemented on Windows 7
https://stackoverflow.com/questions/11039438/using-websocket-on-windows-7

**Comment by fernandobelo** [comment]
I'm having the same problem here. Win 10 OK, Server 2008R2 NOK.

Anyone used https://github.com/PingmanTools/System.Net.WebSockets.Client.Managed ? It is supposed to be a drop-in replacement for System.Net.WebSockets, as it implements the abstract classes from it. 

Still haven´t got the chance to try, if it works, would remove a lot of work from changing the code to use websocket-sharp for example.

**Comment by ggeurts** [comment]
I am working on pull request that uses the System.Net.WebSockets.Client.Managed NuGet package.

**Comment by kblok** [comment]
@ggeurts that project doesn't look so active...

**Comment by ggeurts** [comment]
It defaults to the regular ClientWebSocket usage unless it throws a Platform or supported option in which case it falls back to a port of Microsoft's managed WebSocket implementation.

**Comment by ggeurts** [comment]
Pull request #574 introduces a Puppeteer extension point that enables use of custom WebSocket implementations. I have used this extension point in combination with the https://github.com/PingmanTools/System.Net.WebSockets.Client.Managed implementation to run Puppeteer successfully on Windows 2008 R2.

**Comment by Ariex** [comment]
just for record, this is how it make works for me:
``` C#
var browser = await Puppeteer.LaunchAsync(new LaunchOptions
{
	WebSocketFactory = (uri, socketOptions, cancellationToken) =>
	{
		return System.Net.WebSockets.SystemClientWebSocket.ConnectAsync(uri, cancellationToken);
	},
	Headless = true
});
```
