### ISSUE TITLE
PuppeteerSharp.MessageException: 'Protocol error (Page.captureScreenshot): Invalid parameters quality: integer value expected'

### ISSUE THREAD

**Issue by Goregakalack** [kblok/puppeteer-sharp#514]
Having issues taking a screenshot for a webpage.

```csharp
using (var page = await browser.NewPageAsync())
{
	await page.GoToAsync("https://google.co.uk");
	
	var screenShotStream = await page.ScreenshotStreamAsync(new ScreenshotOptions()
	{
		Type = ScreenshotType.Jpeg,
		Quality = 10,
	});
}
```

ScreenshotStreamAsync throws the following exception 

PuppeteerSharp.MessageException: 'Protocol error (Page.captureScreenshot): Invalid parameters quality: integer value expected'

I took a look at the Connection.cs and I beleive the problem is when the args which contains the 'Quality' is being serlized incorrectly due to its type of 'decimal?', this is what the JSON being sent looks like.

{"id":16,"method":"Target.sendMessageToTarget","params":{"sessionId":"2685512079E3207FCE7D4251753A1FFF:1","message":"{\"id\":13,\"method\":\"Page.captureScreenshot\",\"params\":{\"format\":\"jpeg\",\"quality\":10.0}}"}}

I guess changing the quality type to an interger type of somekind will fix the issue?

**Comment by kblok** [comment]
Good catch!
We’ll get that fixed for next version.
