### ISSUE TITLE
I cannot get images stored locally to be rendered in generated png Image with PuppeteerSharp

### ISSUE THREAD

**Issue by mconsoro** [kblok/puppeteer-sharp#528]
string  HtmlCode = <img style="width:70px; height:70px" src="Car01.png"

var page = await browser.NewPageAsync();
            await page.SetContentAsync(HtmlCode);
                var result = await page.GetContentAsync();
            await page.SetViewportAsync(new ViewPortOptions { Width = 910, Height = 2050 });
But external images for which I specify a url not work(are not visible).

**Comment by kblok** [comment]
Could you share a working example?
The first line won’t compile.

**Comment by mconsoro** [comment]
Hello friend, the project is here: https://github.com/mconsoro/PuppeteerSharpTest
Thanks for the attention.

**Comment by kblok** [comment]
@mconsoro thanks for sharing your code.
So, if you inject the html in a new page, all the paths in that HTML will be relative to `about:blank`, and your image won’t be there.
But you could navigate a local html file and it should work as expected. See this test: 
https://github.com/kblok/puppeteer-sharp/commit/b187eb10995dc859e7cac90ad4acfc1f303fd8c6#diff-a13099aecd47be13bb9cbeeab0f29fc1R407

**Comment by mconsoro** [comment]
@kblok  very thanks, it was very easy, now work.
