### ISSUE TITLE
Using authenticated proxy server

### ISSUE THREAD

**Issue by danhastings** [kblok/puppeteer-sharp#535]
Couldn't find anything specific in the documentation for this C# implementation, but I was able to find some code here  https://stackoverflow.com/questions/48084554/puppeteer-with-crawlera-proxy

I can't seem to get it to work though. I have a string list to store the args for puppeteer . The proxy server is the only argument i am passing in.

```
if (request.proxy != null)
    browserargs.Add("--proxy-server = " + request.proxy.Uri.ToString());
				
var browser = await Puppeteer.LaunchAsync(new LaunchOptions
{
    Headless = true,
    Args = browserargs.ToArray() 
});
```

I am then passing the proxy password and username over like the answer suggested. 
```
await page.SetExtraHttpHeadersAsync(new Dictionary<string, string>() {
{ "Proxy-Authorization", "Basic " + 
    Convert.ToBase64String(Encoding.UTF8.GetBytes(request.proxy.Username + ":" + request.proxy.Password)) }
});
```

If i load up whatsmyip.org it returns a response but its my local IP not an IP from the proxy. Any idea what I amn doing wrong here?

**Comment by kblok** [comment]
Could you try removing the spaces before and after the equal here `—proxy-server = `?

**Comment by danhastings** [comment]
It looks like it has done something as it is finding there is a proxy now, but it is throwing an exception.

net::ERR_NO_SUPPORTED_PROXIES at http://www.whatsmyip.org/ at http://www.whatsmyip.org/

**Comment by kblok** [comment]
Try using the authenticate method. See this example in node https://gist.github.com/jancurn/ecf3f04aea3c245498e06a913ce54115#file-puppeteer-proxy-page-authenticate-js

**Comment by danhastings** [comment]
The issue seems to come from the argument that is passed into chrome. I tried using authenticate and i tried removing it completely. Even without passing a username and password into the request, it fails with the same error. I also tried using a different proxy service and I still get the same issue
