### ISSUE TITLE
Payload class is internal - how then to perform request interception

### ISSUE THREAD

**Issue by christianacca** [kblok/puppeteer-sharp#537]
### Description

I'm trying to set a http header for the initial request to a target webpage. I tried using `SetExtraHttpHeadersAsync` but that appears not to be it's intended use (ie it passes the header to *all* requests that the target web page is making)

I then tried to use request interception as per one of the [unit test](https://github.com/kblok/puppeteer-sharp/blob/aa6470f61ab167b1525ebb74468811f386736b79/lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs#L154). However I can't use this method due to the `Payload` class and it's `Headers` property being marked as internal.

Am I missing some other method of achieving this? Otherwise, can these symbols be made public?

Thanks
Christian

**Comment by kblok** [comment]
Good catch!

**Comment by christianacca** [comment]
Thanks for the fix
