### ISSUE TITLE
SetViewportAsync is not working in PDF Generation

### ISSUE THREAD

**Issue by viswa18** [kblok/puppeteer-sharp#576]
set viewport aync is not working in PDF generation, but working as expected in ScreenshotAsync. Can anyone please check this and let me know Is there any possibilities to getting this worked.

**Comment by kblok** [comment]
I don't Viewport won't apply on PDF generation because it works as a Print command, ergo it will use the `@media print` media query rather than the screen media query.

**Comment by viswa18** [comment]
Is there any workaround to getting this worked? I need this feature in PDF generation, it is working as expected in screenshot.

**Comment by kblok** [comment]
Are you emulating a device or an specific screen size?
Is the site yours or is it an external site?

**Comment by viswa18** [comment]
@kblok  yes, it is an external sites. 
I have tried to set viewport in both Print and Screen media in PDF generation, but it does not works as expected.

**Comment by viswa18** [comment]
Any update for this? Is there any way to getting this worked for save as PDF?

**Comment by kblok** [comment]
@viswa18 what ViewPort are you setting? A code example would be helpful.

**Comment by viswa18** [comment]
@kblok Below is the example code which I have tried. 

 ```
using (var browser = await Puppeteer.LaunchAsync(options))
            using (var page = await browser.NewPageAsync())
            {
                ViewPortOptions viewPortOptions = new ViewPortOptions();
                viewPortOptions.Width = 1920;
                await page.SetViewportAsync(viewPortOptions);
                await page.GoToAsync("http://www.google.com");
                string guid = Guid.NewGuid().ToString();
                Console.WriteLine("Generating PDF");
                await page.PdfAsync(Path.Combine(Directory.GetCurrentDirectory(), guid + ".pdf"));

                Console.WriteLine("Export completed");
            }
```

**Comment by kblok** [comment]
@viswa18 uses [@media](https://developer.mozilla.org/en-US/docs/Web/CSS/@media) print. And the PDF size will be based on the [PageFormat](https://www.puppeteersharp.com/api/PuppeteerSharp.PdfOptions.html#PuppeteerSharp_PdfOptions_Format) you set. 

It is basically the same as "Print to PDF" in Chrome. It will be based on the page size you pick.

**Comment by hermanho** [comment]
I have the similar problem. It seems it is related to this issue.
https://github.com/GoogleChrome/puppeteer/issues/1183#issuecomment-383722137

I could use the trick as below previously.
```csharp
var client = await page.Target.CreateCDPSessionAsync();
await client.SendAsync("Emulation.clearDeviceMetricsOverride");
```
However, the change https://github.com/kblok/puppeteer-sharp/pull/581 prevents the trick and there is no launch argument "defaultViewport".
https://github.com/GoogleChrome/puppeteer/commit/25632133e2683c613c97d9088968c48e3c07a086

**Comment by kblok** [comment]
That's Interesting @hermanho. `defaultViewport` will be delivered on v1.7 https://github.com/kblok/puppeteer-sharp/issues/565

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.

**Comment by kevinah95** [comment]
> @kblok Below is the example code which I have tried.
> 
> ```
> using (var browser = await Puppeteer.LaunchAsync(options))
>            using (var page = await browser.NewPageAsync())
>            {
>                ViewPortOptions viewPortOptions = new ViewPortOptions();
>                viewPortOptions.Width = 1920;
>                await page.SetViewportAsync(viewPortOptions);
>                await page.GoToAsync("http://www.google.com");
>                string guid = Guid.NewGuid().ToString();
>                Console.WriteLine("Generating PDF");
>                await page.PdfAsync(Path.Combine(Directory.GetCurrentDirectory(), guid + ".pdf"));
> 
>                Console.WriteLine("Export completed");
>            }
> ```

You can set the PdfOptions.Width and PdfOptions.Height:

```c#
var browser = await Puppeteer.LaunchAsync(options);
using (var page = await browser.NewPageAsync())
{
    //Remove these three lines:
    //ViewPortOptions viewPortOptions = new ViewPortOptions();
    //viewPortOptions.Width = 1920;
    //await page.SetViewportAsync(viewPortOptions);
    await page.GoToAsync("http://www.google.com");
    string guid = Guid.NewGuid().ToString();
    Console.WriteLine("Generating PDF");
    await page.PdfAsync(Path.Combine(Directory.GetCurrentDirectory(), guid + ".pdf"), 
                                                      new PdfOptions() // <----- Add this
                                                      { 
                                                          Width = 1920, 
                                                          Height = 1080
                                                      });

  Console.WriteLine("Export completed");
}
```
