### ISSUE TITLE
Implement CSS coverage tests

### ISSUE THREAD

**Issue by kblok** [kblok/puppeteer-sharp#58]
https://github.com/GoogleChrome/puppeteer/blob/v1.0.0/test/test.js#L3604

**Comment by PhenX** [comment]
They split their tests, this is the new URL : https://github.com/GoogleChrome/puppeteer/blob/master/test/coverage.spec.js#L100

**Comment by kblok** [comment]
@PhenX I changed the link to honor the v1.0 which is our first goal. Then we'll move to v1.1 and v1.2 until we catch them.
