### ISSUE TITLE
Support convenience env variables

### ISSUE THREAD

**Issue by kblok** [kblok/puppeteer-sharp#608]
https://github.com/kblok/puppeteer/pull/11/commits/28d92116b7072d43665c4e7b964e0e27167a9053

Review all env variables in used on Puppeteer.

**Comment by kblok** [comment]
Regarding these extra Env variables. Those are being use by `npm install` I think we don't need them.

- `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY` - defines HTTP proxy settings that are used to download and run Chromium.
- `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` - do not download bundled Chromium during installation step.
- `PUPPETEER_DOWNLOAD_HOST` - overwrite host part of URL that is used to download Chromium

**Comment by Meir017** [comment]
makes sense

**Comment by ahmadalli** [comment]
so isn't it possible to use `http_proxy` env for putting puppeteer-sharp behind proxy?

**Comment by kblok** [comment]
@ahmadalli Proxy support for BrowserFetcher was implemented exposing a Proxy property here https://github.com/kblok/puppeteer-sharp/pull/1205.
You can pass a proxy to Chromium using the `Args` argument. This is on example in NodeJS https://github.com/GoogleChrome/puppeteer/blob/4c48b77503112c876fc5f907888f5a91a2095aff/examples/proxy.js#L26, but it will work in .NET
