### ISSUE TITLE
Avoid dynamic requires in lib/ folder

### ISSUE THREAD

**Issue by kblok** [kblok/puppeteer-sharp#610]
Review code changes in this commit https://github.com/kblok/puppeteer/pull/11/commits/f230722ff0e9d0a10913a74a00febfec522bcbee

**Comment by kblok** [comment]
@Meir017 I would like you to double check that we don't need to implement this:

 *  `projectRoot` in `BrowserFetcher` constructor. They are just cascading `__dirname` from [here](https://github.com/kblok/puppeteer/commit/f230722ff0e9d0a10913a74a00febfec522bcbee#diff-168726dbe96b3ce427e7fedce31bb0bcR30) `Directory.GetCurrentDirectory()` does the job for us.
* `Launcher` constructor. 
    * Same with `projectRoot`. 
    * `preferredRevision` they are grabbing that from a Json file, we don't have that, and as they say, each Puppeteer version is tied to a Chromium revision, so I think we are not wrong there. 
    * `isPuppeteerCore` We don't have to packages as they do.

**Comment by Meir017** [comment]
I don't think we need this.
This is exactly what I don't like about nodejs... 😉
