### ISSUE TITLE
Getting ElementHandle of Parent Node

### ISSUE THREAD

**Issue by danhastings** [kblok/puppeteer-sharp#614]
I use QuerySelectorAllAsync() to get a list of elements and loop over them. I need to get the parent node of each of these records. If i debug, I can see that element.RemoteObject has a reference to Parent. This is a json reference though and does not seem to have any binding to the dom. I need to obtian the parent as if it were a regular ElementHandle node so that i can do things like figure out how many children it has and what its parent is etc.

```
var elements =  await page.QuerySelectorAllAsync(selector);

foreach(var element in elements)
{
	var parent = await page.EvaluateFunctionAsync("(element) => {return element.parentNode}", element);
	var parent2 = await page.EvaluateFunctionAsync<ElementHandle>("(element) => {return element.parentNode}", element);
}
```

With the example here, parent is set to a JObject. It isnt much use in this form though as I cant access any dom properties of methods for this node. If i try to cast it to an ElementHandle for parent2, it doesnt work. The result is just null. 

Performing calls like `page.EvaluateFunctionAsync<string>("(element) => {return element.nodeName}", element);` work just fine, so the node object seems to be ok. There is just an issue turning the response for the parent node into something that is usable.

**Comment by kblok** [comment]
Take a look a this test https://github.com/kblok/puppeteer-sharp/blob/61629746823b0921fa8ea84fc3169acd2d7e70b3/lib/PuppeteerSharp.Tests/ElementHandleTests/EvaluateFunctionTests.cs#L50

It shows how from a `.tweet` it navigates to a list of `.like`,  and then gets the `innerText`

**Comment by danhastings** [comment]
Rather than needing the parent html i need the parent element itself. I had a look at the source code for QuerySelectorAll and tried to copy what this method was doing. It worked for the parent node and children node if i copied how both of those method execute code. 

```
var handle = await page.EvaluateFunctionHandleAsync("(element) => element.parentNode", elementHandle).ConfigureAwait(false);
if (handle is ElementHandle element){
    ElementHandle parenthandle = (ElementHandle)handle;
}
```
