### ISSUE TITLE
How to close the chrome process when software close and terminate the main process ?

### ISSUE THREAD

**Issue by anirudhagupta** [kblok/puppeteer-sharp#627]
I write a basic hello world code using this library and it looks good to me.  I am interested in a scenario in case my process terminates and chrome still running. 

I close my software and chrome running, I see there is CloseAsync method which I can use to call the instance. In some case, if my software crash or someone close the process from Task Manager what will be an option for close.

Is there anything like setting parent process, so whenever my software exit (crash, closed or terminated by anything) the chrome process will also be exited.

Thanks

**Comment by kblok** [comment]
We have a test trying to verify that https://github.com/kblok/puppeteer-sharp/blob/583b240c6604a599de3584e5fe44953fd672c729/lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs#L295

Could you try to play with that and tell us how we can improve that test?
