### ISSUE TITLE
WS connection not kept alive

### ISSUE THREAD

**Issue by kokovtsev** [kblok/puppeteer-sharp#629]
It seems that the WS connection is reset by Chromium because the connection is not kept alive by PuppeteerSharp. I found that this piece of configuration was commented out - was that made intentionally? Even though we now have the ability to customize the connection factory, I believe that keep-alive would be a convenient default setting...

https://github.com/kblok/puppeteer-sharp/blob/d8a35cb7329755fab8df76b9c6a28f9ab5820746/lib/PuppeteerSharp/Connection.cs#L290

**Comment by kblok** [comment]
@kokovtsev that line is commented because Chromium doesn't support pings yet. 
See: https://bugs.chromium.org/p/chromium/issues/detail?id=865002

**Comment by kblok** [comment]
Could you explain your use case scenario?
Are you actively using chromium for 3 minutes? are you leaving the browser opened in a variable?

**Comment by kokovtsev** [comment]
Browser instance is stored in a singleton service's private field, so it's kept in memory for the whole app lifetime. At arbitrary moments of time (on incoming http requests), I call `NewPageAsync` on that browser instance, do something with the page and close it. After a couple of minutes since the app startup, `NewPageAsync` starts failing with the `Protocol error (Target.createTarget): Target closed.`.
This does not seem to depend on the using activity - sometimes I can create multiple pages before the disconnect, sometimes I can't create even one.

By the way, I just tried providing a custom `WebSocketFactory` which sets `Options.KeepAliveInterval` to `0` and that did the trick - no more disconnects (or at least not that often ones)

**Comment by kblok** [comment]
Let's do something. Confirm that fixed the issue in 24 hours (or so) and I'll make a PR with that.

**Comment by kblok** [comment]
@kokovtsev can you confirm this fixes the issue?

**Comment by kokovtsev** [comment]
Hi Darío,
Yes, setting `KeepAliveInterval` to `0` worked fine for me, the connection on my test environment has been stable for a day now
Thank you!
