### ISSUE TITLE
Cannot render manual set html content as pdf correctly (SetContentAsync)

### ISSUE THREAD

**Issue by essmd** [kblok/puppeteer-sharp#632]
**Before you file a bug, have you:**

* [x] Tried upgrading to newest version of PuppeteerSharp, to see if your issue has already been resolved and released?
* [x] Checked existing open *and* closed [issues](https://github.com/kblok/puppeteer-sharp/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* [x] Tried reproducing your problem in a new isolated project?
* [x] Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/search?q=puppeteer-sharp).

### Description

When `SetContentAsync(string html)` is called, the content will be set correctly, but there is no way to detect/wait for something like "document ready". When i run the snippet below, i have the following results:

1. Breakpoint at `PdfDataAsync`, wait 1-2s, continue -> **The expected and pixel perfect PDF**
2. Breakpoint after `PdfDataAsync` or no breakpoint at all -> **An empty/white PDF**
3. Attaching event handler on `Load` Event and await those event to fire -> **Partial rendered PDF**

### Complete minimal example reproducing the issue
```csharp
// Arrange
var options = new LaunchOptions { Headless = true };
var browser = await Puppeteer.LaunchAsync(options, BrowserFetcher.DefaultRevision);

var html = System.IO.File.ReadAllText(@"C:\invoice.html");
var page = browser.NewPageAsync();
var pageLoadFired = new TaskCompletionSource<bool>();

page.Load += (sender, args) =>
{
    Console.WriteLine("Loaded");
    pageLoadFired .SetResult(true);
};

// Act
await page.SetContentAsync(html);
// await pageLoadFired.Task; // uncomment this, for test case 3

var data = await page.PdfDataAsync(new PdfOptions
{
    Format = PaperFormat.A4,
    PrintBackground = true,
    MarginOptions = new MarginOptions
    {
        Left = "1cm",
        Right = "1cm",
        Top = "1.5cm",
        Bottom = "1.5cm"
    }
});

// Assert
Assert.Equal(41564, data.Length); // 1. 877 Bytes -- 2.  

// Result Case #1 - Breakpoint, wait 1-2s before RenderData = 41564 bytes - perfect!
// Result Case #2 - Breakpoint after RenderData or no BP at all = 877 bytes - white/empty page
// Result Case #3 - Uncomment and await pageLoadFired.Task = 5823 bytes - partial loaded/rendered
```

### Expected behavior:

Either the await of `SetContentAsync` completes when everything is "finished" and ready to "render" or anything else, or some way to wait for the document to be ready. Something like jQuerys `$(document).ready(...)`. The best i found was the "Load" EventHandler no "Ready" EventHandler or something like that.

### Actual behavior:

No way to wait and ensure the document loading process to be finished. Its only possible by wait an random/high amount of time and hope the time/delay was long enought (await Task.Delay(5000)).
If the Network Request in the HTML file requires more than the 5000ms because of network load etc., it will be rendered wrong again.

### Versions

* Which version of PuppeteerSharp are you using? **Latest, 1.6.2**
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0. **Latest, .NET Core 2.1.4 (Runtime) and 2.1.402 (SDK)**

### Additional Information

My example was created in a fresh and clean/new webapi project (dotnet new webapi).
I attached the source HTML file and some screenshots of the results.
Am i missing something or is this an behavior that should/can be improved?

I have also tried to solve the issue with WaitForNavigateAsync with many combinations of events, before and after SetContentAsync and also with Task.WhenAll etc. But WaitForNavigate results in timeouts because no navigation is happening at all (due to SetContent and not GoTo).

Thanks!!

**Source of the input**
[invoice.html](https://github.com/kblok/puppeteer-sharp/files/2394972/invoice_html.txt)

**Screenshots of all three cases (PDF Results)**
[Output Case 1](https://user-images.githubusercontent.com/4410142/45724382-27255480-bbb6-11e8-8e16-b0f767d1dd29.png)
[Output Case 2](https://user-images.githubusercontent.com/4410142/45724383-27bdeb00-bbb6-11e8-809c-5183c6f7e7b9.png)
[Output Case 3](https://user-images.githubusercontent.com/4410142/45724384-27bdeb00-bbb6-11e8-8bb4-05ca3218fca4.png)

**Comment by kblok** [comment]
@essmd could you try waiting for any element in that HTML?
e.g.
```cs
await Page.WaitForSelectorAsync("DIV")
``` 
or
```cs
await Page.WaitForSelectorAsync(".some-class-your-are-injecting")
```

**Comment by essmd** [comment]
What the hell yes! I have not tried WaitForSelectorAsync because i thought it will only give me ElementHandles for my selector, and yes, since DOMDocumentReady fired, and even the Load-Event, it will find the Element...

But yes, its just working fine! Event the `@font-face: src(...)` requests will finishe before the Task completes. Thats amazing!

No i dont like it to query for something in the HTML, because i can not garantuee its always the same. So i tried to query for "body" which should be available always. And yes again, it works!!

Maybe this should be mentioned somewhere in the docs/readme? Just a note / hint or something? I think most people are using GoTo(..) which works fine, but SetContent - this would be a massive time saver.

Thank you for the solution and sorry for the "non issue". I gave my best to not open this issue but i thought i tried everything ... thanks!!


**Working Code:**
```csharp
await page.SetContentAsync(html);
await page.WaitForSelectorAsync("body");

var buffer = await page.PdfDataAsync(new PdfOptions { ... });
```

**Comment by kblok** [comment]
Could you try adding this?
```cs
await Page.WaitForNavigationAsync(new NavigationOptions { WaitUntil = new[] { WaitUntilNavigation.Networkidle0 } });
```
>Consider navigation to be finished when there are no more than 2 network connections for at least 500ms

**Comment by essmd** [comment]
I already tried, this (it was my first attempt) because it is exactly what i want to achive.
The thing is, it results in an timeout (there is an configurable option for an timeout after 30s). Timeout occurs because there never happens an navigation (which does when calling GoToUrl -> where it works!).
No navigation -> waiting forever.
I think  this is an issue / missing feature in the puppeteer "core" ?

Thanks for the support and help! Cheers!

**Comment by LamboJ** [comment]
I've run into the same issue and the workaround I've found is to inject code into the html to set a flag when the page is loaded. It's not pretty, but it works for now. If I have some time, I'll look to implement a proper page.WaitForPageLoadedAsync()

I've added the following into my html:
`<script>window.onload  = function() { window.IsPageLoaded= true; };</script>`

And then in my C# code I have:
`await page.WaitForExpressionAsync("window.IsPageLoaded");`

**Comment by kblok** [comment]
How about `WaitUntilNavigation.Load`?
https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/WaitUntilNavigation.cs#L11

**Comment by chevenel** [comment]
I have the same problem. Adding `WaitUntilNavigation.Load` increases the processing time by at least 30 seconds in my project, which is odd since, if I save the html I'm generating to a flatfile and open that in Chrome, it takes half a second to finish loading.

**Comment by kblok** [comment]
Closing this issue. @essmd feel free to reopen it if you think there is something to be done here.

**Comment by brechtvhb** [comment]
I've had this issue too.
The workaround of @LamboJ fixes it, it feels quite hacky though ..

**Comment by rkthompson3** [comment]
@LamboJ 's fix worked for me too. Thanks a lot.

**Comment by kevinah95** [comment]
> I've run into the same issue and the workaround I've found is to inject code into the html to set a flag when the page is loaded. It's not pretty, but it works for now. If I have some time, I'll look to implement a proper page.WaitForPageLoadedAsync()
> 
> I've added the following into my html:
> `<script>window.onload = function() { window.IsPageLoaded= true; };</script>`
> 
> And then in my C# code I have:
> `await page.WaitForExpressionAsync("window.IsPageLoaded");`

Thanks a lot @LamboJ
