### ISSUE TITLE
Managed memory leak in Connection.cs

### ISSUE THREAD

**Issue by tommymonk** [kblok/puppeteer-sharp#640]
It seems as though entries in the _callbacks dictionary of Connection.cs are never removed.

This causes a managed leak of memory eventually resulting in OOM.
The leak is most pronounced with larger callback data.

```cs
var fetcher = new BrowserFetcher();

await fetcher.DownloadAsync(BrowserFetcher.DefaultRevision);

var browser = await new Launcher().LaunchAsync(new LaunchOptions()
{
    Headless = true,
});

while (true)
{
    await browser.GetVersionAsync();
}
```

**Comment by Meir017** [comment]
@kblok 
looks like we need to remove the callback from the dictionary here - https://github.com/kblok/puppeteer-sharp/blob/6a0bdf109caabb7a2b36cfda5eda0da2cf053369/lib/PuppeteerSharp/Connection.cs#L241

we should also add a test for this, maybe something that just called the `GetVersionAsync` method many times

**Comment by kblok** [comment]
Good catch @tommymonk
