### ISSUE TITLE
Falling back to float when serializing of JavaScript 'number'

### ISSUE THREAD

**Issue by tommymonk** [kblok/puppeteer-sharp#650]
I have code that calls EvaluateExpressionAsync in order to return a value, the value can be an object or primitive so I don't specify the 'T', which defaults to "object". I do this so that I can later choose how to represent the value as string.

The issue I have is that ValueFromRemoteObject defaults to a floating point number if the 'T' isn't int32/64.

```cs
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);

var browser = await new Launcher().LaunchAsync(new LaunchOptions
{
    Headless = true,
});

var page = await browser.NewPageAsync();

var javascript = "<html><body><script type=\"text/javascript\">var obj = { \"int64\": 11111111111111 };</script></body></html>";

await page.SetContentAsync(javascript);

var result = await page.EvaluateExpressionAsync("obj.int64"); // result is System.Single

var str = Convert.ToString(result); // str is 1.111111E+13

browser.Dispose();
```

There needs to be some kind of intelligent numeric type detection such as the ParseReadNumber used by Newtonsoft Json.Net so that my result is an integer.

**Comment by Meir017** [comment]
change to
```cs
var longResult = await page.EvaluateExpressionAsync<long>("obj.int64");
```
works  after updating the `RemoteObjectHelper` class
![image](https://user-images.githubusercontent.com/9786571/46144264-11bec300-c265-11e8-8999-378fb5b6c5ef.png)

although it doesn't fix the `page.EvaluateExpressionAsync("obj.int64");` case

@kblok does this make sense?

**Comment by kblok** [comment]
I agreed with that @Meir017.
@tommymonk can't you convert that `Single` to the value you need?

**Comment by tommymonk** [comment]
The issue is that my calling code doesn't know what the resulting type will be, it may be an entire object or just a primitive, I need to continue with 'object', there is some code later that decides how to represent the result based on it's type, but because the value is coming back as the wrong type, it falls over.

I don't consider it correct behavior that an integer is being returned as floating point.

`var obj = { a:111111 }`

In the above case a selector of `page.EvaluateExpressionAsync("obj")` would return as integer but `page.EvaluateExpressionAsync("obj.a")` would not.

**Comment by Meir017** [comment]
the js type `Number` represents more than just the C# `int`

**Comment by tommymonk** [comment]
Yes, which is why I suggested sophisticated detection is needed.

I think a quick win here as you're already using Json.Net would be something like;

`return JValue.Parse(objectValue).ToObject<T>()`

This would handle all of the detection for you and should be quite performant.

**Comment by Meir017** [comment]
and we should really deprecate/remove the `dynamic` overload, it's a source of weird bugs

**Comment by kblok** [comment]
@tommymonk What you could do is returning a JSHandle and then check it's properties https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp.Tests/JSHandleTests/GetPropertiesTests.cs#L15

If the object has the property you need, you call `JsonValueAsync<int>` of that property, if not, you call `JsonValueAsync<int>` of the same object.

**Comment by kblok** [comment]
@Meir017 but I don't know to play "smart". I'd rather provide tools for the users to do what they need to do.

**Comment by Meir017** [comment]
the correct way is to use the generic overload

**Comment by tommymonk** [comment]
That decision is yours to take, I believe it will push unnecessary complexity out into the consumers' code.

Other libraries I've used that handle the lower-level Runtime.evaluate such as [chrome-dev-tools-runtime](https://github.com/BaristaLabs/chrome-dev-tools-runtime) simply let Json.Net handle the RemoteObject without issue.

**Comment by kblok** [comment]
@tommymonk feel free to submit a PR. I know there is room for improvements there.

**Comment by tommymonk** [comment]
If I get time later this evening I'll have a go at forking and cutting back some of the dynamic to make things like this easier.
