### ISSUE TITLE
Nice project

### ISSUE THREAD

**Issue by Sicos1977** [kblok/puppeteer-sharp#67]
Hi,

I just ran across your project, I did make something similar but then just to convert HTML to PDF.

You can find my project over here  --> https://github.com/Sicos1977/ChromeHtmlToPdf

My goal was just to make something that could replace wkHtmlToPdf

Greetings,
Kees van Spelde

**Comment by kblok** [comment]
That's cool Kees! I will definitely take a look at that. I started Puppeteer Sharp for the same reason: wkHtmlToPdf 😝 . But I got excited about the puppeteer project and here I am.

**Comment by Sicos1977** [comment]
I like the way how you have made everything async and the way you handle the communication with Chrome (with the callback system). I also thought about making something like that but decided it was a little bit overkill because I just wanted to do HTML to PDF conversions. It was also harder to keep everything synchronized that way.

**Comment by kblok** [comment]
That was quite a challenge, but to be honest, I just followed the original Puppeteer idea.

I want to take a look at your code because there are some many messages going back and forward between the client and chromium itself that I like to know what's the minimum communication needed to print a PDF file.

**Comment by Sicos1977** [comment]
I borrowed some of your code .... the connection class... hope you don't mind.

**Comment by kblok** [comment]
No worries @Sicos1977, next beer is on you.

**Comment by Sicos1977** [comment]
:-) 👍

**Comment by Sicos1977** [comment]
Where you from if I may ask? Netherlands over here...

**Comment by Sicos1977** [comment]
The reason why I'm trying out your connection class is because I used supersocket and websocket from nuGet but that one always fails after a while. So I'm trying to figure out if it is an Chrome thinghie or that component.
