### ISSUE TITLE
Having issues with ExposeFunction and timeout

### ISSUE THREAD

**Issue by casperah** [kblok/puppeteer-sharp#684]
**Before you file a bug, have you:**

* Tried upgrading to newest version of PuppeteerSharp, to see if your issue has already been resolved and released?
* Checked existing open *and* closed [issues](https://github.com/kblok/puppeteer-sharp/issues?utf8=%E2%9C%93&q=is%3Aissue), to see if the issue has already been reported?
* Tried reproducing your problem in a new isolated project?
* Considered if this is a general question and not a bug?. For general questions please use [StackOverflow](https://stackoverflow.com/search?q=puppeteer-sharp).

### Description

[Description of the issue]

### Complete minimal example reproducing the issue

Complete means the code snippet can be copied into a unit test method in a fresh C# project and run.
Minimal means it is stripped from code not related to reproducing the issue.

E.g.
``

// Act
...

// Assert
...
```

### Expected behavior:

[What you expect to happen]

### Actual behavior:

[What actually happens]

### Versions

* Which version of PuppeteerSharp are you using?
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by casperah** [comment]
Sorry if the things looks a little strange, but the interaction of mac and remote desktop to pc is very problematic once in a while.

The problem is that PuppeteerSharp raises some TargetClosedExceptions that causes my app to close, but it does not hit my try-catch.

Also having issues with TimeoutExceptions that is shown in the Output on a windows PC.  Not sure if they cause other problems.

The included Program.cs contains info on how to see the problems.

**Comment by casperah** [comment]
The Program.cs file:

`using System;
using System.Threading.Tasks;
using PuppeteerSharp;
using System.Diagnostics;

namespace PuppeteerTest
{
    class Program
    {
        // GIT Commit id: 7c29c545a49fb0c891fcf92d041ee8669ac65cc3  message: v1.8 docs (#665)


        // The problem is that it raises a lot of unhandled TargetClosedExceptions that I am unable to handle
        // And some odd TimeoutExceptions that I can see in output.


        // You can change LoopCount if needed.
        // On my computer:
        // LoopCount = 1000 gives _callbacks.Count = 0
        // LoopCount = 10000 gives _callbacks.Count around 3000
        // LoopCount = 20000 gives _callbacks.Count around 12000
        private static readonly int LoopCount = 10000;
        private static readonly int ReportCount = 10;
        private static readonly int ReportModulus = LoopCount / ReportCount;
        static void Main(string[] args)
        {
            try
            {
                // Please, only enable one test as a time.

                // Insert a breakpoint in CPDSession.OnClose and check number of _callbacks 
                RunCallbacks().Wait();

                // Timeout handling has some issues
                // Please check: https://stackoverflow.com/questions/4238345/asynchronously-wait-for-taskt-to-complete-with-timeout
                // Using windows check Output for TimeoutExceptions
                RunTimeout().Wait();
            }
            catch (Exception e)
            {
                // Note that this catch do not catch TargetClosedExceptions even though they terminate the application.
                Console.WriteLine(e);
            }
            Console.WriteLine("Press any key");
            Console.ReadKey();
        }


        private static async Task RunTimeout()
        {
            var fetcher = new BrowserFetcher();
            await fetcher.DownloadAsync(BrowserFetcher.DefaultRevision);
            var executable = fetcher.GetExecutablePath(BrowserFetcher.DefaultRevision);

            using (var browser = await Puppeteer.LaunchAsync(new LaunchOptions { ExecutablePath = executable, Args = new string[0], }))
            {
                using (var page = await browser.NewPageAsync())
                {
                    Stopwatch watch = new Stopwatch();
                    watch.Start();
                    page.DefaultNavigationTimeout = 100000;
                    for (var i = 0; i < LoopCount; i++)
                    {
                        if (i % ReportModulus == 0)
                        {
                            Console.WriteLine($"Navigating {i}  - {watch.ElapsedMilliseconds}ms");
                            watch.Restart();
                        }
                        await page.GoToAsync("about:blank", new NavigationOptions { });


                    }
                }

            }

        }
        private static async Task RunCallbacks()
        {
            var fetcher = new BrowserFetcher();
            await fetcher.DownloadAsync(BrowserFetcher.DefaultRevision);
            var executable = fetcher.GetExecutablePath(BrowserFetcher.DefaultRevision);

            using (var browser = await Puppeteer.LaunchAsync(new LaunchOptions { ExecutablePath = executable, Args = new string[0], }))
            {
                using (var page = await browser.NewPageAsync())
                {
                    await page.ExposeFunctionAsync<string, bool>("extractData", ExtractData);

                    await page.AddScriptTagAsync(new AddTagOptions { Type = "text/javascript", Content = $"function test() {{ for(var i = 0; i < {LoopCount}; i++) extractData(i); }};" });

                    await page.EvaluateFunctionAsync("test");
                }
            }

        }

        private static bool ExtractData(string data)
        {
            var number = int.Parse(data);
            if ((number % ReportModulus) == 0)
                Console.WriteLine($"Extracted {data}");
            return true;
        }
    }
}
`

**Comment by Meir017** [comment]
@casperah btw, when you post a C# snippet use
![image](https://user-images.githubusercontent.com/9786571/46616067-6e9e6100-cb22-11e8-9bfd-bd17809378cb.png)
so highlight it as C#

** I edited your post :)

**Comment by casperah** [comment]
thanks, now I know

**Comment by casperah** [comment]
Okay, close and comment did not close the form, but the entire issue, I really have a lot to learn about git hub

**Comment by kblok** [comment]
@casperah I was able to reproduce the issue. I'm looking into it.

**Comment by kblok** [comment]
I had fun finding this bug @casperah. Thanks for the the project example 👍

**Comment by casperah** [comment]
looking forward for the release
