### ISSUE TITLE
Failed to load Chromium

### ISSUE THREAD

**Issue by DrEight** [kblok/puppeteer-sharp#685]
I guess that this is a very basic problem, but reading the documentation I can not figure out.
I receive this exception testing the first example in the read me: 
Failed to launch Chromium! [1008/192332.096:ERROR:resource_bundle.cc(815)] Failed to load d:\tests\HeadlessChrome\HeadlessChrome\bin\Debug\.local-chromium\Win64-588429\chrome-win32\resources.pak

what am I missing ?

**Comment by danhastings** [comment]
I am getting the same issue "Failed to launch chrome! path to executable does not exist". I have checked and i can see "Win64-588429" exists in the local chromium folder. The exception is being thrown to say it cant find ".local-chromium\Win64-549031\chrome-win32\chrome.exe".

There must be a bug in here somewhere that isnt referencing the correct version

**Comment by kblok** [comment]
Could you try removing your `.local-chromium` folder @DrEight ?

**Comment by DrEight** [comment]
yes it worked. Thanks!

**Comment by hey-hoho** [comment]
I publised my project to centos7,now throw `PuppeteerSharp.ChromiumProcessException: Failed to launch Chromium!` What can I to do?
