### ISSUE TITLE
Execute function by Proxy

### ISSUE THREAD

**Issue by gethunt** [kblok/puppeteer-sharp#688]
Hi,

I'm cruling sites on daily basic.
Lately there are many sites that blocking my IP, I'm using PhantomJS and there is an option to use proxy, this solved the issue.

I want to move from PhantomJS to Headless Chrome, but I can see there is not proxy support, so I can't reach sites like asos.

I can reproduce this proxy blocking, 
Do you have a plan when it going to be implement?

Thanks

**Comment by danhastings** [comment]
Proxy support is already there. https://github.com/kblok/puppeteer-sharp/issues/535

**Comment by gethunt** [comment]
The proxy still not working, I tryed his answer.

here is my code:

            string temp = "";
            WebClient client = new WebClient();
            client.Encoding = System.Text.Encoding.UTF8;


            var options = new LaunchOptions
            {
                Headless = true                
            };

            if (useProxy)
            {
                Uri uri = new Uri("https://www.asos.com");
                 proxy = ProxyUtils.Instance.getProxy(uri);

                List<string> browserArgs = new List<string>();
                string proxyVal = String.Concat("--proxy-server=", proxy.Key, ":", proxy.Value);
                browserArgs.Add(proxyVal);
                options.Args = browserArgs.ToArray();
            }

            Console.WriteLine("Downloading chromium");
            await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);            

            Console.WriteLine("Navigating google");
            using (var browser = await Puppeteer.LaunchAsync(options))
            using (var page = await browser.NewPageAsync())
            {
                var response = await page.GoToAsync("https://www.asos.com/prettylittlething/prettylittlething-square-neck-body/prd/9782436?clr=white&SearchQuery=&cid=4167&gridcolumn=2&gridrow=1&gridsize=4&pge=1&pgesize=72&totalstyles=5593&affid=10607&pubref=1171&transaction_id=1023bfea1128361b88bfcc6f3689d7");               

                if(response.Status == HttpStatusCode.Forbidden && !useProxy)
                {
                      //Forbidden status
                   
                    return;

                }

**Comment by danhastings** [comment]
Do you need to pass a password and username? Most proxys for scraping require authentication. This can be done using a header, often "Proxy-Authorization". You can also use `Page.AuthenticateAsync(credentials);` to send the username and password over

**Comment by gethunt** [comment]
just wrong proxy, now it's working.
