### ISSUE TITLE
LaunchAsync hangs on Ubuntu

### ISSUE THREAD

**Issue by esotery** [kblok/puppeteer-sharp#696]
### Description:

Hi there,

I am trying to get the puppeteer sharp to run on Ubuntu.

Made a sample console app with the minimal sample to download a screenshot.

When I run it on my WIn 10 computer, works just fine.

When I run in on the Ubuntu, it hangs during the LaunchAsync.

### Sample:

               _logger.LogInformation("Start");
                var info = await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
                _logger.LogInformation($"Version {info.Revision} downloaded {info.Downloaded} to {info.ExecutablePath}");
                var browser = await Puppeteer.LaunchAsync(new LaunchOptions
                {
                    Headless = true,
                }, _loggerFactory);
                _logger.LogInformation("Browser launched");
                var page = await browser.NewPageAsync();
                await page.GoToAsync("http://www.google.com");
                _logger.LogInformation("Page downloaded");
                _logger.LogInformation($"Saving to {Environment.GetFolderPath(Environment.SpecialFolder.Personal)}");
                await page.ScreenshotAsync(Path.Join(Environment.GetFolderPath(Environment.SpecialFolder.Personal), "example.png"));

### Expected behavior:

Puppeteer is launched and the screenshot is downloaded.

### Actual behavior:

Puppeteer hangs.

### Versions

Puppeteer version: 1.4.0
.NET version: .NET core 2.1
Ubuntu version: Ubuntu 18.04.1 LTS

Thank you for your help.

**Comment by kblok** [comment]
@esotery Linux support is almost there. https://github.com/kblok/puppeteer-sharp/pull/430
We just need some help having Linux tests running on AppVeyor. Any help is welcome.

**Comment by esotery** [comment]
I haven't realized it only runs on Windows. I thought linux it has all the prerequisites needed (.NET standard, WebSockets) 

Anything I can do to help?

**Comment by kblok** [comment]
It runs on Mac. But we agreed that in order to say that it works on Linux we need to have tests proving that.

Every time I said "Hey let's do it once for good" I got stuck trying to create the self-signed certificate for the site to run in HTTPS. See https://github.com/kblok/puppeteer-sharp/blob/master/appveyor.yml#L22.

If you are willing to try to get it running, send me an email, or join Slack and I can set up a Linux Project in AppVeyor and walk you through the process.

**Comment by kblok** [comment]
Closing because we know there are some stuff to do to guarantee Linux support
