### ISSUE TITLE
Get an HTML element

### ISSUE THREAD

**Issue by malves** [kblok/puppeteer-sharp#708]
Hi,

I am trying to get all <a> elements in a loaded page, to do that I tried the following query selector:

ElementHandle[] elements = await page.QuerySelectorAllAsync("a");

How can I then extract the "href=" property of each element ? I would like to get all URLs but I don't see how I can do it. I tried to call GetPropertiesAsync(); on each element but I don't see where I can find the element properties.

Thank you very much

**Comment by kblok** [comment]
I would do this instead:
```cs 
EvaluateExpressionAsync<string[]>("Array.from(document.querySelectorAll('a')).map(a => a.href);");
```

**Comment by malves** [comment]
@kblok thank you very much I appreciate your help.

Just for my information, is it possible to get the same result by calling page.QuerySelectorAll("a") and doing something with the result ?

Thank you

**Comment by kblok** [comment]
@malves Not with `QuerySelectorAll` but you could do this with `QuerySelectorAllHandleAsync` which returns a `JSHandle` that points to that array on Chromium.

```cs
await page.QuerySelectorAllHandleAsync("a").EvaluateFunctionAsync<string[]("elements => elements.map(a => a.href)");
```

My first approach uses only one call to chromium, whereas this second approach needs two calls. Any method using `QuerySelectorAllAsync` would involve X + 1 calls (being X the number of elements).

**Comment by malves** [comment]
Perfect, thank you for this explanation :) Let me know if I can help you in anyway
