### ISSUE TITLE
Lack of thread safety causes lock-up

### ISSUE THREAD

**Issue by tommymonk** [kblok/puppeteer-sharp#714]
The following code demonstrates issues with thread-safety of the internals.
When running this, you experience a lock-up of one or both threads.
Whilst this is a contrived example, we've experienced these permanent halts in execution of multi-threaded code.
Due to it's async nature, it was very difficult to debug and get to the root cause of this issue

```
static async Task Main(string[] args)
{
    await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
    var browser = await Puppeteer.LaunchAsync(new LaunchOptions());
    var page = await browser.NewPageAsync().ConfigureAwait(false);

    async Task doWork(string math, int expected)
    {
        while (true)
        {
            var result = await page.EvaluateExpressionAsync<int>(math).ConfigureAwait(false);

            if (result != expected)
                throw new ApplicationException();
            else
                Console.WriteLine($"{math} = {expected}");
        }
    }

    await Task.WhenAll(doWork("1+1", 2), doWork("2+2", 4));
}
```
The minimum changes I've found needed to ensure this example run smoothly are;

- Replace pre-increment of integer in `Connection.cs`, `WaitTask.cs` and `CDPSession.cs` e.g. `++_lastId` to `Interlocked.Increment(ref _lastId)`
- Replace non thread-safe `Dictionary<>` usage with `ConcurrentDictionary<>` in `Connection.cs` and `CDPSession.cs`

**Comment by kblok** [comment]
Not the first time I get the suggestion to switch to ConcurrentDictionaries.
Go for it @tommymonk. The CI will show us how it performs.
