### ISSUE TITLE
SlowMo prevents the page from loading

### ISSUE THREAD

**Issue by DominicBoettger** [kblok/puppeteer-sharp#716]
### Description

As soon as SlowMo = 100 is used the page is not loading at all anymore.

### Complete minimal example reproducing the issue

```csharp
using (Browser browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = false,
                Args =  new[] { "--no-sandbox", "--disable-setuid-sandbox" },
                SlowMo = 100
            }))
await page.EvaluateOnNewDocumentAsync(setIsServer);
                        await page.SetRequestInterceptionAsync(true);
                        page.Request += (sender, e) =>
                        {
                            string resType = e.Request.ResourceType.ToString();
                            if (resType == "Image" || resType == "Font")
                            {
                                e.Request.AbortAsync();
                            } else
                            {
                                e.Request.ContinueAsync();
                            }
                        };
string content = await page.GetContentAsync();
```

### Expected behavior:

That the site loads but just with the SlowMo functionality.

### Actual behavior:

The site does not render at all.

### Versions

* PuppeteerSharp 1.8.0
* .NET core 2.1

**Comment by kblok** [comment]
@DominicBoettger  I coded this test and it's working https://github.com/kblok/puppeteer-sharp/commit/b5dd5aa859825570ef64397e4d2459766e674118

Could you help me break it?

**Comment by kblok** [comment]
Closed due to inactivity. Feel free to reopen it if needed.

**Comment by ismaeldcom** [comment]
I was going to open a new issue but I think it's the same problem.

### Description
The test in b5dd5aa859825570ef64397e4d2459766e674118 passes well but if you do something more *advanced* it always fails.

### Example
```csharp
LaunchOptions options = new LaunchOptions {
    Headless = false,
    SlowMo = 100
};
using (Browser browser = await Puppeteer.LaunchAsync(options))
using (Page page = await browser.NewPageAsync()) {
    await page.GoToAsync("https://duckduckgo.com/");
    ElementHandle input = await page.WaitForSelectorAsync("#search_form_input_homepage");
    await input.TypeAsync("Lorem ipsum dolor sit amet.");
}
```

### Expected behavior:

Load duckduckgo and type with delay.

### Actual behavior:

The next two errors randomly
`csharp PuppeteerSharp.NavigationException: 'Navigation failed because browser has disconnected!`
`PuppeteerSharp.WaitTaskTimeoutException: 'waiting for selector '#search_form_input_homepage' failed`

### Versions

* PuppeteerSharp 1.14.0
* .NET framework 4.7.2

**Comment by ChrisWongAtCUHK** [comment]
Set **SlowMo** to 1000, there is exception:
_PuppeteerSharp.NavigationException: Timeout Exceeded: 30000ms exceeded_

https://github.com/ChrisWongAtCUHK/PuppetTest

**Comment by kblok** [comment]
@ChrisWongAtCUHK can you create a new issue?

**Comment by Sergio1C** [comment]
The issue may still exists: https://github.com/hardkoded/puppeteer-sharp/issues/1897#issuecomment-1093907986
