### ISSUE TITLE
Issue with Puppeteer.Launch on IIS

### ISSUE THREAD

**Issue by taz4270** [kblok/puppeteer-sharp#730]
Hello I have an issue when I try to use `Puppeteer.LaunchAsync` at IIS, Everything but this line of code is Ok, so i dont know what is the problem in specific terms, I just know that it throws a `System.AggregateException` with the message "ChromiumProcessException: Failed to launch Chromium!". Im probably missing some information about how to do it, and i tried to find in every corner, until now, no solution found
### Description
TLDR;  Using `Puppeteer.LaunchAsync` on IIS, throws `System.AggregateException` with the message "ChromiumProcessException: Failed to launch Chromium!".

### Code
I made an extension for `PuppeteerSharp`, so i could get synchronous methods, but it worked as it should work.

**MainClass**

```csharp
BrowserFetcher browserFetcher = new BrowserFetcher(new BrowserFetcherOptions()
    {
        Path = HostingEnvironment.MapPath("~/App_Data/")
    });
browserFetcher.Download(BrowserFetcher.DefaultRevision);
Browser browser = PuppeteerExt.Launch(new LaunchOptions()
{
    Headless = true,
    ExecutablePath = browserFetcher.GetExecutablePath(BrowserFetcher.DefaultRevision)
});
Page page = browser.NewPage();
page.GoTo("https://www.algardata.com",60000);
return page;
```

**My Extension `PuppeteerExt`**

```csharp
public static Browser Launch(LaunchOptions options)
{
     return Task.Run(() => PrivateLaunch(options)).Result;
}
private static Task<Browser> PrivateLaunch(LaunchOptions options)
{
    try
    {
        return Puppeteer.LaunchAsync(options);
    }
    catch (Exception e)
    {
        throw e;
    }
}
```

###Note:
If you say "It's probably your extension's method that is causing that is causing the Exception." It isn't.
I mean, if it crashes on Launch, why doesn't crash before in my others extension methods like `browserFetcher.Download` or `browser.NewPage
` ?

### Expected behavior:

Return the Page

### Actual behavior:

Expection on `Puppeteer.LaunchAsync`

### Versions

* Which version of PuppeteerSharp are you? PuppeteerSharp 1.9.0
* Which .NET runtime and version are you targeting? .NET framework 4.7.1
 ### Adittional Content
![image](https://user-images.githubusercontent.com/44700489/47914828-de410b00-de98-11e8-8162-4ee28e23f84d.png)

**Comment by taz4270** [comment]
Like I said, I created an extension, they contain E.g : `browserFetcher.Download(BrowserFetcher.DefaultRevision);` contains `browserFetcher.DownloadAsync(BrowserFetcher.DefaultRevision);` inside, and it waits, as I intended.

Now for `~/App_Data/` it's already unzipped.
![location](https://user-images.githubusercontent.com/44700489/47915732-b0a99100-de9b-11e8-8b62-ffb29f31ebd3.PNG)

**Comment by kblok** [comment]
Cool then. A few more things to check:
 * What's `browserFetcher.GetExecutablePath(BrowserFetcher.DefaultRevision)` returning?
 * Does that file exists?
 * If you run that chrome manually it works?
 * Does the IIS User has permissions to execute that app?

**Comment by taz4270** [comment]
- "C:\Users\joao.rodrigues\source\repos\ClassLibrary1\HeadlessAPI\App_Data\Win64-594312\chrome-win\chrome.exe"
- Yes
- Somehow, in that exact path, it is Not but on the other it is working, i will try to delete them and try to see the interaction
- I don't know, i'm new at IIS, i'm curious to try new things

**Comment by taz4270** [comment]
Somehow, when i removed the chromium files and reinstall them, it works, now it is working, Feel free to contact me if you want to make synchronous methods from your asynchronous methods, Thank you 👍

**Comment by kblok** [comment]
Awesome!

**Comment by kulesshhh** [comment]
Hello @kblok  , 
I was facing the same issue earlier which somehow got resolved on its own after re-deployment to IIS. But now, I am facing another issue where puppeteer is launching in headless mode only, even when i have specified "Headless = false".

Can you help me with this.

Thanks

**Comment by LojainHassan** [comment]
await new BrowserFetcher().DownloadAsync();
                    var browser = await Puppeteer.LaunchAsync(new LaunchOptions
                    {
                        Headless = true,
                        ExecutablePath = @"C:\inetpub\wwwroot\Chrome\Win64-127.0.6533.88\chrome-win64\chrome.exe"
                    }).ConfigureAwait(false);


                    using var page = await browser.NewPageAsync();
                  
                    await page.SetContentAsync(fileContent);
                    page.DefaultTimeout = 0;
                    await page.PdfAsync(pdfFilepath, new PdfOptions
                    {
                        MarginOptions = {
                Top= "100px",
                  Left= "50px",
                 Bottom= "80px",
                  Right= "50px"
                 },
                        DisplayHeaderFooter = true,
                        HeaderTemplate = cc,
                        FooterTemplate =bb,
                        
                        Format = PuppeteerSharp.Media.PaperFormat.A5  // Specify the paper format (optional)
                    }).ConfigureAwait(false);
when publish to iis doesnt work

**Comment by kblok** [comment]
@kulesshhh @LojainHassan You might need to fix the browser's permissions. [See](https://pptr.dev/troubleshooting/#chrome-reports-sandbox-errors-on-windows)

**Comment by LojainHassan** [comment]
@kblok I dont where this excatly ? is in chrome itself?

**Comment by kblok** [comment]
@LojainHassan Are you sure that the browser is downloaded in `C:\inetpub\wwwroot\Chrome\Win64-127.0.6533.88`?
Why are you forcing the executable path?

**Comment by LojainHassan** [comment]
@kblok  yes it downloaded successfully and
**** I already put  C:\inetpub\wwwroot\Chrome\Win64-127.0.6533.88\chrome.exe    as executable path

**Comment by LojainHassan** [comment]
Is must to specify chrome.exe or not ? @kblok

**Comment by kblok** [comment]
If you are doing `await new BrowserFetcher().DownloadAsync();`, you shouldn't need to set the executable path. Could you remove the executable path?

**Comment by LojainHassan** [comment]
No I dont remove ,   
await new BrowserFetcher().DownloadAsync();
                    using var browser = await Puppeteer.LaunchAsync(new LaunchOptions
                    { 
                        Headless =true 

                    });

**Comment by LojainHassan** [comment]
do I need to remove any thing ? @kblok

**Comment by kblok** [comment]
What do you get if you remove the `ExecutablePath`?

**Comment by LojainHassan** [comment]
from My code I still have problem @kblok  but the file it self still in my project files @kblok

**Comment by kblok** [comment]
@LojainHassan just to confirm. What's exactly the problem?

**Comment by kblok** [comment]
Could you run this in the server?

```
C:\inetpub\wwwroot\Chrome\Win64-127.0.6533.88\setup.exe --configure-browser-in-directory="C:\inetpub\wwwroot\Chrome\Win64-127.0.6533.88"
```

**Comment by LojainHassan** [comment]
the path is wrong because there is folder called : chrome-win64 @kblok

**Comment by LojainHassan** [comment]
C:\inetpub\wwwroot\Chrome\Win64-127.0.6533.88\chrome-win64\setup.exe --configure-browser-in-directory="C:\inetpub\wwwroot\Chrome\Win64-127.0.6533.88

**Comment by kblok** [comment]
@LojainHassan The setup folder must be the same as the `configure-browser-in-directory` flag, and must be the same as the one you are passing.
Again, you shouldn't be setting the `ExecutablePath`

**Comment by LojainHassan** [comment]
@kblok  I didn't but I still have problem , the path for command to run is wrong because there's a folder you doesn't mention it

**Comment by LojainHassan** [comment]
folder called : chrome-win64 @kblok

**Comment by kulesshhh** [comment]
> @kulesshhh @LojainHassan You might need to fix the browser's permissions. [See](https://pptr.dev/troubleshooting/#chrome-reports-sandbox-errors-on-windows)

I raised this issue 5 years back, not facing it now 🙂

**Comment by LojainHassan** [comment]
I am trying alot but I still have issues @kulesshhh 😊
