### ISSUE TITLE
Can this library run on Linux with dotnet core ?

### ISSUE THREAD

**Issue by ndphuong** [kblok/puppeteer-sharp#733]
Hi,

Can this library run on Linux with dotnet core ?

**Comment by kblok** [comment]
It could. We need some help trying to get the CI running on Linux. There is some WIP here https://github.com/kblok/puppeteer-sharp/pull/430. 

Any contributions to this topic will be accepted.

**Comment by kblok** [comment]
Closing, this discussion should be followed on #429
