### ISSUE TITLE
Response.BufferAsync should return ValueTask<byte[]>, not ValueTask<string>

### ISSUE THREAD

**Issue by miroslavp** [kblok/puppeteer-sharp#764]
### Description

Currently `Response.BufferAsync()` returns `ValueTask<string>` which is wrong when the response contains image data. 

Here is the original puppeteer code (not the puppeteer-sharp, but the one from Google) which stores the response data (base64/utf8 strings) to a Buffer object. The Buffer object internally is like array of bytes.

    if (!this._contentPromise) {
      this._contentPromise = this._bodyLoadedPromise.then(async error => {
        if (error)
          throw error;
        const response = await this._client.send('Network.getResponseBody', {
          requestId: this._request._requestId
        });
        return Buffer.from(response.body, response.base64Encoded ? 'base64' : 'utf8');
      });
    }
    return this._contentPromise;

Here is the current puppeteer-sharp code. It converts the uft8/base64 strings to plain string which is wrong, because it mangles the image data.

```csharp
                    _buffer = response.Base64Encoded
                        ? Encoding.UTF8.GetString(Convert.FromBase64String(response.Body))
                        : response.Body;
```

What we need to do is to convert the utf8/base64 string to byte[]. This way, the image data (encoded in base64 string) will not be mangled. It should look like this:

```csharp
                    _buffer = response.Base64Encoded
                        ? Convert.FromBase64String(response.Body)
                        : Encoding.UTF8.GetBytes(response.Body);
```
Of course then the following line

```csharp
public ValueTask<string> TextAsync() => BufferAsync();
```

should be also amended to something like this

```csharp
public async ValueTask<string> TextAsync() => Encoding.UTF8.GetString(await BufferAsync());
```

### Complete minimal example reproducing the issue

The following code is written in C# 7.3 and should be able to store every image from the website to the disk. The thing is, I can't do that because the data parameter is not byte[], but string.

```csharp
    class Program
    {
        static string[] imageMimeTypes = { "image/jpeg", "image/png", "image/webp", "image/bmp", "image/gif" };

        static async Task Main(string[] args)
        {
            await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions
            {
                Headless = true
            });
            var page = await browser.NewPageAsync();
            page.Response += Page_Response;

            await page.GoToAsync("https://anywebsite.that.contains.images");
        }

        private static void Page_Response(object sender, ResponseCreatedEventArgs e)
        {
            string contentType = null;

            if (e.Response.Headers.ContainsKey("content-type"))
                contentType = (string)e.Response.Headers["content-type"];

            if (e.Response.Headers.ContainsKey("Content-Type"))
                contentType = (string)e.Response.Headers["Content-Type"];

            if (imageMimeTypes.Any(t => t == contentType))
            {
                string fileName = null;
                var lastSlashIndex = e.Response.Url.LastIndexOf('/');
                if (lastSlashIndex != -1)
                    fileName = e.Response.Url.Substring(lastSlashIndex + 1);
                else
                    fileName = e.Response.Url;

                e.Response.BufferAsync().AsTask().ContinueWith(async (data) => 
                File.WriteAllBytes($@"c:\Temp\{fileName}", await data));
            }
        }
    }
...
```

### Expected behavior:

Should be able to store base64 encoded images to disk in a raw byte form

### Actual behavior:

Can't do that, because current implementation converts both utf8 and base64 strings to string which corrupts the image data.

### Versions

* Which version of PuppeteerSharp are you using?
1.9.0
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
.NET Core 2.1

### Additional Information

N/A

**Comment by kblok** [comment]
Good catch @miroslavp. I'll take a look at it.
