### ISSUE TITLE
How-To: Reuse a downloaded version of Chrome

### ISSUE THREAD

**Issue by kblok** [kblok/puppeteer-sharp#765]
Let's answer this with a How to
https://stackoverflow.com/questions/53371103/puppeteer-sharp-avoid-downloading-chromium-bundle-chromium-locally

**Comment by kblok** [comment]
@bdurrani in case you want to add another demo :)

**Comment by bdurrani** [comment]
👍 Were you thinking of a runnable example or just a code snippet for this?

**Comment by kblok** [comment]
@bdurrani yes, we could assume that Chromium was downloaded in any other demo project or in the Test Project

**Comment by bdurrani** [comment]
TBH, this seems like it would be better as a code snippet instead of a shipping example.
What do you think? 

Maybe something [here](https://github.com/kblok/puppeteer-sharp/blob/b22848339cef5e53db988318c36175a34df50c67/docfx_project/api/index.md)?

Would it make sense to consolidate all the code snippets in the different places?
Like these two
- https://www.puppeteersharp.com/index.html
- https://www.puppeteersharp.com/api/index.html

**Comment by kblok** [comment]
@bdurrani you know that my dream is having a killing "How to" section. Let's add one more page there.

Just between you I and me 😂 , All those snippets on the home page and the API home page are just to put something in there instead of having a white page. I think we can say more relevant things in those pages instead of just code snippets. 

My goal is having a super cool "How-To" section; we could even start moving those snippets from the home page to How-Tos. So then we can see Google Analytics and confirm how helpful those documents are for the community.

**Comment by bdurrani** [comment]
You mean something similar to this?
https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md

If you can set up a page or something, i can start moving some of the snippets over. I've been trying to build the doc_fx project on my windows 10 machine, but for some reason i just get lots of warnings

`
[18-11-24 02:02:31.675]Warning:[Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html]Warning: Can't load content from index.html: Could not find file 'C:\github\puppeteer-sharp\docs\index.html'.
[18-11-24 02:02:31.678]Warning:[Postprocess.HandlePostProcessorsWithIncremental.HandlePostProcessors.Processing html]Warning: Can't load content from examples/Page.EvaluateExpressionAsync.GetAllLinks.html: Could not find a part of the path 'C:\github\puppeteer-sharp\docs\examples\Page.EvaluateExpressionAsync.GetAllLinks.html'.

I ran the following
`
docfx metadata .\docfx_project\docfx.json
docfx build .\docfx_project\docfx.json -o docs
`
Thanks
