### ISSUE TITLE
BrowserFetcher downloads chromium by default to current directory (not to .dlls folder)

### ISSUE THREAD

**Issue by videokojot** [kblok/puppeteer-sharp#799]
### Description

BrowserFetcher.cs by default downloads chromium binaries to current working directory
[BroswerFetcher.cs](https://github.com/kblok/puppeteer-sharp/blob/8dbd6ff9e14051b3262ab79993c1c4ba993e9af0/lib/PuppeteerSharp/BrowserFetcher.cs)

 ```csharp
...
     DownloadsFolder = Path.Combine(Directory.GetCurrentDirectory(), ".local-chromium");
...
```

 instead of to the directory where the binaries of project are located (as specified in BrowserFetcherOptions xml doc)
[BrowserFetcherOptions.cs](https://github.com/kblok/puppeteer-sharp/blob/c65c6d840484f8c65a2d5bbee2de44ecf4688529/lib/PuppeteerSharp/BrowserFetcherOptions.cs)

 ```csharp
//...
        /// <summary>
        /// A path for the downloads folder. Defaults to [root]/.local-chromium, where [root] is where the project binaries are located.
        /// </summary>
        public string Path { get; set; }
//...
```

### Expected behavior:

Either change the documentation, but better would be to download by default to the [root]/.local-chromium, where [root] is where the project binaries are located.

ie:
 ```csharp
//...
     DownloadsFolder =
 Path.Combine(Path.GetDirectoryName(Assembly.GetEntryAssembly().Location), 
".local-chromium");
//...
```

I can make PR for this - but the change is very small.

### Versions

* Which version of PuppeteerSharp are you using?
1.10
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
happens on both

**Comment by Meir017** [comment]
would this mean that for each runtime it will download another copy since the output directory is different for each runtime?

**Comment by kblok** [comment]
Yes. but it would also would mean that if my app is at `c:\myapp` and I call it from `c:\` or from `c:\myapp\`. Local-chromium would be always on `c:\myapp\.local-chromium`.  Now we are creating two `.local.chromium` folders: one in `c:\` and another in `c:\myapp`.

**Comment by Meir017** [comment]
hmm, I would have preferred if there would be a cache directory in the user-profile dir (similar to `.nuget`, `.vscode` ).
The new default behavior makes sense.

How about adding an overload with an enum argument:
- in current dir
- in binaries dir
- in user profile
?
I think this will simplify things

**Comment by videokojot** [comment]
I stumbled upon this because I am have simple PuppeteerSharp wrapper, which periodically kills zombie chromium processes (sometimes some of the puppeteer waited calls just freeze outside of the managed code) and I wanted to be able to locate which process (or assembly) started it, to just kill those chromiums... I can account for this in my code (by setting the Path property in BrowserFetcher explictily)- but found the documentation was misleading...

@Meir017 I like this idea of enum & user profile cache folder.

**Comment by kblok** [comment]
We won't implement this because we have a way to solve this using `Path`

**Comment by yene** [comment]
would be nice to configure DownloadsFolder, to have more control about how the filesystem is used. e.g. with containers
