### ISSUE TITLE
After using elementHandle.EvaluateFunctionAsync(...) elementHandle variable is disposed 

### ISSUE THREAD

**Issue by pclaudiuc** [kblok/puppeteer-sharp#832]
### Description

After using elementHandle.EvaluateFunctionAsync(...) elementHandle variable is disposed 

### Complete minimal example reproducing the issue
await elementHandle.EvaluateFunctionAsync(...)
await elementHandle.QuerySelectorAsync(...) throws "PuppeteerException: JSHandle is disposed!"

### Expected behavior:

elementHandle.Disposed=false;
Original implementation for node.js let you use elementHandle countless time without disposing automatically(disposing should be developer task, i guess)

### Actual behavior:

elementHandle.Disposed=true;

### Versions

* Which version of PuppeteerSharp are you using?
1.11.1
* Which .NET runtime and version are you targeting? E.g. .NET framework 4.6.1 or .NET Core 2.0.
4.6.1

**Comment by kblok** [comment]
@pclaudiuc I checked this and you are right, we are disposing the elementHandle, but so does Puppeteer.

Reference
https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Extensions.cs#L61
and
https://github.com/GoogleChrome/puppeteer/blob/master/lib/ExecutionContext.js#L571

Could you share some NodeJS code so we can compare?

**Comment by pclaudiuc** [comment]
[scrap-test.zip](https://github.com/kblok/puppeteer-sharp/files/2723686/scrap-test.zip)

**Comment by pclaudiuc** [comment]
```
import puppeteer from "puppeteer"

async function Test() {
    const browser = await puppeteer.launch();
    const page = await browser.newPage();
    await page.goto('https://developers.google.com/web/');
    let item = await page.$(".wf-hero-flex-item.wf-hero-webfu");
    if (item != null) {
        console.log(await item.$eval("h3", el => el.textContent))
        console.log(await item.$eval("h3", el => el.textContent))
    }
    await browser.close();
}
Test().then(() => {

})
```

**Console:**

_Web Fundamentals
Web Fundamentals_

**Comment by pclaudiuc** [comment]
in original implementation elemenHandle disposed is the one represented by selector
```
async $eval(selector, pageFunction, ...args) {
    const **elementHandle** = await this.$(selector);
    if (!elementHandle)
      throw new Error(`Error: failed to find element matching selector "${selector}"`);
    const result = await this.executionContext().evaluate(pageFunction, elementHandle, ...args);
    await **elementHandle**.dispose();
    return result;
  } 
```

**Comment by pclaudiuc** [comment]
```
 public static async Task<T> EvaluateFunctionAsync<T>(this ElementHandle **elementHandle**, string pageFunction, params object[] args)
        {
            if (**elementHandle** == null)
            {
                throw new SelectorException("Error: failed to find element matching selector");
            }

            var newArgs = new object[args.Length + 1];
            newArgs[0] = elementHandle;
            args.CopyTo(newArgs, 1);
            var result = await elementHandle.ExecutionContext.EvaluateFunctionAsync<T>(pageFunction, newArgs).ConfigureAwait(false);
            await `elementHandle`.DisposeAsync().ConfigureAwait(false);
            return result;
        }
```

**Comment by kblok** [comment]
Does your code look something like this?
```cs 
var item = await page.QuerySelectorAsync(".wf-hero-flex-item.wf-hero-webfu");
Console.WriteLine(await item.QuerySelectorAsync("h3").EvaluateFunctionAsync<string>("el => el.textContent");
```

**Comment by pclaudiuc** [comment]
in node.js i can use elementHandle.$eval() countless times without elementHandle being disposed(internally it's disposed element handle pointed by selector - first argument)
in your implementation elementHandle.EvaluateFunctionAsync(..) can be called only once on the same variable

**Comment by kblok** [comment]
There we are disposing the element for `h3`. we should be able to do this.

```cs
var item = await page.QuerySelectorAsync(".wf-hero-flex-item.wf-hero-webfu");
Console.WriteLine(await item.QuerySelectorAsync("h3").EvaluateFunctionAsync<string>("el => el.textContent");
Console.WriteLine(await item.QuerySelectorAsync("h3").EvaluateFunctionAsync<string>("el => el.textContent");
```

We are not  disposing `item`, but `QuerySelectorAsync("h3")`.

**Comment by kblok** [comment]
I'm getting your point. But I'm struggling with your issue and honor Puppeteer's implementation.

Puppeteer doesn't have an `eval` function in his ElementHandle class. Our `QuerySelectorAsync().EvaluateFunctionAsync()` maps to `$$eval` (we are not able to name a mehod `$$`.

What you could do is `page.EvaluteFunctionAsync` and passing the item as an argument:

```cs
await page.EvaluteFunctionAsync<bool>(@"(el)=>{let catName = el.getAttribute('data-category-name');
                    return catName === 'Smartwatch'}", **item**);
```

I'm open to ideas, but let's remember that our first goal is to be a port.
We could add a comment in the XML docs.

**Comment by pclaudiuc** [comment]
page.EvaluateFunctionAsync() it's working as you suggested(passing the item as an argument)

My suggestion: overload  ElementHandle.EvaluateFunctionAsync() by adding as first argument a string  selector 

Thank you for bringing puppeteer on .net world!
Great job!
