### ISSUE TITLE
DllNotFoundException: Unable to load shared library 'MonoPosixHelper' or one of its dependencies. 

### ISSUE THREAD

**Issue by gonzocode** [kblok/puppeteer-sharp#845]
### Description

I cant get puppeteer to work on Mac OSX, is it supported ?

Im just running one of the simple examples from this repo.
I get the following exception when i run my app:

 An unhandled exception occurred while processing the request.
DllNotFoundException: Unable to load shared library 'MonoPosixHelper' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libMonoPosixHelper, 1): image not found
PuppeteerSharp.Helpers.Linux.LinuxSysCall.FromFilePermissions(FilePermissions value, out uint rval)

Fails on this line:

```csharp
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);  
```

### Versions

PuppeteerSharp 1.11.1
.Net Core 2.2.102
Mac OSX High Sierra 10.13.3

**Comment by kblok** [comment]
@gonzocode MacOS is my main dev environment, so yes :)

It's weird because I'm not getting that issue. That should be provided by Mono. On the other hand, we should try to fix file permissions on Mac. So I'll change that and release 1.11.2 tomorrow.
