### ISSUE TITLE
Possible bug? Having issues running puppeteer on raspbian lite(stretch)

### ISSUE THREAD

**Issue by atresnjo** [kblok/puppeteer-sharp#851]
OS: Linux retropie 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux
Runtime: .NET Core 2.2.0
Built with: dotnet publish -r linux-arm -c Release

When puppeteer finishes downloading the following exception is being thrown:![putty_2019-01-13_18-39-06](https://user-images.githubusercontent.com/41112852/51088938-1d77bc00-1766-11e9-889a-70d0ad098135.png)

Next start it would throw 

`System.ComponentModel.Win32Exception (8): Exec format error`

So I commented it out and downloaded the latest chromium-browser package myself, replaced the files puppeteer-sharp downloaded with the files from the chromium-browser package and then it worked as expected.

Now I'm not sure if puppeteer is downloading the wrong files, or my initial download was corrupted due to the first exception? Thanks for the great library!

**Comment by Mese1953** [comment]
@atresnjo Which chromium-browser package did you download? I have the same error and would like to try the workaround.

**Comment by atresnjo** [comment]
> 
> 
> You are not the first here. We got the same question related `MonoPosixHelper` before.
> I thought that library was included in Mono. I would appreciate any documentation related to that.

Not sure I can help with that. I didn't download Mono on the machine. Is that required? 
All I did was download the .NET Core runtime.

> 
> 
> @atresnjo Which chromium-browser package did you download? I have the same error and would like to try the workaround.

apt-get install chromium-browser

then replaced the contents and that was it, one more thing was that I had to rename the chromium instance from "chromium-something" to "chromium" because puppeter looks for that name in the folder.

**Comment by kblok** [comment]
So, yes. It turns out that you need to install Mono and .NET Core in Linux. I didn't know about that

**Comment by atresnjo** [comment]
> 
> 
> So, yes. It turns out that you need to install Mono and .NET Core in Linux. I didn't know about that. Could you try downloading mono @atresnjo ?

I downloaded mono-complete and the exception disappeared, so that solved it. Another issue that's remaining is that the BrowseFetcher downloads the wrong version.

![grafik](https://user-images.githubusercontent.com/41112852/52533902-bc2e1300-2d3a-11e9-88f1-46454ceefa54.png)

Did some research and this apparently happens when the binary is for the wrong architecture 

I'll try later a package from https://packages.debian.org/en/stretch/chromium and see if that will work.
