### ISSUE TITLE
Cannot download Chromium on Mac

### ISSUE THREAD

**Issue by calfrei** [kblok/puppeteer-sharp#899]
### Description

Trying to download Chromium with BrowserFetcher on Mac OS X High Sierra and Mojave but when mac-chrome.zip is downloaded it gets deleted.

It works perfectly on several Windows Environments.

```
BrowserFetcher browserFetcher = new BrowserFetcher(new BrowserFetcherOptions
{
	Path = path
});

await browserFetcher.DownloadAsync(revision);

LaunchOptions options = new LaunchOptions
{
	Args = ...,
	Headless = true,
	ExecutablePath = browserFetcher.GetExecutablePath(revision)
};

Browser = await Puppeteer.LaunchAsync(options);
```

I've tried several Paths for Mac OS X, also the default setting doesn't work.
Also tried the "App Data" Path for Mac OS X in "/Users/USERNAME/Library/Application Support/".

I see that it can download the mac-chrome.zip file but as I mentioned above it get's deleted.

It also doesn't work when I set chmod 777 for "everyone" on .local-chromium with sudo.

### Versions

* PuppeteerSharp v1.11.2
* .NET Core 2.2
* Mac OS X High Sierra and Mac OS X Mojave

### Additional Information

If I download the mac-chrome.zip manually it works...

**Comment by kblok** [comment]
MacOS is my main development platform and it's working here. Could you debug it and see where is getting stuck?

**Comment by kasperpedersen** [comment]
@calfrei, did you try with a path that doesn't contain any spaces? I had issues with directories that had spaces in them.

I think the unzip method used on macOS isn't quoting arguments with spaces: https://github.com/kblok/puppeteer-sharp/blob/60a0ba6a9098dea53e42c62a4529dbb3e97d59fc/lib/PuppeteerSharp/BrowserFetcher.cs#L278

**Comment by calfrei** [comment]
@kasperpedersen Thanks for the hint and sorry for late reply... the user which has problems has his first and lastname (with spaces) so this might be an issue. Will try to explain to the user if it's possible to create another user to test that scenario.
