### ISSUE TITLE
Unusable screenshot quality.

### ISSUE THREAD

**Issue by rgelb** [kblok/puppeteer-sharp#921]
### Description

The quality of the generated image is unusable.  Example: https://i.imgur.com/V0au5hf.png

### Complete minimal example reproducing the issue

The code that I adapted off the main readme.md page.

```csharp
await new BrowserFetcher().DownloadAsync(BrowserFetcher.DefaultRevision);
var browser = await Puppeteer.LaunchAsync(new LaunchOptions
{
    Headless = true
});
var page = await browser.NewPageAsync();
await page.GoToAsync("http://www.google.com");

string outputFile = @"C:\Users\HomeUser\Desktop\output2.jpg";
await page.ScreenshotAsync(outputFile);
```

### Expected behavior:

Better quality.

### Actual behavior:

Unusable quality

### Versions

* Which version of PuppeteerSharp are you using?  1.11.2 (via Nuget)
* Which .NET runtime and version are you targeting? I tried both .net framework 4.7.2 and .net core 2.2 with same results.

### Additional Information

It downloads .local-chromium/Win64-609904 into the bin/debug folder.  Not sure why it's happening.  I looked around the namespace and couldn't find any Quality properties.

![output2](https://user-images.githubusercontent.com/1064250/52882849-d2164c00-311d-11e9-8e96-e79ef1e85d53.jpg)

**Comment by kblok** [comment]
Could you try saving the file as png?

**Comment by rgelb** [comment]
@kblok  Thank you - that did the trick.  So looks like the default JPG quality is off.  Is there a lever to adjust that (so I can skip the additional step of converting png to jpg)?

**Comment by kblok** [comment]
You have a `Quality` property on the ScreenShotOptions https://github.com/kblok/puppeteer-sharp/blob/6bfb2703b66f8e4caa2cf896b0e76272f29e2941/lib/PuppeteerSharp/ScreenshotOptions.cs#L46

You can also set that to 100.

**Comment by kblok** [comment]
Feel free to reopen it if needed.

**Comment by rgelb** [comment]
@kblok Thank you.  This works for me.  But I submitted a PR to fix this issue for the next person who encounters it.
