### ISSUE TITLE
Disconnected event not fired when using Disconnect method

### ISSUE THREAD

**Issue by szilardx** [kblok/puppeteer-sharp#927]
### Description

I tried using the Browser.Disconnect method for debugging purposes.
When calling it, it does not fire Browser.Disconnected event. Browser.CloseAsync does. 

### Complete minimal example reproducing the issue

```csharp
            var browser = await Puppeteer.LaunchAsync(new LaunchOptions());

            //the handler is only called when using await browser.CloseAsync();
            browser.Disconnected +=(s,e) =>Console.WriteLine("Disconnected event hit!");

            var page = browser.NewPageAsync();
            browser.Disconnect();

```

### Versions

* Which version of PuppeteerSharp are you using? - 1.11.2
* Which .NET runtime and version are you targeting? .NET framework 4.6.1

**Comment by kblok** [comment]
Why would you want to Launch a process and then disconnect (instead of close) from it?
This would orphan the Chromium process.

You should use one of these pairs of calls:

* You `LaunchAsync` and then you `CloseAsync`.
* You `ConnectAsync` and then you `Disconnect`.

**Comment by szilardx** [comment]
Thanks for the clarification! I use `LaunchAsync` then work on a `Page` for a long period, and then `CloseAsync`. I do 2 separate task simultaneously from one .NET process, in two separate browser process (so if one crashes, it won't kill the other).
But I have random WebSocket disconnect issues. (like once every day) At first I thought it would be a good idea to reconnect to the browser, and continue on the `Page` where the script stopped working. 
So I was testing out `ConnectAsync`, but in order to test it, I needed to create the disconnected situation manually.
I found that there is a `Disconnected` event, and the summary description says "Raised when ... Disconnect method was called". 

Now, I realized it is better to start my process from scratch in the event of a WebSocket disconnect Exception, but it might be a good idea still to reconnect to the existing browser to close it, or to reuse it.

**Comment by kblok** [comment]
@szilardx I closed the Reconnect issue because I don't think the WebSocket connect just breaks. There might be something else going that breaks the connection (or the browser). So we would need to work on that issue instead of the reconnect.

**Comment by szilardx** [comment]
@kblok Okay, I'll try to get some logs from Chromium too.
