### ISSUE TITLE
Screenshot in headless mode

### ISSUE THREAD

**Issue by jhdscript** [kblok/puppeteer-sharp#944]
Hello,

 for a project in need to capture a screenshot in headless mode.

I try to do it with puppeteer-sharp but the task ScreenshotAsync never returns after called.

How can i take a screenshot in headless mode ?

Thanx in advance

**Comment by jhdscript** [comment]
I use this args in cmdline: --disable-features=MojoVideoCapture,SurfaceSynchronization

Maybe it s the problem

**Comment by kblok** [comment]
Could you share some code?

**Comment by jhdscript** [comment]
My issue in fact is screenshot take lot of time:

`
    Dim s As String = Await ChromiumPage.ScreenshotBase64Async()
        await ChromiumPage.ScreenshotAsync("test_.png")
        Dim s1 As New Stopwatch
        s1.Start()
        For i As Integer = 0 To 50
            await ChromiumPage.ScreenshotDataAsync()
        Next
        s1.Stop
`

For 50 screenshot it tooks more than 20 seconds :-(
There is a better way to capture 30 screenshot in 1 second ? Maybe access directly to chromium buffer ?

**Comment by kblok** [comment]
We had some discussions about performance here https://github.com/kblok/puppeteer-sharp/issues/703
After that we implemented a Burst Mode which might help you to get some speed bump https://github.com/kblok/puppeteer-sharp/pull/705

**Comment by jhdscript** [comment]
Burst mode is better but still very slow :-(

**Comment by kblok** [comment]
No plans to improve this yet.
