### ISSUE TITLE
Ensure Targets are always closed

### ISSUE THREAD

**Issue by ggeurts** [kblok/puppeteer-sharp#948]
`Target` closure is initiated by the `Page` class by a task that is scheduled in its constructor. This task will only complete when `Target.CloseTask` completes. However, `Target.CloseTask` only completes when `Browser` receives a DestroyTarget message. If for some reason this message never arrives, the `Page` will hang indefinitely on closure.

**Comment by kblok** [comment]
Is there any way to reproduce this with a test?

**Comment by ggeurts** [comment]
Yep,

        [Fact(Timeout =  5000)]
        public async Task ShouldCloseWhenConnectionBreaksPrematurely()
        {
            Browser.Connection.Dispose();
            await Page.CloseAsync();
        }

**Comment by kblok** [comment]
Awesome!

**Comment by ggeurts** [comment]
This tests also highlights a bug in ChromeProcess kill timeout
