### ISSUE TITLE
Defunct process issue under latest version

### ISSUE THREAD

**Issue by mesanja** [kblok/puppeteer-sharp#996]
[Using puppeteer-sharp under asp.net .net core 2.2 keeps defunct chrome processes when Puppeteer object is disposed]

Steps to reproduce:

1. Install asp.net core 2.2 api
2. With simple request call puppeteer, lunch browser, get content close browser
3. Observe a lot of defunct processes 
4. Sooner or later observer Docker: "No space left on device"

```csharp
 using (var browser = await Puppeteer.LaunchAsync(options).ConfigureAwait(false))
  {
                var allPages = await browser.PagesAsync().ConfigureAwait(false);
                var page = allPages.First();

                try
                {
                    await page.SetBypassCSPAsync(true);
                    await page.SetRequestInterceptionAsync(true).ConfigureAwait(false);

                    DisableMediaContent(page);

                   // navigation to page omitted here
                }
}
```
![image](https://user-images.githubusercontent.com/14080769/54061311-f939d800-4208-11e9-900e-efd5234e4f33.png)

What I am doing wrong? Any recommendations are much appreciated. Thank you in advance.

**Comment by kblok** [comment]
Hey @mesanja. It seems Puppeteer also have this issue. Could you check this issue and see if any of the comments there help?
https://github.com/GoogleChrome/puppeteer/issues/1825

**Comment by mesanja** [comment]
> Hey @mesanja. It seems Puppeteer also have this issue. Could you check this issue and see if any of the comments there help?
> [GoogleChrome/puppeteer#1825](https://github.com/GoogleChrome/puppeteer/issues/1825)

Hi @kblok thanks for response, they propose to use dumb-init, but we should have separate runner for chromium. I was thinking about console app that will encapsulate all work with puppeteer-sharp in order for chromium to have that console app as parent, so we could send kill -s 9 console_app_pid.

**Comment by kblok** [comment]
I ran into some issues when running Puppeteer-Sharp on a machine with low resources. I did this:

```cs
_chromiumProcessID = browser.Process.Id;

public static void EnforceChromiumClose()
{
    var process = Process.GetProcessById(_chromiumProcessID);
    if (_chromiumProcessID > 0 && process?.HasExited == false)
    {
        process.Kill();
    }
}
``` 

Not clean at all. But if Chromium can't gracefully close itself. I would force kill it.

**Comment by ggeurts** [comment]
Which Puppeteersharp version does the problem occur with? We recently fixed a chromium close timeout issue.

**Comment by mesanja** [comment]
It's turned out that issue is not related to puppeteer it self but for docker nature. In order to wipe zombies I used this solution https://github.com/Yelp/dumb-init.
For anyone who faced with same issue, please use dumb-init.

Thanks all.

**Comment by kblok** [comment]
@mesanja thank you for sharing that back here!
